-- ASSIGNMENT INSERTS
INSERT INTO Assignment (a_desc, a_due_date, c_code) VALUES
('Perform a code review of the provided pull request. Submit written feedback addressing style, logic, and security.', '2025-10-16', 'SWEN1340'),
('Produce a full requirements specification document for a e-learning system, including use cases and user stories.', '2025-10-31', 'SWEN1340'),
('Create a UML class diagram and sequence diagram for the retail system described in the case study.', '2025-11-19', 'SWEN1340'),
('Write a test plan and execute test cases for the provided ride-sharing application. Submit a defect report.', '2025-11-30', 'SWEN1340'),
('Create a UML class diagram and sequence diagram for the healthcare system described in the case study.', '2025-03-06', 'SWEN1765'),
('Write a test plan and execute test cases for the provided hospital management application. Submit a defect report.', '2025-04-17', 'SWEN1765'),
('Evaluate two competing cloud storage frameworks and recommend one for a given business scenario.', '2025-01-18', 'INFO2930'),
('Design a normalised relational schema for a education system. Include an ER diagram and justification.', '2025-02-03', 'INFO2930'),
('Write a report analysing the information security risks facing a education organisation.', '2025-04-16', 'INFO2930'),
('Develop a business intelligence report for a education company using the tools discussed in class.', '2025-04-24', 'INFO2930'),
('Using the provided dataset, perform exploratory data analysis and present your findings in a dashboard.', '2025-04-28', 'INFO2930'),
('Implement a binary search tree in Python. Your solution must handle edge cases and include unit tests.', '2025-10-21', 'COMP2738'),
('Design and build a desktop application using C++. Submit source code and a README.', '2025-11-16', 'COMP2738'),
('Analyse the time and space complexity of the provided compression algorithm. Write a report justifying your findings.', '2025-11-20', 'COMP2738'),
('Using the provided dataset, perform exploratory data analysis and present your findings in a dashboard.', '2025-10-21', 'INFO2977'),
('Evaluate two competing ERP frameworks and recommend one for a given business scenario.', '2025-11-15', 'INFO2977'),
('Write a report analysing the information security risks facing a healthcare organisation.', '2025-12-14', 'INFO2977'),
('Using the provided dataset, perform exploratory data analysis and present your findings in a dashboard.', '2025-02-16', 'INFO1085'),
('Evaluate two competing data warehouse frameworks and recommend one for a given business scenario.', '2025-03-08', 'INFO1085'),
('Design a normalised relational schema for a retail system. Include an ER diagram and justification.', '2025-03-26', 'INFO1085'),
('Using the provided dataset, perform exploratory data analysis and present your findings in a dashboard.', '2025-09-22', 'INFO1390'),
('Write a report analysing the information security risks facing a education organisation.', '2025-09-28', 'INFO1390'),
('Design a normalised relational schema for a banking system. Include an ER diagram and justification.', '2025-10-06', 'INFO1390'),
('Evaluate two competing CRM frameworks and recommend one for a given business scenario.', '2025-10-20', 'INFO1390'),
('Develop a business intelligence report for a logistics company using the tools discussed in class.', '2025-12-05', 'INFO1390'),
('Perform a code review of the provided pull request. Submit written feedback addressing style, logic, and security.', '2025-11-29', 'SWEN3258'),
('Produce a full requirements specification document for a ride-sharing system, including use cases and user stories.', '2025-12-03', 'SWEN3258'),
('Write a test plan and execute test cases for the provided e-learning application. Submit a defect report.', '2025-12-11', 'SWEN3258'),
('Write a short essay comparing two approaches to statistics, with worked examples for each.', '2025-03-07', 'MATH1775'),
('Prove the following numerical methods theorems using the methods covered in lectures.', '2025-03-11', 'MATH1775'),
('Complete the problem set on calculus. Show all working - answers without justification will not receive credit.', '2025-03-06', 'MATH2417'),
('Model the real-world scenario below using statistics techniques and interpret your results.', '2025-04-26', 'MATH2417'),
('Write a short essay comparing two approaches to discrete mathematics, with worked examples for each.', '2025-10-13', 'MATH2210'),
('Solve the attached discrete mathematics problem set and verify your answers using any computational tool.', '2025-12-08', 'MATH2210'),
('Model the real-world scenario below using discrete mathematics techniques and interpret your results.', '2025-09-12', 'MATH3187'),
('Prove the following numerical methods theorems using the methods covered in lectures.', '2025-11-09', 'MATH3187'),
('Write a short essay comparing two approaches to discrete mathematics, with worked examples for each.', '2025-11-29', 'MATH3187'),
('Solve the attached numerical methods problem set and verify your answers using any computational tool.', '2025-12-02', 'MATH3187'),
('Write a short essay comparing two approaches to statistics, with worked examples for each.', '2025-11-24', 'MATH1714'),
('Model the real-world scenario below using calculus techniques and interpret your results.', '2025-12-10', 'MATH1714'),
('Write a short essay comparing two approaches to statistics, with worked examples for each.', '2025-03-06', 'MATH1373'),
('Prove the following number theory theorems using the methods covered in lectures.', '2025-03-30', 'MATH1373'),
('Solve the attached calculus problem set and verify your answers using any computational tool.', '2025-04-19', 'MATH1373'),
('Model the real-world scenario below using number theory techniques and interpret your results.', '2025-04-14', 'MATH1773'),
('Solve the attached probability problem set and verify your answers using any computational tool.', '2025-04-25', 'MATH1773'),
('Research and summarise the industrial applications of spectroscopy. Cite at least five peer-reviewed sources.', '2025-09-25', 'CHEM1658'),
('Prepare a safety data summary for the reagents used in the organic synthesis lab and assess associated hazards.', '2025-09-25', 'CHEM1658'),
('Complete the reaction mechanism worksheet for electrochemistry. Clearly label all intermediates and arrow-pushing steps.', '2025-11-27', 'CHEM1658'),
('Write a formal lab report for the thermochemistry experiment conducted in Week 6. Follow the standard report format.', '2025-04-10', 'CHEM2807'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-04-13', 'CHEM2807'),
('Write a formal lab report for the acid-base reactions experiment conducted in Week 3. Follow the standard report format.', '2025-09-10', 'CHEM1997'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-10-10', 'CHEM1997'),
('Research and summarise the industrial applications of electrochemistry. Cite at least five peer-reviewed sources.', '2025-11-15', 'CHEM1997'),
('Prepare a safety data summary for the reagents used in the thermochemistry lab and assess associated hazards.', '2025-11-16', 'CHEM1997'),
('Complete the reaction mechanism worksheet for electrochemistry. Clearly label all intermediates and arrow-pushing steps.', '2025-12-09', 'CHEM1997'),
('Write a formal lab report for the thermochemistry experiment conducted in Week 5. Follow the standard report format.', '2025-02-03', 'CHEM2920'),
('Research and summarise the industrial applications of thermochemistry. Cite at least five peer-reviewed sources.', '2025-04-23', 'CHEM2920'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-02-26', 'CHEM2771'),
('Prepare a safety data summary for the reagents used in the electrochemistry lab and assess associated hazards.', '2025-03-20', 'CHEM2771'),
('Complete the reaction mechanism worksheet for organic synthesis. Clearly label all intermediates and arrow-pushing steps.', '2025-04-02', 'CHEM2771'),
('Write a formal lab report for the spectroscopy experiment conducted in Week 8. Follow the standard report format.', '2025-04-12', 'CHEM2771'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-09-10', 'CHEM2882'),
('Prepare a safety data summary for the reagents used in the spectroscopy lab and assess associated hazards.', '2025-10-21', 'CHEM2882'),
('Research and summarise the industrial applications of electrochemistry. Cite at least five peer-reviewed sources.', '2025-10-23', 'CHEM2882'),
('Complete the reaction mechanism worksheet for polymer chemistry. Clearly label all intermediates and arrow-pushing steps.', '2025-11-29', 'CHEM2882'),
('Complete the reaction mechanism worksheet for electrochemistry. Clearly label all intermediates and arrow-pushing steps.', '2025-03-29', 'CHEM3064'),
('Prepare a safety data summary for the reagents used in the electrochemistry lab and assess associated hazards.', '2025-04-11', 'CHEM3064'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-04-15', 'CHEM3064'),
('Solve the simple harmonic motion problem set. Include free-body diagrams where applicable.', '2025-09-06', 'PHYS2551'),
('Analyse the experimental data provided using simple harmonic motion principles and present your conclusions.', '2025-10-22', 'PHYS2551'),
('Research a real-world application of simple harmonic motion and write a two-page technical summary.', '2025-11-11', 'PHYS2551'),
('Derive the equations of motion for the given electromagnetic induction system from first principles.', '2025-01-16', 'PHYS2123'),
('Analyse the experimental data provided using wave optics principles and present your conclusions.', '2025-03-04', 'PHYS2123'),
('Solve the wave optics problem set. Include free-body diagrams where applicable.', '2025-04-14', 'PHYS2123'),
('Write a lab report for the thermodynamics experiment. Compare your results to the theoretical values and discuss errors.', '2025-04-14', 'PHYS2123'),
('Analyse the experimental data provided using quantum mechanics principles and present your conclusions.', '2025-09-19', 'PHYS2867'),
('Research a real-world application of thermodynamics and write a two-page technical summary.', '2025-11-22', 'PHYS2867'),
('Write a lab report for the wave optics experiment. Compare your results to the theoretical values and discuss errors.', '2025-11-23', 'PHYS2867'),
('Solve the electromagnetic induction problem set. Include free-body diagrams where applicable.', '2025-11-24', 'PHYS2867'),
('Write a lab report for the thermodynamics experiment. Compare your results to the theoretical values and discuss errors.', '2025-10-16', 'PHYS3356'),
('Derive the equations of motion for the given projectile motion system from first principles.', '2025-11-12', 'PHYS3356'),
('Solve the wave optics problem set. Include free-body diagrams where applicable.', '2025-10-31', 'PHYS1967'),
('Derive the equations of motion for the given electromagnetic induction system from first principles.', '2025-11-13', 'PHYS1967'),
('Research a real-world application of simple harmonic motion and write a two-page technical summary.', '2025-12-05', 'PHYS1967'),
('Solve the simple harmonic motion problem set. Include free-body diagrams where applicable.', '2025-04-07', 'PHYS3025'),
('Derive the equations of motion for the given projectile motion system from first principles.', '2025-04-29', 'PHYS3025'),
('Research a real-world application of wave optics and write a two-page technical summary.', '2025-01-28', 'PHYS3230'),
('Analyse the experimental data provided using simple harmonic motion principles and present your conclusions.', '2025-02-21', 'PHYS3230'),
('Write a lab report for the wave optics experiment. Compare your results to the theoretical values and discuss errors.', '2025-03-16', 'PHYS3230'),
('Derive the equations of motion for the given electromagnetic induction system from first principles.', '2025-03-25', 'PHYS3230'),
('Solve the quantum mechanics problem set. Include free-body diagrams where applicable.', '2025-03-30', 'PHYS3230'),
('Critically evaluate two research papers on cellular respiration and compare their methodologies and conclusions.', '2025-12-04', 'BIOL2230'),
('Create an annotated diagram of the natural selection process, explaining each stage in your own words.', '2025-12-07', 'BIOL2230'),
('Write an essay discussing the role of natural selection in human disease. Use at least six academic references.', '2025-02-20', 'BIOL2783'),
('Create an annotated diagram of the the immune system process, explaining each stage in your own words.', '2025-03-01', 'BIOL2783'),
('Critically evaluate two research papers on cellular respiration and compare their methodologies and conclusions.', '2025-04-01', 'BIOL2783'),
('Design a controlled experiment to investigate the effect of an environmental variable on mitosis.', '2025-04-11', 'BIOL2783'),
('Prepare a lab report on the natural selection experiment from Week 5. Include your hypothesis, results, and discussion.', '2025-04-22', 'BIOL2783'),
('Write an essay discussing the role of cellular respiration in human disease. Use at least six academic references.', '2025-03-19', 'BIOL1856'),
('Prepare a lab report on the DNA replication experiment from Week 6. Include your hypothesis, results, and discussion.', '2025-04-24', 'BIOL1856'),
('Design a controlled experiment to investigate the effect of an environmental variable on mitosis.', '2025-02-19', 'BIOL2226'),
('Critically evaluate two research papers on enzyme kinetics and compare their methodologies and conclusions.', '2025-03-10', 'BIOL2226'),
('Create an annotated diagram of the enzyme kinetics process, explaining each stage in your own words.', '2025-04-24', 'BIOL3225'),
('Design a controlled experiment to investigate the effect of an environmental variable on natural selection.', '2025-04-25', 'BIOL3225'),
('Write an essay discussing the role of enzyme kinetics in human disease. Use at least six academic references.', '2025-04-25', 'BIOL1382'),
('Design a controlled experiment to investigate the effect of an environmental variable on mitosis.', '2025-04-26', 'BIOL1382'),
('Design a controlled experiment to investigate the effect of an environmental variable on DNA replication.', '2025-10-02', 'BIOL1925'),
('Prepare a lab report on the DNA replication experiment from Week 6. Include your hypothesis, results, and discussion.', '2025-11-12', 'BIOL1925'),
('Critically evaluate two research papers on mitosis and compare their methodologies and conclusions.', '2025-12-01', 'BIOL1925'),
('Write an essay discussing the role of mitosis in human disease. Use at least six academic references.', '2025-12-07', 'BIOL1925'),
('Create an annotated diagram of the enzyme kinetics process, explaining each stage in your own words.', '2025-12-11', 'BIOL1925'),
('Write a 500-word essay in Spanish on the topic of the environment. Focus on grammatical accuracy and vocabulary range.', '2025-02-13', 'SPAN3405'),
('Record a two-minute spoken response in Spanish describing technology. Submit as an audio file.', '2025-03-09', 'SPAN3405'),
('Translate the provided passage from English to Spanish, preserving tone and meaning.', '2025-03-24', 'SPAN3405'),
('Write a 500-word essay in Spanish on the topic of family life. Focus on grammatical accuracy and vocabulary range.', '2025-03-01', 'SPAN1630'),
('Record a two-minute spoken response in Spanish describing family life. Submit as an audio file.', '2025-03-21', 'SPAN1630'),
('Prepare a written dialogue in Spanish between two characters discussing the environment.', '2025-04-13', 'SPAN1630'),
('Analyse the grammatical structures used in the provided Spanish text and annotate them with explanations.', '2025-04-14', 'SPAN1630'),
('Translate the provided passage from English to Spanish, preserving tone and meaning.', '2025-04-21', 'SPAN1630'),
('Translate the provided passage from English into Japanese.', '2025-03-30', 'JAPA3124'),
('Complete the grammar exercises for the structures covered in Weeks 3-6.', '2025-03-31', 'JAPA3124'),
('Write a dialogue in Japanese between two characters meeting for the first time.', '2025-04-23', 'JAPA3124'),
('Write a dialogue in Mandarin between two people discussing travel.', '2025-11-22', 'CHIN1048'),
('Translate the provided English passage into Mandarin Chinese.', '2025-12-03', 'CHIN1048'),
('Record yourself reading the provided Mandarin text aloud. Submit as an audio file.', '2025-12-06', 'CHIN1048'),
('Translate the provided passage from English to Spanish, preserving tone and meaning.', '2025-03-09', 'SPAN1368'),
('Write a 500-word essay in Spanish on the topic of technology. Focus on grammatical accuracy and vocabulary range.', '2025-04-09', 'SPAN1368'),
('Translate the provided passage from English to Spanish, preserving tone and meaning.', '2025-10-20', 'SPAN2548'),
('Analyse the grammatical structures used in the provided Spanish text and annotate them with explanations.', '2025-11-09', 'SPAN2548'),
('Prepare a written dialogue in Spanish between two characters discussing family life.', '2025-11-10', 'SPAN2548'),
('Record yourself reading the provided Mandarin text aloud. Submit as an audio file.', '2025-09-22', 'CHIN1804'),
('Write a short paragraph in Mandarin describing technology. Use a minimum of 150 characters.', '2025-11-18', 'CHIN1804'),
('Translate the provided English passage into Mandarin Chinese.', '2025-12-04', 'CHIN1804'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-02-15', 'GEOL3356'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-03-05', 'GEOL3356'),
('Write a field report based on the volcanic activity site visit conducted in Week 3.', '2025-04-13', 'GEOL3356'),
('Research the geologic history of river deltas and write a two-page summary with cited sources.', '2025-04-21', 'GEOL3356'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-04-29', 'GEOL3356'),
('Research the geologic history of coastal erosion and write a two-page summary with cited sources.', '2025-11-21', 'GEOL2631'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-11-29', 'GEOL2631'),
('Write a field report based on the sedimentary basins site visit conducted in Week 3.', '2025-12-02', 'GEOL2631'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-12-10', 'GEOL2631'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-12-11', 'GEOL2631'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-10-13', 'GEOL3304'),
('Research the geologic history of volcanic activity and write a two-page summary with cited sources.', '2025-11-06', 'GEOL3304'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-11-29', 'GEOL3304'),
('Research the geologic history of volcanic activity and write a two-page summary with cited sources.', '2025-01-25', 'GEOL1169'),
('Write a field report based on the fault systems site visit conducted in Week 3.', '2025-02-21', 'GEOL1169'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-03-03', 'GEOL1169'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-04-17', 'GEOL1169'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-02-28', 'GEOL1048'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-03-02', 'GEOL1048'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-03-11', 'GEOL1048'),
('Write a field report based on the sedimentary basins site visit conducted in Week 6.', '2025-03-19', 'GEOL1048'),
('Research the geologic history of volcanic activity and write a two-page summary with cited sources.', '2025-04-10', 'GEOL1048'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-01-31', 'GEOL2436'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-03-17', 'GEOL2436'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-04-11', 'GEOL2436'),
('Research the geologic history of volcanic activity and write a two-page summary with cited sources.', '2025-04-15', 'GEOL2436'),
('Research the geologic history of river deltas and write a two-page summary with cited sources.', '2025-11-07', 'GEOL3045'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-11-21', 'GEOL3045'),
('Research and summarise the industrial applications of acid-base reactions. Cite at least five peer-reviewed sources.', '2025-03-16', 'CHEM3134'),
('Prepare a safety data summary for the reagents used in the polymer chemistry lab and assess associated hazards.', '2025-03-21', 'CHEM3134'),
('Record a two-minute spoken response in French on French culture. Submit as an audio file.', '2025-11-17', 'FRENCH2201'),
('Translate the provided passage from English to French, preserving tone and meaning.', '2025-11-30', 'FRENCH2201'),
('Complete the problem set on numerical methods. Show all working - answers without justification will not receive credit.', '2025-02-02', 'MATH1195'),
('Write a short essay comparing two approaches to discrete mathematics, with worked examples for each.', '2025-03-26', 'MATH1195'),
('Model the real-world scenario below using linear algebra techniques and interpret your results.', '2025-04-01', 'MATH1195'),
('Solve the attached linear algebra problem set and verify your answers using any computational tool.', '2025-04-11', 'MATH1195'),
('Prove the following number theory theorems using the methods covered in lectures.', '2025-04-26', 'MATH1195'),
('Solve the attached statistics problem set and verify your answers using any computational tool.', '2025-11-01', 'MATH1303'),
('Model the real-world scenario below using linear algebra techniques and interpret your results.', '2025-11-28', 'MATH1303'),
('Prove the following statistics theorems using the methods covered in lectures.', '2025-11-30', 'MATH1303'),
('Complete the problem set on discrete mathematics. Show all working - answers without justification will not receive credit.', '2025-12-10', 'MATH1303'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-02-26', 'GEOL2487'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-04-24', 'GEOL2487'),
('Prepare a lab report on the enzyme kinetics experiment from Week 6. Include your hypothesis, results, and discussion.', '2025-02-26', 'BIOL2509'),
('Design a controlled experiment to investigate the effect of an environmental variable on DNA replication.', '2025-03-05', 'BIOL2509'),
('Critically evaluate two research papers on the immune system and compare their methodologies and conclusions.', '2025-03-08', 'BIOL2509'),
('Perform a code review of the provided pull request. Submit written feedback addressing style, logic, and security.', '2025-10-07', 'SWEN1182'),
('Create a UML class diagram and sequence diagram for the fintech system described in the case study.', '2025-11-02', 'SWEN1182'),
('Write a test plan and execute test cases for the provided ride-sharing application. Submit a defect report.', '2025-12-06', 'SWEN1182'),
('Complete the reaction mechanism worksheet for spectroscopy. Clearly label all intermediates and arrow-pushing steps.', '2025-02-11', 'CHEM1668'),
('Write a formal lab report for the spectroscopy experiment conducted in Week 6. Follow the standard report format.', '2025-04-08', 'CHEM1668'),
('Research and summarise the industrial applications of acid-base reactions. Cite at least five peer-reviewed sources.', '2025-04-18', 'CHEM1668'),
('Solve the simple harmonic motion problem set. Include free-body diagrams where applicable.', '2025-04-18', 'PHYS2279'),
('Write a lab report for the simple harmonic motion experiment. Compare your results to the theoretical values and discuss errors.', '2025-04-20', 'PHYS2279'),
('Analyse the experimental data provided using projectile motion principles and present your conclusions.', '2025-04-27', 'PHYS2279'),
('Analyse the experimental data provided using electromagnetic induction principles and present your conclusions.', '2025-10-06', 'PHYS3064'),
('Research a real-world application of projectile motion and write a two-page technical summary.', '2025-10-16', 'PHYS3064'),
('Derive the equations of motion for the given thermodynamics system from first principles.', '2025-11-28', 'PHYS3064'),
('Write a lab report for the quantum mechanics experiment. Compare your results to the theoretical values and discuss errors.', '2025-12-05', 'PHYS3064'),
('Solve the quantum mechanics problem set. Include free-body diagrams where applicable.', '2025-12-05', 'PHYS3064'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-02-09', 'GEOL3129'),
('Research the geologic history of fault systems and write a two-page summary with cited sources.', '2025-02-26', 'GEOL3129'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-03-06', 'GEOL3129'),
('Translate the provided passage from English into Japanese.', '2025-03-28', 'JAPA3090'),
('Record a spoken response in Japanese describing technology. Submit as an audio file.', '2025-04-29', 'JAPA3090'),
('Write a field report based on the river deltas site visit conducted in Week 4.', '2025-01-31', 'GEOL1059'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-03-02', 'GEOL1059'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-04-04', 'GEOL1059'),
('Research the geologic history of volcanic activity and write a two-page summary with cited sources.', '2025-04-21', 'GEOL1059'),
('Write an essay discussing the role of DNA replication in human disease. Use at least six academic references.', '2025-03-08', 'BIOL2118'),
('Critically evaluate two research papers on mitosis and compare their methodologies and conclusions.', '2025-03-25', 'BIOL2118'),
('Design a controlled experiment to investigate the effect of an environmental variable on enzyme kinetics.', '2025-04-18', 'BIOL2118'),
('Prepare a lab report on the mitosis experiment from Week 5. Include your hypothesis, results, and discussion.', '2025-04-20', 'BIOL2118'),
('Complete the reaction mechanism worksheet for spectroscopy. Clearly label all intermediates and arrow-pushing steps.', '2025-03-06', 'CHEM1170'),
('Write a formal lab report for the polymer chemistry experiment conducted in Week 5. Follow the standard report format.', '2025-03-25', 'CHEM1170'),
('Research a real-world application of electromagnetic induction and write a two-page technical summary.', '2025-09-26', 'PHYS3431'),
('Write a lab report for the quantum mechanics experiment. Compare your results to the theoretical values and discuss errors.', '2025-10-08', 'PHYS3431'),
('Write a field report based on the fault systems site visit conducted in Week 6.', '2025-01-22', 'GEOL1019'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-03-11', 'GEOL1019'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-03-17', 'GEOL1019'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-03-21', 'GEOL1019'),
('Research the geologic history of river deltas and write a two-page summary with cited sources.', '2025-04-02', 'GEOL1019'),
('Prepare a written dialogue in Spanish between two characters discussing travel.', '2025-10-17', 'SPAN2173'),
('Write a 500-word essay in Spanish on the topic of the environment. Focus on grammatical accuracy and vocabulary range.', '2025-11-04', 'SPAN2173'),
('Translate the provided passage from English to Spanish, preserving tone and meaning.', '2025-11-14', 'SPAN2173'),
('Record a two-minute spoken response in Spanish describing family life. Submit as an audio file.', '2025-12-12', 'SPAN2173'),
('Research a real-world application of thermodynamics and write a two-page technical summary.', '2025-11-04', 'PHYS2548'),
('Write a lab report for the simple harmonic motion experiment. Compare your results to the theoretical values and discuss errors.', '2025-11-15', 'PHYS2548'),
('Analyse the experimental data provided using projectile motion principles and present your conclusions.', '2025-12-05', 'PHYS2548'),
('Produce a full requirements specification document for a e-learning system, including use cases and user stories.', '2025-03-22', 'SWEN2702'),
('Write a test plan and execute test cases for the provided e-learning application. Submit a defect report.', '2025-03-24', 'SWEN2702'),
('Plan a two-week agile sprint for the ride-sharing project. Include a backlog, sprint goal, and burndown chart.', '2025-04-05', 'SWEN2702'),
('Perform a code review of the provided pull request. Submit written feedback addressing style, logic, and security.', '2025-04-13', 'SWEN2702'),
('Create a UML class diagram and sequence diagram for the government system described in the case study.', '2025-04-28', 'SWEN2702'),
('Analyse the experimental data provided using simple harmonic motion principles and present your conclusions.', '2025-09-23', 'PHYS1824'),
('Write a lab report for the thermodynamics experiment. Compare your results to the theoretical values and discuss errors.', '2025-10-16', 'PHYS1824'),
('Derive the equations of motion for the given simple harmonic motion system from first principles.', '2025-10-24', 'PHYS1824'),
('Solve the simple harmonic motion problem set. Include free-body diagrams where applicable.', '2025-11-17', 'PHYS1824'),
('Research a real-world application of thermodynamics and write a two-page technical summary.', '2025-11-29', 'PHYS1824'),
('Prepare a written dialogue in Spanish between two characters discussing the environment.', '2025-03-10', 'SPAN1492'),
('Translate the provided passage from English to Spanish, preserving tone and meaning.', '2025-04-23', 'SPAN1492'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-10-02', 'CHEM2075'),
('Write a formal lab report for the organic synthesis experiment conducted in Week 8. Follow the standard report format.', '2025-11-30', 'CHEM2075'),
('Prepare a safety data summary for the reagents used in the thermochemistry lab and assess associated hazards.', '2025-12-12', 'CHEM2075'),
('Translate the provided passage from English into Japanese.', '2025-02-12', 'JAPA2859'),
('Record a spoken response in Japanese describing travel. Submit as an audio file.', '2025-03-06', 'JAPA2859'),
('Write a formal lab report for the spectroscopy experiment conducted in Week 7. Follow the standard report format.', '2025-01-31', 'CHEM2214'),
('Prepare a safety data summary for the reagents used in the electrochemistry lab and assess associated hazards.', '2025-04-07', 'CHEM2214'),
('Complete the reaction mechanism worksheet for organic synthesis. Clearly label all intermediates and arrow-pushing steps.', '2025-04-26', 'CHEM2214'),
('Critically evaluate two research papers on enzyme kinetics and compare their methodologies and conclusions.', '2025-09-20', 'BIOL1178'),
('Create an annotated diagram of the mitosis process, explaining each stage in your own words.', '2025-11-23', 'BIOL1178'),
('Research a real-world application of simple harmonic motion and write a two-page technical summary.', '2025-09-27', 'PHYS1866'),
('Solve the thermodynamics problem set. Include free-body diagrams where applicable.', '2025-11-06', 'PHYS1866'),
('Translate the provided English passage into Mandarin Chinese.', '2025-10-27', 'CHIN3356'),
('Write a dialogue in Mandarin between two people discussing family.', '2025-11-21', 'CHIN3356'),
('Write a short paragraph in Mandarin describing food. Use a minimum of 150 characters.', '2025-11-24', 'CHIN3356'),
('Record yourself reading the provided Mandarin text aloud. Submit as an audio file.', '2025-12-06', 'CHIN3356'),
('Answer the comprehension questions on the provided Mandarin reading passage.', '2025-12-06', 'CHIN3356'),
('Write a short essay comparing two approaches to numerical methods, with worked examples for each.', '2025-10-30', 'MATH2070'),
('Complete the problem set on statistics. Show all working - answers without justification will not receive credit.', '2025-11-15', 'MATH2070'),
('Perform a code review of the provided pull request. Submit written feedback addressing style, logic, and security.', '2025-11-08', 'SWEN3038'),
('Create a UML class diagram and sequence diagram for the fintech system described in the case study.', '2025-12-14', 'SWEN3038'),
('Create an annotated diagram of the mitosis process, explaining each stage in your own words.', '2025-02-01', 'BIOL1917'),
('Critically evaluate two research papers on mitosis and compare their methodologies and conclusions.', '2025-02-19', 'BIOL1917'),
('Write an essay discussing the role of mitosis in human disease. Use at least six academic references.', '2025-03-31', 'BIOL1917'),
('Design a controlled experiment to investigate the effect of an environmental variable on enzyme kinetics.', '2025-02-11', 'BIOL1878'),
('Create an annotated diagram of the the immune system process, explaining each stage in your own words.', '2025-03-09', 'BIOL1878'),
('Prepare a lab report on the the immune system experiment from Week 5. Include your hypothesis, results, and discussion.', '2025-03-28', 'BIOL1878'),
('Critically evaluate two research papers on DNA replication and compare their methodologies and conclusions.', '2025-04-10', 'BIOL1878'),
('Write an essay discussing the role of the immune system in human disease. Use at least six academic references.', '2025-04-22', 'BIOL1878'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-09-17', 'GEOL1823'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-11-09', 'GEOL1823'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-12-08', 'GEOL1823'),
('Research the geologic history of fault systems and write a two-page summary with cited sources.', '2025-12-10', 'GEOL1823'),
('Write a field report based on the fault systems site visit conducted in Week 6.', '2025-12-11', 'GEOL1823'),
('Answer the comprehension questions on the provided Mandarin reading passage.', '2025-10-12', 'CHIN2805'),
('Translate the provided English passage into Mandarin Chinese.', '2025-12-08', 'CHIN2805'),
('Prepare a lab report on the DNA replication experiment from Week 3. Include your hypothesis, results, and discussion.', '2025-02-17', 'BIOL1711'),
('Write an essay discussing the role of DNA replication in human disease. Use at least six academic references.', '2025-03-12', 'BIOL1711'),
('Design a controlled experiment to investigate the effect of an environmental variable on enzyme kinetics.', '2025-03-30', 'BIOL1711'),
('Create an annotated diagram of the enzyme kinetics process, explaining each stage in your own words.', '2025-04-09', 'BIOL1711'),
('Critically evaluate two research papers on the immune system and compare their methodologies and conclusions.', '2025-04-20', 'BIOL1711'),
('Critically evaluate two research papers on the immune system and compare their methodologies and conclusions.', '2025-02-16', 'BIOL2622'),
('Design a controlled experiment to investigate the effect of an environmental variable on mitosis.', '2025-03-23', 'BIOL2622'),
('Create an annotated diagram of the DNA replication process, explaining each stage in your own words.', '2025-04-08', 'BIOL2622'),
('Prepare a lab report on the cellular respiration experiment from Week 3. Include your hypothesis, results, and discussion.', '2025-04-12', 'BIOL2622'),
('Write an essay discussing the role of mitosis in human disease. Use at least six academic references.', '2025-04-14', 'BIOL2622'),
('Design a normalised relational schema for a healthcare system. Include an ER diagram and justification.', '2025-03-03', 'INFO1184'),
('Using the provided dataset, perform exploratory data analysis and present your findings in a dashboard.', '2025-03-11', 'INFO1184'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-02-07', 'GEOL2731'),
('Write a field report based on the fault systems site visit conducted in Week 3.', '2025-03-24', 'GEOL2731'),
('Research the geologic history of coastal erosion and write a two-page summary with cited sources.', '2025-03-27', 'GEOL2731'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-03-27', 'GEOL2731'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-04-03', 'GEOL2731'),
('Build a REST API with Go that performs full CRUD operations on a concurrency dataset.', '2025-10-02', 'COMP2464'),
('Analyse the time and space complexity of the provided compression algorithm. Write a report justifying your findings.', '2025-10-11', 'COMP2464'),
('Implement a linked list in C++. Your solution must handle edge cases and include unit tests.', '2025-12-07', 'COMP2464'),
('Create an annotated diagram of the DNA replication process, explaining each stage in your own words.', '2025-01-24', 'BIOL1904'),
('Critically evaluate two research papers on the immune system and compare their methodologies and conclusions.', '2025-03-01', 'BIOL1904'),
('Design a controlled experiment to investigate the effect of an environmental variable on mitosis.', '2025-03-26', 'BIOL1904'),
('Write an essay discussing the role of cellular respiration in human disease. Use at least six academic references.', '2025-04-03', 'BIOL1904'),
('Prepare a lab report on the DNA replication experiment from Week 5. Include your hypothesis, results, and discussion.', '2025-04-16', 'BIOL1904'),
('Create an annotated diagram of the cellular respiration process, explaining each stage in your own words.', '2025-10-04', 'BIOL1743'),
('Critically evaluate two research papers on the immune system and compare their methodologies and conclusions.', '2025-12-03', 'BIOL1743'),
('Design a controlled experiment to investigate the effect of an environmental variable on the immune system.', '2025-10-10', 'BIOL1453'),
('Create an annotated diagram of the cellular respiration process, explaining each stage in your own words.', '2025-11-07', 'BIOL1453'),
('Prepare a lab report on the mitosis experiment from Week 2. Include your hypothesis, results, and discussion.', '2025-11-10', 'BIOL1453'),
('Critically evaluate two research papers on the immune system and compare their methodologies and conclusions.', '2025-11-15', 'BIOL1453'),
('Write an essay discussing the role of enzyme kinetics in human disease. Use at least six academic references.', '2025-12-12', 'BIOL1453'),
('Analyse the experimental data provided using thermodynamics principles and present your conclusions.', '2025-02-16', 'PHYS2914'),
('Research a real-world application of thermodynamics and write a two-page technical summary.', '2025-02-28', 'PHYS2914'),
('Write a lab report for the wave optics experiment. Compare your results to the theoretical values and discuss errors.', '2025-03-18', 'PHYS2914'),
('Solve the quantum mechanics problem set. Include free-body diagrams where applicable.', '2025-03-25', 'PHYS2914'),
('Derive the equations of motion for the given wave optics system from first principles.', '2025-03-30', 'PHYS2914'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-09-21', 'GEOL1700'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-10-30', 'GEOL1700'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-11-02', 'GEOL1700'),
('Research and summarise the industrial applications of polymer chemistry. Cite at least five peer-reviewed sources.', '2025-02-26', 'CHEM3125'),
('Write a formal lab report for the polymer chemistry experiment conducted in Week 5. Follow the standard report format.', '2025-03-26', 'CHEM3125'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-04-03', 'CHEM3125'),
('Complete the reaction mechanism worksheet for electrochemistry. Clearly label all intermediates and arrow-pushing steps.', '2025-04-05', 'CHEM3125'),
('Complete the problem set on linear algebra. Show all working - answers without justification will not receive credit.', '2025-01-17', 'MATH1139'),
('Solve the attached number theory problem set and verify your answers using any computational tool.', '2025-02-07', 'MATH1139'),
('Model the real-world scenario below using statistics techniques and interpret your results.', '2025-03-21', 'MATH1139'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-03-27', 'GEOL2467'),
('Research the geologic history of river deltas and write a two-page summary with cited sources.', '2025-04-07', 'GEOL2467'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-04-07', 'GEOL2467'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-04-19', 'GEOL2467'),
('Write a field report based on the sedimentary basins site visit conducted in Week 6.', '2025-04-20', 'GEOL2467'),
('Complete the reaction mechanism worksheet for spectroscopy. Clearly label all intermediates and arrow-pushing steps.', '2025-10-31', 'CHEM2208'),
('Write a formal lab report for the electrochemistry experiment conducted in Week 5. Follow the standard report format.', '2025-12-09', 'CHEM2208'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-12-10', 'CHEM2208'),
('Solve the quantum mechanics problem set. Include free-body diagrams where applicable.', '2025-03-05', 'PHYS1944'),
('Research a real-world application of quantum mechanics and write a two-page technical summary.', '2025-03-25', 'PHYS1944'),
('Analyse the experimental data provided using simple harmonic motion principles and present your conclusions.', '2025-04-18', 'PHYS1944'),
('Derive the equations of motion for the given electromagnetic induction system from first principles.', '2025-04-25', 'PHYS1944'),
('Write a lab report for the projectile motion experiment. Compare your results to the theoretical values and discuss errors.', '2025-04-26', 'PHYS1944'),
('Design a controlled experiment to investigate the effect of an environmental variable on DNA replication.', '2025-02-08', 'BIOL3197'),
('Create an annotated diagram of the natural selection process, explaining each stage in your own words.', '2025-03-26', 'BIOL3197'),
('Prepare a lab report on the mitosis experiment from Week 2. Include your hypothesis, results, and discussion.', '2025-03-28', 'BIOL3197'),
('Critically evaluate two research papers on cellular respiration and compare their methodologies and conclusions.', '2025-04-01', 'BIOL3197'),
('Write an essay discussing the role of cellular respiration in human disease. Use at least six academic references.', '2025-04-15', 'BIOL3197'),
('Prepare a lab report on the the immune system experiment from Week 4. Include your hypothesis, results, and discussion.', '2025-10-04', 'BIOL1635'),
('Write an essay discussing the role of cellular respiration in human disease. Use at least six academic references.', '2025-10-21', 'BIOL1635'),
('Critically evaluate two research papers on mitosis and compare their methodologies and conclusions.', '2025-10-25', 'BIOL1635'),
('Design a controlled experiment to investigate the effect of an environmental variable on mitosis.', '2025-11-08', 'BIOL1635'),
('Create an annotated diagram of the natural selection process, explaining each stage in your own words.', '2025-11-28', 'BIOL1635'),
('Model the real-world scenario below using discrete mathematics techniques and interpret your results.', '2025-04-09', 'MATH1270'),
('Prove the following numerical methods theorems using the methods covered in lectures.', '2025-04-16', 'MATH1270'),
('Critically evaluate two research papers on DNA replication and compare their methodologies and conclusions.', '2025-09-20', 'BIOL2801'),
('Design a controlled experiment to investigate the effect of an environmental variable on mitosis.', '2025-10-21', 'BIOL2801'),
('Create an annotated diagram of the enzyme kinetics process, explaining each stage in your own words.', '2025-10-31', 'BIOL2801'),
('Prepare a lab report on the enzyme kinetics experiment from Week 3. Include your hypothesis, results, and discussion.', '2025-11-14', 'BIOL2801'),
('Write an essay discussing the role of mitosis in human disease. Use at least six academic references.', '2025-12-09', 'BIOL2801'),
('Design a controlled experiment to investigate the effect of an environmental variable on DNA replication.', '2025-02-22', 'BIOL2705'),
('Prepare a lab report on the DNA replication experiment from Week 4. Include your hypothesis, results, and discussion.', '2025-03-25', 'BIOL2705'),
('Research a real-world application of wave optics and write a two-page technical summary.', '2025-10-06', 'PHYS1590'),
('Solve the quantum mechanics problem set. Include free-body diagrams where applicable.', '2025-10-19', 'PHYS1590'),
('Derive the equations of motion for the given simple harmonic motion system from first principles.', '2025-11-18', 'PHYS1590'),
('Write a lab report for the quantum mechanics experiment. Compare your results to the theoretical values and discuss errors.', '2025-10-19', 'PHYS2201'),
('Solve the electromagnetic induction problem set. Include free-body diagrams where applicable.', '2025-11-19', 'PHYS2201'),
('Write a lab report for the electromagnetic induction experiment. Compare your results to the theoretical values and discuss errors.', '2025-03-10', 'PHYS2314'),
('Derive the equations of motion for the given quantum mechanics system from first principles.', '2025-03-12', 'PHYS2314'),
('Analyse the experimental data provided using projectile motion principles and present your conclusions.', '2025-04-16', 'PHYS2314'),
('Solve the quantum mechanics problem set. Include free-body diagrams where applicable.', '2025-04-18', 'PHYS2314'),
('Research a real-world application of simple harmonic motion and write a two-page technical summary.', '2025-04-28', 'PHYS2314'),
('Write a field report based on the river deltas site visit conducted in Week 4.', '2025-03-21', 'GEOL3310'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-04-24', 'GEOL3310'),
('Write a lab report for the quantum mechanics experiment. Compare your results to the theoretical values and discuss errors.', '2025-02-05', 'PHYS2525'),
('Research a real-world application of electromagnetic induction and write a two-page technical summary.', '2025-02-14', 'PHYS2525'),
('Solve the wave optics problem set. Include free-body diagrams where applicable.', '2025-03-07', 'PHYS2525'),
('Derive the equations of motion for the given quantum mechanics system from first principles.', '2025-04-25', 'PHYS2525'),
('Prove the following numerical methods theorems using the methods covered in lectures.', '2025-03-03', 'MATH3379'),
('Write a short essay comparing two approaches to number theory, with worked examples for each.', '2025-04-02', 'MATH3379'),
('Model the real-world scenario below using calculus techniques and interpret your results.', '2025-04-16', 'MATH3379'),
('Translate the provided passage from English to French, preserving tone and meaning.', '2025-10-05', 'FRENCH1240'),
('Write a formal letter in French responding to the scenario described in the case study.', '2025-10-24', 'FRENCH1240'),
('Record a two-minute spoken response in French on French culture. Submit as an audio file.', '2025-11-10', 'FRENCH1240'),
('Analyse the grammatical structures in the provided French text and annotate them.', '2025-11-17', 'FRENCH1240'),
('Prepare a lab report on the enzyme kinetics experiment from Week 4. Include your hypothesis, results, and discussion.', '2025-03-19', 'BIOL2516'),
('Create an annotated diagram of the natural selection process, explaining each stage in your own words.', '2025-04-20', 'BIOL2516'),
('Model the real-world scenario below using number theory techniques and interpret your results.', '2025-03-09', 'MATH2772'),
('Solve the attached linear algebra problem set and verify your answers using any computational tool.', '2025-03-16', 'MATH2772'),
('Complete the problem set on probability. Show all working - answers without justification will not receive credit.', '2025-04-25', 'MATH2772'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-10-21', 'GEOL1865'),
('Research the geologic history of fault systems and write a two-page summary with cited sources.', '2025-11-12', 'GEOL1865'),
('Write a field report based on the sedimentary basins site visit conducted in Week 4.', '2025-11-19', 'GEOL1865'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-12-07', 'GEOL1865'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-12-11', 'GEOL1865'),
('Complete the reaction mechanism worksheet for acid-base reactions. Clearly label all intermediates and arrow-pushing steps.', '2025-11-07', 'CHEM1065'),
('Research and summarise the industrial applications of electrochemistry. Cite at least five peer-reviewed sources.', '2025-11-20', 'CHEM1065'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-09-13', 'GEOL3344'),
('Research the geologic history of river deltas and write a two-page summary with cited sources.', '2025-10-27', 'GEOL3344'),
('Prove the following discrete mathematics theorems using the methods covered in lectures.', '2025-02-14', 'MATH2558'),
('Solve the attached numerical methods problem set and verify your answers using any computational tool.', '2025-03-30', 'MATH2558'),
('Model the real-world scenario below using linear algebra techniques and interpret your results.', '2025-04-11', 'MATH2558'),
('Write a lab report for the electromagnetic induction experiment. Compare your results to the theoretical values and discuss errors.', '2025-01-23', 'PHYS1759'),
('Analyse the experimental data provided using electromagnetic induction principles and present your conclusions.', '2025-02-12', 'PHYS1759'),
('Solve the projectile motion problem set. Include free-body diagrams where applicable.', '2025-02-26', 'PHYS1759'),
('Research a real-world application of quantum mechanics and write a two-page technical summary.', '2025-03-24', 'PHYS1759'),
('Derive the equations of motion for the given simple harmonic motion system from first principles.', '2025-04-14', 'PHYS1759'),
('Perform a code review of the provided pull request. Submit written feedback addressing style, logic, and security.', '2025-09-29', 'SWEN2288'),
('Create a UML class diagram and sequence diagram for the retail system described in the case study.', '2025-10-25', 'SWEN2288'),
('Produce a full requirements specification document for a ride-sharing system, including use cases and user stories.', '2025-10-31', 'SWEN2288'),
('Plan a two-week agile sprint for the ride-sharing project. Include a backlog, sprint goal, and burndown chart.', '2025-12-11', 'SWEN2288'),
('Design and build a web application using Python. Submit source code and a README.', '2025-10-07', 'COMP1016'),
('Refactor the given legacy codebase to follow SOLID principles. Document every change made.', '2025-11-24', 'COMP1016'),
('Build a REST API with JavaScript that performs full CRUD operations on a networking dataset.', '2025-11-26', 'COMP1016'),
('Implement a graph in C++. Your solution must handle edge cases and include unit tests.', '2025-12-05', 'COMP1016'),
('Write an essay discussing the role of mitosis in human disease. Use at least six academic references.', '2025-02-22', 'BIOL2374'),
('Critically evaluate two research papers on DNA replication and compare their methodologies and conclusions.', '2025-02-23', 'BIOL2374'),
('Design a controlled experiment to investigate the effect of an environmental variable on natural selection.', '2025-02-27', 'BIOL2374'),
('Prepare a lab report on the DNA replication experiment from Week 6. Include your hypothesis, results, and discussion.', '2025-03-25', 'BIOL2374'),
('Create an annotated diagram of the mitosis process, explaining each stage in your own words.', '2025-04-13', 'BIOL2374'),
('Complete the reaction mechanism worksheet for organic synthesis. Clearly label all intermediates and arrow-pushing steps.', '2025-04-01', 'CHEM1880'),
('Write a formal lab report for the acid-base reactions experiment conducted in Week 4. Follow the standard report format.', '2025-04-26', 'CHEM1880'),
('Solve the attached calculus problem set and verify your answers using any computational tool.', '2025-04-15', 'MATH2073'),
('Complete the problem set on calculus. Show all working - answers without justification will not receive credit.', '2025-04-22', 'MATH2073'),
('Design a controlled experiment to investigate the effect of an environmental variable on mitosis.', '2025-03-09', 'BIOL2635'),
('Prepare a lab report on the cellular respiration experiment from Week 6. Include your hypothesis, results, and discussion.', '2025-03-11', 'BIOL2635'),
('Write an essay discussing the role of DNA replication in human disease. Use at least six academic references.', '2025-03-15', 'BIOL2635'),
('Create an annotated diagram of the cellular respiration process, explaining each stage in your own words.', '2025-03-27', 'BIOL2635'),
('Critically evaluate two research papers on mitosis and compare their methodologies and conclusions.', '2025-03-29', 'BIOL2635'),
('Refactor the given legacy codebase to follow SOLID principles. Document every change made.', '2025-10-27', 'COMP1423'),
('Implement a hash map in Go. Your solution must handle edge cases and include unit tests.', '2025-11-04', 'COMP1423'),
('Prepare a safety data summary for the reagents used in the acid-base reactions lab and assess associated hazards.', '2025-10-19', 'CHEM3351'),
('Complete the reaction mechanism worksheet for polymer chemistry. Clearly label all intermediates and arrow-pushing steps.', '2025-10-23', 'CHEM3351'),
('Write a formal lab report for the thermochemistry experiment conducted in Week 5. Follow the standard report format.', '2025-11-12', 'CHEM3351'),
('Research and summarise the industrial applications of electrochemistry. Cite at least five peer-reviewed sources.', '2025-11-22', 'CHEM3351'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-12-02', 'CHEM3351'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-02-07', 'GEOL1938'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-02-20', 'GEOL1938'),
('Research the geologic history of volcanic activity and write a two-page summary with cited sources.', '2025-03-12', 'GEOL1938'),
('Solve the attached discrete mathematics problem set and verify your answers using any computational tool.', '2025-09-07', 'MATH1466'),
('Model the real-world scenario below using numerical methods techniques and interpret your results.', '2025-10-10', 'MATH1466'),
('Complete the problem set on discrete mathematics. Show all working - answers without justification will not receive credit.', '2025-10-25', 'MATH1466'),
('Prove the following statistics theorems using the methods covered in lectures.', '2025-11-13', 'MATH1466'),
('Write a short essay comparing two approaches to linear algebra, with worked examples for each.', '2025-11-18', 'MATH1466'),
('Complete the problem set on probability. Show all working - answers without justification will not receive credit.', '2025-03-17', 'MATH1340'),
('Model the real-world scenario below using linear algebra techniques and interpret your results.', '2025-04-20', 'MATH1340'),
('Derive the equations of motion for the given projectile motion system from first principles.', '2025-11-12', 'PHYS2506'),
('Write a lab report for the simple harmonic motion experiment. Compare your results to the theoretical values and discuss errors.', '2025-12-11', 'PHYS2506'),
('Model the real-world scenario below using linear algebra techniques and interpret your results.', '2025-03-08', 'MATH2086'),
('Solve the attached calculus problem set and verify your answers using any computational tool.', '2025-03-14', 'MATH2086'),
('Prove the following calculus theorems using the methods covered in lectures.', '2025-03-24', 'MATH2086'),
('Complete the problem set on linear algebra. Show all working - answers without justification will not receive credit.', '2025-03-23', 'MATH1337'),
('Solve the attached discrete mathematics problem set and verify your answers using any computational tool.', '2025-04-11', 'MATH1337'),
('Model the real-world scenario below using numerical methods techniques and interpret your results.', '2025-04-16', 'MATH1337'),
('Prove the following statistics theorems using the methods covered in lectures.', '2025-04-20', 'MATH1337'),
('Analyse the grammatical structures used in the provided Spanish text and annotate them with explanations.', '2025-01-20', 'SPAN3483'),
('Translate the provided passage from English to Spanish, preserving tone and meaning.', '2025-02-10', 'SPAN3483'),
('Write a 500-word essay in Spanish on the topic of family life. Focus on grammatical accuracy and vocabulary range.', '2025-02-21', 'SPAN3483'),
('Prepare a written dialogue in Spanish between two characters discussing family life.', '2025-03-04', 'SPAN3483'),
('Write a short paragraph in Mandarin describing technology. Use a minimum of 150 characters.', '2025-12-04', 'CHIN1064'),
('Translate the provided English passage into Mandarin Chinese.', '2025-12-05', 'CHIN1064'),
('Prepare a lab report on the natural selection experiment from Week 6. Include your hypothesis, results, and discussion.', '2025-11-02', 'BIOL1910'),
('Design a controlled experiment to investigate the effect of an environmental variable on natural selection.', '2025-11-26', 'BIOL1910'),
('Create an annotated diagram of the enzyme kinetics process, explaining each stage in your own words.', '2025-12-12', 'BIOL1910'),
('Design a controlled experiment to investigate the effect of an environmental variable on natural selection.', '2025-11-14', 'BIOL2058'),
('Critically evaluate two research papers on DNA replication and compare their methodologies and conclusions.', '2025-12-10', 'BIOL2058'),
('Write an essay discussing the role of mitosis in human disease. Use at least six academic references.', '2025-12-10', 'BIOL2058'),
('Analyse the grammatical structures in the provided French text and annotate them.', '2025-04-09', 'FRENCH2325'),
('Translate the provided passage from English to French, preserving tone and meaning.', '2025-04-20', 'FRENCH2325'),
('Write a short paragraph in Mandarin describing technology. Use a minimum of 150 characters.', '2025-03-23', 'CHIN3274'),
('Record yourself reading the provided Mandarin text aloud. Submit as an audio file.', '2025-03-31', 'CHIN3274'),
('Prepare a safety data summary for the reagents used in the electrochemistry lab and assess associated hazards.', '2025-02-07', 'CHEM2917'),
('Write a formal lab report for the organic synthesis experiment conducted in Week 6. Follow the standard report format.', '2025-03-30', 'CHEM2917'),
('Analyse the experimental data provided using electromagnetic induction principles and present your conclusions.', '2025-10-14', 'PHYS1325'),
('Solve the thermodynamics problem set. Include free-body diagrams where applicable.', '2025-12-11', 'PHYS1325'),
('Write a formal lab report for the electrochemistry experiment conducted in Week 5. Follow the standard report format.', '2025-10-11', 'CHEM2468'),
('Complete the reaction mechanism worksheet for acid-base reactions. Clearly label all intermediates and arrow-pushing steps.', '2025-10-23', 'CHEM2468'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-12-10', 'CHEM2468'),
('Research and summarise the industrial applications of organic synthesis. Cite at least five peer-reviewed sources.', '2025-12-11', 'CHEM2468'),
('Design a controlled experiment to investigate the effect of an environmental variable on mitosis.', '2025-02-17', 'BIOL1768'),
('Critically evaluate two research papers on mitosis and compare their methodologies and conclusions.', '2025-03-06', 'BIOL1768'),
('Create an annotated diagram of the cellular respiration process, explaining each stage in your own words.', '2025-03-22', 'BIOL1768'),
('Prepare a lab report on the cellular respiration experiment from Week 4. Include your hypothesis, results, and discussion.', '2025-03-25', 'BIOL1768'),
('Write an essay discussing the role of cellular respiration in human disease. Use at least six academic references.', '2025-04-26', 'BIOL1768'),
('Write a short essay comparing two approaches to linear algebra, with worked examples for each.', '2025-02-27', 'MATH3199'),
('Solve the attached probability problem set and verify your answers using any computational tool.', '2025-03-27', 'MATH3199'),
('Model the real-world scenario below using discrete mathematics techniques and interpret your results.', '2025-04-07', 'MATH3199'),
('Prove the following calculus theorems using the methods covered in lectures.', '2025-04-19', 'MATH3199'),
('Complete the problem set on numerical methods. Show all working - answers without justification will not receive credit.', '2025-04-23', 'MATH3199'),
('Write a lab report for the quantum mechanics experiment. Compare your results to the theoretical values and discuss errors.', '2025-02-11', 'PHYS1151'),
('Solve the projectile motion problem set. Include free-body diagrams where applicable.', '2025-03-20', 'PHYS1151'),
('Research a real-world application of thermodynamics and write a two-page technical summary.', '2025-04-12', 'PHYS1151'),
('Analyse the experimental data provided using electromagnetic induction principles and present your conclusions.', '2025-04-15', 'PHYS1151'),
('Derive the equations of motion for the given quantum mechanics system from first principles.', '2025-04-29', 'PHYS1151'),
('Create a UML class diagram and sequence diagram for the fintech system described in the case study.', '2025-03-25', 'SWEN2904'),
('Write a test plan and execute test cases for the provided mobile banking application. Submit a defect report.', '2025-04-06', 'SWEN2904'),
('Complete the problem set on numerical methods. Show all working - answers without justification will not receive credit.', '2025-04-17', 'MATH1832'),
('Model the real-world scenario below using probability techniques and interpret your results.', '2025-04-28', 'MATH1832'),
('Analyse the grammatical structures used in the provided Spanish text and annotate them with explanations.', '2025-03-01', 'SPAN1689'),
('Prepare a written dialogue in Spanish between two characters discussing culture.', '2025-03-10', 'SPAN1689'),
('Record a two-minute spoken response in Spanish describing travel. Submit as an audio file.', '2025-04-02', 'SPAN1689'),
('Write a 500-word essay in Spanish on the topic of culture. Focus on grammatical accuracy and vocabulary range.', '2025-04-15', 'SPAN1689'),
('Write a short essay comparing two approaches to number theory, with worked examples for each.', '2025-02-06', 'MATH3380'),
('Solve the attached discrete mathematics problem set and verify your answers using any computational tool.', '2025-04-14', 'MATH3380'),
('Complete the problem set on linear algebra. Show all working - answers without justification will not receive credit.', '2025-04-17', 'MATH3380'),
('Model the real-world scenario below using number theory techniques and interpret your results.', '2025-04-21', 'MATH3380'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-10-12', 'CHEM2110'),
('Prepare a safety data summary for the reagents used in the electrochemistry lab and assess associated hazards.', '2025-11-02', 'CHEM2110'),
('Write a formal lab report for the organic synthesis experiment conducted in Week 4. Follow the standard report format.', '2025-11-10', 'CHEM2110'),
('Complete the reaction mechanism worksheet for thermochemistry. Clearly label all intermediates and arrow-pushing steps.', '2025-11-23', 'CHEM2110'),
('Research and summarise the industrial applications of electrochemistry. Cite at least five peer-reviewed sources.', '2025-12-03', 'CHEM2110'),
('Write a 500-word essay in French on the topic of technology. Pay attention to agreement and verb conjugation.', '2025-02-05', 'FRENCH2790'),
('Record a two-minute spoken response in French on daily routines. Submit as an audio file.', '2025-02-18', 'FRENCH2790');

INSERT INTO Assignment (a_desc, a_due_date, c_code) VALUES
('Translate the provided passage from English to French, preserving tone and meaning.', '2025-02-20', 'FRENCH2790'),
('Analyse the grammatical structures in the provided French text and annotate them.', '2025-04-27', 'FRENCH2790'),
('Design a normalised relational schema for a education system. Include an ER diagram and justification.', '2025-01-29', 'INFO1252'),
('Write a report analysing the information security risks facing a healthcare organisation.', '2025-02-01', 'INFO1252'),
('Evaluate two competing data warehouse frameworks and recommend one for a given business scenario.', '2025-02-08', 'INFO1252'),
('Develop a business intelligence report for a logistics company using the tools discussed in class.', '2025-04-25', 'INFO1252'),
('Using the provided dataset, perform exploratory data analysis and present your findings in a dashboard.', '2025-04-27', 'INFO1252'),
('Prepare a lab report on the mitosis experiment from Week 5. Include your hypothesis, results, and discussion.', '2025-10-06', 'BIOL2115'),
('Create an annotated diagram of the the immune system process, explaining each stage in your own words.', '2025-10-19', 'BIOL2115'),
('Design a controlled experiment to investigate the effect of an environmental variable on mitosis.', '2025-11-16', 'BIOL2115'),
('Critically evaluate two research papers on the immune system and compare their methodologies and conclusions.', '2025-12-13', 'BIOL2115'),
('Write an essay discussing the role of the immune system in human disease. Use at least six academic references.', '2025-12-13', 'BIOL2115'),
('Research and summarise the industrial applications of organic synthesis. Cite at least five peer-reviewed sources.', '2025-04-06', 'CHEM2896'),
('Complete the reaction mechanism worksheet for acid-base reactions. Clearly label all intermediates and arrow-pushing steps.', '2025-04-13', 'CHEM2896'),
('Solve the thermodynamics problem set. Include free-body diagrams where applicable.', '2025-02-16', 'PHYS3492'),
('Derive the equations of motion for the given quantum mechanics system from first principles.', '2025-03-08', 'PHYS3492'),
('Research a real-world application of wave optics and write a two-page technical summary.', '2025-03-11', 'PHYS3492'),
('Analyse the experimental data provided using quantum mechanics principles and present your conclusions.', '2025-03-28', 'PHYS3492'),
('Solve the attached numerical methods problem set and verify your answers using any computational tool.', '2025-10-15', 'MATH2061'),
('Prove the following statistics theorems using the methods covered in lectures.', '2025-10-29', 'MATH2061'),
('Model the real-world scenario below using number theory techniques and interpret your results.', '2025-11-05', 'MATH2061'),
('Write a short essay comparing two approaches to calculus, with worked examples for each.', '2025-12-06', 'MATH2061'),
('Complete the problem set on discrete mathematics. Show all working - answers without justification will not receive credit.', '2025-12-11', 'MATH2061'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-09-11', 'GEOL2066'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-11-16', 'GEOL2066'),
('Research the geologic history of coastal erosion and write a two-page summary with cited sources.', '2025-11-25', 'GEOL2066'),
('Complete the problem set on calculus. Show all working - answers without justification will not receive credit.', '2025-10-08', 'MATH1079'),
('Write a short essay comparing two approaches to linear algebra, with worked examples for each.', '2025-10-15', 'MATH1079'),
('Model the real-world scenario below using discrete mathematics techniques and interpret your results.', '2025-10-28', 'MATH1079'),
('Solve the attached calculus problem set and verify your answers using any computational tool.', '2025-11-29', 'MATH1079'),
('Prove the following numerical methods theorems using the methods covered in lectures.', '2025-12-01', 'MATH1079'),
('Analyse the experimental data provided using quantum mechanics principles and present your conclusions.', '2025-09-26', 'PHYS1028'),
('Solve the simple harmonic motion problem set. Include free-body diagrams where applicable.', '2025-10-29', 'PHYS1028'),
('Derive the equations of motion for the given projectile motion system from first principles.', '2025-11-18', 'PHYS1028'),
('Research a real-world application of wave optics and write a two-page technical summary.', '2025-11-24', 'PHYS1028'),
('Write a lab report for the quantum mechanics experiment. Compare your results to the theoretical values and discuss errors.', '2025-12-01', 'PHYS1028'),
('Translate the provided passage from English to French, preserving tone and meaning.', '2025-03-19', 'FRENCH2015'),
('Record a two-minute spoken response in French on travel. Submit as an audio file.', '2025-03-23', 'FRENCH2015'),
('Prepare a lab report on the the immune system experiment from Week 6. Include your hypothesis, results, and discussion.', '2025-04-08', 'BIOL3168'),
('Critically evaluate two research papers on the immune system and compare their methodologies and conclusions.', '2025-04-23', 'BIOL3168'),
('Create an annotated diagram of the cellular respiration process, explaining each stage in your own words.', '2025-04-26', 'BIOL3168'),
('Write a short paragraph in Mandarin describing daily life. Use a minimum of 150 characters.', '2025-11-11', 'CHIN3152'),
('Translate the provided English passage into Mandarin Chinese.', '2025-11-11', 'CHIN3152'),
('Record yourself reading the provided Mandarin text aloud. Submit as an audio file.', '2025-11-12', 'CHIN3152'),
('Answer the comprehension questions on the provided Mandarin reading passage.', '2025-12-02', 'CHIN3152'),
('Write a dialogue in Mandarin between two people discussing food.', '2025-12-08', 'CHIN3152'),
('Design and build a desktop application using Java. Submit source code and a README.', '2025-02-24', 'COMP2199'),
('Implement a hash map in C++. Your solution must handle edge cases and include unit tests.', '2025-03-30', 'COMP2199'),
('Build a REST API with Java that performs full CRUD operations on a security dataset.', '2025-04-20', 'COMP2199'),
('Write a field report based on the river deltas site visit conducted in Week 4.', '2025-02-28', 'GEOL2634'),
('Research the geologic history of fault systems and write a two-page summary with cited sources.', '2025-03-15', 'GEOL2634'),
('Solve the attached calculus problem set and verify your answers using any computational tool.', '2025-02-22', 'MATH2132'),
('Prove the following number theory theorems using the methods covered in lectures.', '2025-03-31', 'MATH2132'),
('Model the real-world scenario below using number theory techniques and interpret your results.', '2025-04-01', 'MATH2132'),
('Translate the provided passage from English to Spanish, preserving tone and meaning.', '2025-09-15', 'SPAN2816'),
('Record a two-minute spoken response in Spanish describing technology. Submit as an audio file.', '2025-11-14', 'SPAN2816'),
('Prepare a written dialogue in Spanish between two characters discussing the environment.', '2025-12-09', 'SPAN2816'),
('Analyse the grammatical structures used in the provided Spanish text and annotate them with explanations.', '2025-12-10', 'SPAN2816'),
('Research and summarise the industrial applications of spectroscopy. Cite at least five peer-reviewed sources.', '2025-12-02', 'CHEM1364'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-12-05', 'CHEM1364'),
('Analyse the experimental data provided using simple harmonic motion principles and present your conclusions.', '2025-03-01', 'PHYS2242'),
('Research a real-world application of electromagnetic induction and write a two-page technical summary.', '2025-03-04', 'PHYS2242'),
('Solve the projectile motion problem set. Include free-body diagrams where applicable.', '2025-03-23', 'PHYS2242'),
('Write a lab report for the simple harmonic motion experiment. Compare your results to the theoretical values and discuss errors.', '2025-04-07', 'PHYS2242'),
('Derive the equations of motion for the given electromagnetic induction system from first principles.', '2025-04-09', 'PHYS2242'),
('Complete the problem set on discrete mathematics. Show all working - answers without justification will not receive credit.', '2025-01-25', 'MATH1683'),
('Prove the following number theory theorems using the methods covered in lectures.', '2025-03-17', 'MATH1683'),
('Solve the attached discrete mathematics problem set and verify your answers using any computational tool.', '2025-04-03', 'MATH1683'),
('Model the real-world scenario below using probability techniques and interpret your results.', '2025-04-08', 'MATH1683'),
('Write a short essay comparing two approaches to number theory, with worked examples for each.', '2025-04-25', 'MATH1683'),
('Using the provided dataset, perform exploratory data analysis and present your findings in a dashboard.', '2025-04-14', 'INFO2402'),
('Design a normalised relational schema for a healthcare system. Include an ER diagram and justification.', '2025-04-18', 'INFO2402'),
('Model the real-world scenario below using probability techniques and interpret your results.', '2025-11-11', 'MATH1125'),
('Complete the problem set on statistics. Show all working - answers without justification will not receive credit.', '2025-12-06', 'MATH1125'),
('Solve the attached numerical methods problem set and verify your answers using any computational tool.', '2025-12-09', 'MATH1125'),
('Complete the reaction mechanism worksheet for polymer chemistry. Clearly label all intermediates and arrow-pushing steps.', '2025-11-03', 'CHEM1649'),
('Research and summarise the industrial applications of acid-base reactions. Cite at least five peer-reviewed sources.', '2025-12-05', 'CHEM1649'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-12-10', 'CHEM1649'),
('Prepare a safety data summary for the reagents used in the electrochemistry lab and assess associated hazards.', '2025-12-12', 'CHEM1649'),
('Analyse the experimental data provided using projectile motion principles and present your conclusions.', '2025-11-29', 'PHYS3499'),
('Derive the equations of motion for the given thermodynamics system from first principles.', '2025-12-01', 'PHYS3499'),
('Write a lab report for the simple harmonic motion experiment. Compare your results to the theoretical values and discuss errors.', '2025-12-06', 'PHYS3499'),
('Research a real-world application of thermodynamics and write a two-page technical summary.', '2025-10-08', 'PHYS1864'),
('Write a lab report for the wave optics experiment. Compare your results to the theoretical values and discuss errors.', '2025-11-12', 'PHYS1864'),
('Write a short essay comparing two approaches to probability, with worked examples for each.', '2025-01-26', 'MATH2082'),
('Prove the following linear algebra theorems using the methods covered in lectures.', '2025-04-12', 'MATH2082'),
('Solve the attached probability problem set and verify your answers using any computational tool.', '2025-04-12', 'MATH2082'),
('Complete the problem set on calculus. Show all working - answers without justification will not receive credit.', '2025-04-26', 'MATH2082'),
('Write a field report based on the river deltas site visit conducted in Week 6.', '2025-09-23', 'GEOL2503'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-10-09', 'GEOL2503'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-11-05', 'GEOL2503'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-12-09', 'GEOL2503'),
('Research the geologic history of sedimentary basins and write a two-page summary with cited sources.', '2025-12-14', 'GEOL2503'),
('Critically evaluate two research papers on the immune system and compare their methodologies and conclusions.', '2025-02-08', 'BIOL1579'),
('Design a controlled experiment to investigate the effect of an environmental variable on cellular respiration.', '2025-04-02', 'BIOL1579'),
('Write an essay discussing the role of natural selection in human disease. Use at least six academic references.', '2025-04-23', 'BIOL1579'),
('Derive the equations of motion for the given projectile motion system from first principles.', '2025-02-09', 'PHYS1676'),
('Write a lab report for the projectile motion experiment. Compare your results to the theoretical values and discuss errors.', '2025-03-08', 'PHYS1676'),
('Design a controlled experiment to investigate the effect of an environmental variable on cellular respiration.', '2025-03-21', 'BIOL1333'),
('Prepare a lab report on the the immune system experiment from Week 4. Include your hypothesis, results, and discussion.', '2025-04-15', 'BIOL1333'),
('Create an annotated diagram of the DNA replication process, explaining each stage in your own words.', '2025-04-24', 'BIOL1333'),
('Critically evaluate two research papers on natural selection and compare their methodologies and conclusions.', '2025-04-24', 'BIOL1333'),
('Research and summarise the industrial applications of polymer chemistry. Cite at least five peer-reviewed sources.', '2025-10-18', 'CHEM1234'),
('Complete the reaction mechanism worksheet for polymer chemistry. Clearly label all intermediates and arrow-pushing steps.', '2025-10-20', 'CHEM1234'),
('Prepare a safety data summary for the reagents used in the spectroscopy lab and assess associated hazards.', '2025-11-14', 'CHEM1234'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-12-13', 'CHEM1234'),
('Write an essay discussing the role of the immune system in human disease. Use at least six academic references.', '2025-09-27', 'BIOL1668'),
('Critically evaluate two research papers on enzyme kinetics and compare their methodologies and conclusions.', '2025-11-04', 'BIOL1668'),
('Design a controlled experiment to investigate the effect of an environmental variable on natural selection.', '2025-11-13', 'BIOL1668'),
('Create an annotated diagram of the enzyme kinetics process, explaining each stage in your own words.', '2025-11-25', 'BIOL1668'),
('Prepare a lab report on the the immune system experiment from Week 5. Include your hypothesis, results, and discussion.', '2025-11-26', 'BIOL1668'),
('Analyse the experimental data provided using simple harmonic motion principles and present your conclusions.', '2025-10-18', 'PHYS1457'),
('Solve the wave optics problem set. Include free-body diagrams where applicable.', '2025-11-05', 'PHYS1457'),
('Derive the equations of motion for the given thermodynamics system from first principles.', '2025-11-20', 'PHYS1457'),
('Write a lab report for the quantum mechanics experiment. Compare your results to the theoretical values and discuss errors.', '2025-12-05', 'PHYS1457'),
('Research a real-world application of electromagnetic induction and write a two-page technical summary.', '2025-10-07', 'PHYS2726'),
('Solve the simple harmonic motion problem set. Include free-body diagrams where applicable.', '2025-11-06', 'PHYS2726'),
('Analyse the experimental data provided using simple harmonic motion principles and present your conclusions.', '2025-12-05', 'PHYS2726'),
('Write a lab report for the electromagnetic induction experiment. Compare your results to the theoretical values and discuss errors.', '2025-12-07', 'PHYS2726'),
('Derive the equations of motion for the given simple harmonic motion system from first principles.', '2025-12-12', 'PHYS2726'),
('Write a lab report for the projectile motion experiment. Compare your results to the theoretical values and discuss errors.', '2025-10-04', 'PHYS2364'),
('Solve the thermodynamics problem set. Include free-body diagrams where applicable.', '2025-11-01', 'PHYS2364'),
('Analyse the experimental data provided using thermodynamics principles and present your conclusions.', '2025-11-03', 'PHYS2364'),
('Write a 500-word essay in Spanish on the topic of family life. Focus on grammatical accuracy and vocabulary range.', '2025-02-14', 'SPAN1379'),
('Prepare a written dialogue in Spanish between two characters discussing technology.', '2025-03-30', 'SPAN1379'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-02-20', 'GEOL1068'),
('Write a field report based on the river deltas site visit conducted in Week 4.', '2025-03-04', 'GEOL1068'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-04-12', 'GEOL1068'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-04-15', 'GEOL1068'),
('Research the geologic history of river deltas and write a two-page summary with cited sources.', '2025-04-28', 'GEOL1068'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-02-17', 'GEOL2238'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-04-12', 'GEOL2238'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-04-22', 'GEOL2238'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-10-03', 'GEOL2378'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-10-21', 'GEOL2378'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-11-20', 'GEOL2378'),
('Write a field report based on the river deltas site visit conducted in Week 4.', '2025-11-20', 'GEOL2378'),
('Research the geologic history of river deltas and write a two-page summary with cited sources.', '2025-11-30', 'GEOL2378'),
('Write a formal letter in French responding to the scenario described in the case study.', '2025-11-10', 'FRENCH2386'),
('Analyse the grammatical structures in the provided French text and annotate them.', '2025-11-10', 'FRENCH2386'),
('Write a 500-word essay in French on the topic of technology. Pay attention to agreement and verb conjugation.', '2025-11-30', 'FRENCH2386'),
('Record a two-minute spoken response in French on the environment. Submit as an audio file.', '2025-12-03', 'FRENCH2386'),
('Translate the provided passage from English to French, preserving tone and meaning.', '2025-12-08', 'FRENCH2386'),
('Translate the provided passage from English into Japanese.', '2025-02-03', 'JAPA1775'),
('Write a short essay in Japanese on the topic of travel. Minimum 200 characters.', '2025-03-13', 'JAPA1775'),
('Complete the grammar exercises for the structures covered in Weeks 4-6.', '2025-03-13', 'JAPA1775'),
('Record a spoken response in Japanese describing technology. Submit as an audio file.', '2025-04-04', 'JAPA1775'),
('Write a dialogue in Japanese between two characters meeting for the first time.', '2025-04-28', 'JAPA1775'),
('Record a two-minute spoken response in Spanish describing culture. Submit as an audio file.', '2025-03-13', 'SPAN1764'),
('Analyse the grammatical structures used in the provided Spanish text and annotate them with explanations.', '2025-03-21', 'SPAN1764'),
('Translate the provided passage from English to Spanish, preserving tone and meaning.', '2025-04-12', 'SPAN1764'),
('Write a 500-word essay in Spanish on the topic of the environment. Focus on grammatical accuracy and vocabulary range.', '2025-04-22', 'SPAN1764'),
('Write a lab report for the simple harmonic motion experiment. Compare your results to the theoretical values and discuss errors.', '2025-02-19', 'PHYS1520'),
('Solve the electromagnetic induction problem set. Include free-body diagrams where applicable.', '2025-04-01', 'PHYS1520'),
('Research a real-world application of wave optics and write a two-page technical summary.', '2025-04-20', 'PHYS1520'),
('Derive the equations of motion for the given simple harmonic motion system from first principles.', '2025-04-20', 'PHYS1520'),
('Analyse the experimental data provided using quantum mechanics principles and present your conclusions.', '2025-02-08', 'PHYS2301'),
('Research a real-world application of projectile motion and write a two-page technical summary.', '2025-02-19', 'PHYS2301'),
('Derive the equations of motion for the given electromagnetic induction system from first principles.', '2025-03-28', 'PHYS2301'),
('Write a lab report for the quantum mechanics experiment. Compare your results to the theoretical values and discuss errors.', '2025-04-27', 'PHYS2301'),
('Write a lab report for the thermodynamics experiment. Compare your results to the theoretical values and discuss errors.', '2025-02-24', 'PHYS2172'),
('Solve the simple harmonic motion problem set. Include free-body diagrams where applicable.', '2025-02-25', 'PHYS2172'),
('Analyse the experimental data provided using wave optics principles and present your conclusions.', '2025-04-02', 'PHYS2172'),
('Derive the equations of motion for the given thermodynamics system from first principles.', '2025-04-10', 'PHYS2172'),
('Research a real-world application of thermodynamics and write a two-page technical summary.', '2025-04-25', 'PHYS2172'),
('Write an essay discussing the role of natural selection in human disease. Use at least six academic references.', '2025-10-03', 'BIOL1666'),
('Design a controlled experiment to investigate the effect of an environmental variable on DNA replication.', '2025-10-06', 'BIOL1666'),
('Create an annotated diagram of the DNA replication process, explaining each stage in your own words.', '2025-11-23', 'BIOL1666'),
('Critically evaluate two research papers on DNA replication and compare their methodologies and conclusions.', '2025-12-01', 'BIOL1666'),
('Translate the provided English passage into Mandarin Chinese.', '2025-02-14', 'CHIN1300'),
('Write a short paragraph in Mandarin describing family. Use a minimum of 150 characters.', '2025-03-13', 'CHIN1300'),
('Answer the comprehension questions on the provided Mandarin reading passage.', '2025-03-21', 'CHIN1300'),
('Write a dialogue in Mandarin between two people discussing daily life.', '2025-04-11', 'CHIN1300'),
('Record yourself reading the provided Mandarin text aloud. Submit as an audio file.', '2025-04-15', 'CHIN1300'),
('Solve the attached discrete mathematics problem set and verify your answers using any computational tool.', '2025-02-04', 'MATH1168'),
('Model the real-world scenario below using discrete mathematics techniques and interpret your results.', '2025-03-04', 'MATH1168'),
('Write a short essay comparing two approaches to probability, with worked examples for each.', '2025-03-22', 'MATH1168'),
('Complete the problem set on discrete mathematics. Show all working - answers without justification will not receive credit.', '2025-04-08', 'MATH1168'),
('Critically evaluate two research papers on enzyme kinetics and compare their methodologies and conclusions.', '2025-03-16', 'BIOL3360'),
('Prepare a lab report on the natural selection experiment from Week 3. Include your hypothesis, results, and discussion.', '2025-04-07', 'BIOL3360'),
('Create an annotated diagram of the mitosis process, explaining each stage in your own words.', '2025-04-23', 'BIOL3360'),
('Write a field report based on the river deltas site visit conducted in Week 5.', '2025-11-03', 'GEOL2309'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-11-12', 'GEOL2309'),
('Research the geologic history of river deltas and write a two-page summary with cited sources.', '2025-11-14', 'GEOL2309'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-02-10', 'GEOL1787'),
('Research the geologic history of volcanic activity and write a two-page summary with cited sources.', '2025-03-06', 'GEOL1787'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-03-31', 'GEOL1787'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-04-08', 'GEOL1787'),
('Write a field report based on the sedimentary basins site visit conducted in Week 5.', '2025-04-27', 'GEOL1787'),
('Create an annotated diagram of the natural selection process, explaining each stage in your own words.', '2025-04-11', 'BIOL2895'),
('Design a controlled experiment to investigate the effect of an environmental variable on mitosis.', '2025-04-25', 'BIOL2895');

