-- CALENDAR EVENT INSERTS
INSERT INTO CalendarEvent (event_name, details, event_date, c_code) VALUES
('DevOps: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-17', 'SWEN1340'),
('Software Design In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-10-12', 'SWEN1340'),
('Week 13 Tutorial - Software Design', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-12', 'SWEN1340'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-11-29', 'SWEN1340'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-01-12', 'SWEN1765'),
('Week 5 Lecture - DevOps', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-22', 'SWEN1765'),
('Tutorial: DevOps Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-23', 'SWEN1765'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-02-02', 'SWEN1765'),
('Business Intelligence: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-02', 'INFO2930'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-09-14', 'COMP2738'),
('Introduction to Operating Systems', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-20', 'COMP2738'),
('Algorithms: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-04', 'COMP2738'),
('Networking In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-12-13', 'COMP2738'),
('Unit 1 Test - Networking', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-12-15', 'COMP2738'),
('Database Design: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-02', 'INFO2977'),
('Information Security In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-10-14', 'INFO2977'),
('Week 13 Tutorial - Business Intelligence', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-20', 'INFO2977'),
('Introduction to Data Analytics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-28', 'INFO1085'),
('Tutorial: IT Project Management Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-29', 'INFO1085'),
('Quiz 1 - IT Project Management', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-10-23', 'INFO1390'),
('Agile Methods: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-13', 'SWEN3258'),
('Quiz 1 - Software Design', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-12-10', 'SWEN3258'),
('Statistics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-02', 'MATH1775'),
('Unit 1 Test - Linear Algebra', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-04-17', 'MATH1775'),
('Numerical Methods Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-08', 'MATH2417'),
('Lecturer Office Hours - Week 7', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-09-03', 'MATH2210'),
('Introduction to Probability', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-07', 'MATH2210'),
('Week 1 Tutorial - Discrete Mathematics', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-28', 'MATH2210'),
('Introduction to Statistics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-05', 'MATH3187'),
('Introduction to Statistics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-17', 'MATH3187'),
('Lecturer Office Hours - Week 1', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-12-01', 'MATH3187'),
('Quiz 1 - Linear Algebra', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-09-19', 'MATH1714'),
('Tutorial: Calculus Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-21', 'MATH1714'),
('Chapter Quiz: Numerical Methods', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-03-13', 'MATH1373'),
('Tutorial: Linear Algebra Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-12', 'MATH1773'),
('Week 13 Lecture - Numerical Methods', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-27', 'MATH1773'),
('Week 13 Lecture - Statistics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-25', 'MATH1773'),
('Introduction to Inorganic Chemistry', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-29', 'CHEM1658'),
('Lab Session 1 - Thermochemistry', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-10-03', 'CHEM1658'),
('Analytical Methods: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-12', 'CHEM1658'),
('Introduction to Inorganic Chemistry', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-09', 'CHEM2807'),
('Chapter Quiz: Organic Chemistry', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-03-11', 'CHEM2807'),
('Chapter Quiz: Organic Chemistry', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-03-31', 'CHEM2807'),
('Quiz 1 - Analytical Methods', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-04-03', 'CHEM2807'),
('Tutorial: Organic Chemistry Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-24', 'CHEM1997'),
('Introduction to Thermochemistry', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-11', 'CHEM2920'),
('Week 10 Tutorial - Analytical Methods', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-25', 'CHEM2920'),
('Quiz 1 - Analytical Methods', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-04-27', 'CHEM2771'),
('Inorganic Chemistry: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-29', 'CHEM2882'),
('Organic Chemistry Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-05', 'CHEM2882'),
('Introduction to Inorganic Chemistry', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-18', 'CHEM2882'),
('Thermochemistry: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-16', 'CHEM3064'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-10-07', 'PHYS2551'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-11-11', 'PHYS2551'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-11-14', 'PHYS2551'),
('Week 8 Lecture - Wave Optics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-04', 'PHYS2551'),
('Introduction to Electromagnetism', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-22', 'PHYS2123'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-10-07', 'PHYS2867'),
('Electromagnetism Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-25', 'PHYS2867'),
('Introduction to Mechanics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-30', 'PHYS2867'),
('Quantum Physics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-09', 'PHYS2867'),
('Electromagnetism: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-07', 'PHYS2867'),
('Tutorial: Thermodynamics Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-05', 'PHYS3356'),
('Chapter Quiz: Quantum Physics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-11-09', 'PHYS3356'),
('Tutorial: Wave Optics Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-11', 'PHYS3356'),
('Mechanics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-01', 'PHYS3356'),
('Lab Session 1 - Electromagnetism', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-10-20', 'PHYS1967'),
('Week 12 Tutorial - Thermodynamics', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-09', 'PHYS3025'),
('Mechanics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-11', 'PHYS3025'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-03-24', 'PHYS3025'),
('Introduction to Thermodynamics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-18', 'PHYS3025'),
('Thermodynamics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-16', 'PHYS3230'),
('Quantum Physics In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-04-17', 'PHYS3230'),
('Genetics Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-06', 'BIOL2230'),
('Tutorial: Ecology Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-10', 'BIOL2230'),
('Human Biology: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-14', 'BIOL2230'),
('Chapter Quiz: Genetics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-12-15', 'BIOL2230'),
('Introduction to Genetics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-15', 'BIOL2230'),
('Introduction to Cell Biology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-04', 'BIOL2783'),
('Tutorial: Genetics Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-09', 'BIOL2783'),
('Human Biology: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-09', 'BIOL2783'),
('Cell Biology: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-10', 'BIOL2783'),
('Week 6 Lecture - Ecology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-22', 'BIOL2783'),
('Genetics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-26', 'BIOL1856'),
('Week 13 Lecture - Ecology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-27', 'BIOL1856'),
('Cell Biology Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-08', 'BIOL1856'),
('Week 3 Lecture - Cell Biology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-23', 'BIOL1856'),
('Microbiology In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-03-27', 'BIOL2226'),
('Tutorial: Ecology Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-21', 'BIOL2226'),
('Lecturer Office Hours - Week 2', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-03-12', 'BIOL3225'),
('Tutorial: Cell Biology Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-09', 'BIOL1382'),
('Week 3 Lecture - Ecology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-07', 'BIOL1382'),
('Genetics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-06', 'BIOL1925'),
('Introduction to Written Composition', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-17', 'SPAN3405'),
('Verb Conjugation: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-17', 'SPAN3405'),
('Hispanic Literature: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-04', 'SPAN3405'),
('Lab Session 1 - Spanish Grammar', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-04-06', 'SPAN3405'),
('Verb Conjugation: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-07', 'SPAN1630'),
('Introduction to Spanish Grammar', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-21', 'SPAN1630'),
('Hispanic Literature Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-28', 'SPAN1630'),
('Introduction to Japanese Grammar', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-18', 'JAPA3124'),
('Tutorial: Kanji Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-21', 'JAPA3124'),
('Introduction to Japanese Culture', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-22', 'JAPA3124'),
('Introduction to Japanese Culture', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-28', 'JAPA3124'),
('Reading Comprehension Practical', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-09-06', 'CHIN1048'),
('Week 6 Lecture - Character Writing', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-17', 'CHIN1048'),
('Week 4 Tutorial - Oral Expression', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-14', 'CHIN1048'),
('Lecturer Office Hours - Week 3', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-01-21', 'SPAN1368'),
('Week 13 Tutorial - Verb Conjugation', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-07', 'SPAN2548'),
('Spanish Grammar Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-05', 'SPAN2548'),
('Week 11 Tutorial - Spanish Grammar', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-12-04', 'SPAN2548'),
('Introduction to Chinese Culture', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-05', 'CHIN1804'),
('Character Writing In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-09-28', 'CHIN1804'),
('Reading Comprehension In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-10-20', 'CHIN1804'),
('Mandarin Tones Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-12', 'CHIN1804'),
('Week 8 Lecture - Mineralogy', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-14', 'GEOL3356'),
('Week 7 Tutorial - Structural Geology', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-20', 'GEOL3356'),
('Week 10 Lecture - Geophysics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-19', 'GEOL3356'),
('Week 1 Lecture - Petrology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-30', 'GEOL3356'),
('Tutorial: Petrology Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-10', 'GEOL3356'),
('Introduction to Structural Geology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-16', 'GEOL2631'),
('Introduction to Earth History', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-26', 'GEOL2631'),
('Quiz 2 - Structural Geology', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-09-30', 'GEOL2631'),
('Quiz 1 - Earth History', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-10-12', 'GEOL2631'),
('Mineralogy: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-13', 'GEOL3304'),
('Introduction to Earth History', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-14', 'GEOL3304'),
('Structural Geology Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-12-15', 'GEOL3304'),
('Tutorial: Geophysics Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-15', 'GEOL1169'),
('Tutorial: Mineralogy Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-01', 'GEOL1169'),
('Petrology In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-04-23', 'GEOL1169'),
('Introduction to Structural Geology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-17', 'GEOL1048'),
('Earth History: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-11', 'GEOL1048'),
('Tutorial: Earth History Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-30', 'GEOL2436'),
('Week 5 Lecture - Petrology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-07', 'GEOL2436'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-03-10', 'GEOL2436'),
('Unit 1 Test - Structural Geology', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-03-30', 'GEOL2436'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-04-17', 'GEOL2436'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-09-18', 'GEOL3045'),
('Introduction to Petrology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-19', 'GEOL3045'),
('Petrology Practical', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-12-03', 'GEOL3045'),
('Introduction to Earth History', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-11', 'GEOL3045'),
('Introduction to Thermochemistry', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-19', 'CHEM3134'),
('Organic Chemistry Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-29', 'CHEM3134'),
('Lab Session 1 - Analytical Methods', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-02-12', 'CHEM3134'),
('Week 8 Lecture - Thermochemistry', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-12', 'CHEM3134'),
('Analytical Methods: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-05', 'CHEM3134'),
('Chapter Quiz: Francophone Literature', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-11-05', 'FRENCH2201'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-11-08', 'FRENCH2201'),
('Chapter Quiz: Francophone Literature', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-11-08', 'FRENCH2201'),
('Week 8 Lecture - Written Composition', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-05', 'FRENCH2201'),
('Week 5 Lecture - Calculus', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-02', 'MATH1195'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-04-10', 'MATH1195'),
('Lecturer Office Hours - Week 8', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-09-23', 'MATH1303'),
('Introduction to Discrete Mathematics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-22', 'MATH1303'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-11-01', 'MATH1303'),
('Introduction to Statistics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-28', 'MATH1303'),
('Lecturer Office Hours - Week 3', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-11-30', 'MATH1303'),
('Introduction to Earth History', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-30', 'GEOL2487'),
('Introduction to Geophysics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-25', 'GEOL2487'),
('Introduction to Geophysics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-09', 'GEOL2487'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-04-29', 'BIOL2509'),
('Agile Methods Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-03', 'SWEN1182'),
('Requirements Engineering: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-06', 'SWEN1182'),
('Week 8 Lecture - Agile Methods', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-25', 'SWEN1182'),
('Introduction to Software Testing', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-03', 'SWEN1182'),
('Unit 1 Test - Inorganic Chemistry', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-03-10', 'CHEM1668'),
('Laboratory: Spectroscopy', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-04-10', 'CHEM1668'),
('Week 7 Tutorial - Electromagnetism', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-08', 'PHYS2279'),
('Introduction to Mechanics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-18', 'PHYS2279'),
('Wave Optics In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-03-03', 'PHYS2279'),
('Lecturer Office Hours - Week 6', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-11-01', 'PHYS3064'),
('Mechanics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-12', 'PHYS3064'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-02-15', 'GEOL3129'),
('Kanji Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-24', 'JAPA3090'),
('Japanese Culture Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-30', 'JAPA3090'),
('Laboratory: Petrology', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-02-22', 'GEOL1059'),
('Week 5 Tutorial - Earth History', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-26', 'GEOL1059'),
('Quiz 1 - Mineralogy', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-03-28', 'GEOL1059'),
('Earth History Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-19', 'GEOL1059'),
('Introduction to Human Biology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-13', 'BIOL2118'),
('Quiz 1 - Microbiology', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-02-16', 'BIOL2118'),
('Week 2 Tutorial - Ecology', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-26', 'BIOL2118'),
('Unit 1 Test - Microbiology', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-04-02', 'BIOL2118'),
('Genetics Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-18', 'BIOL2118'),
('Spectroscopy: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-07', 'CHEM1170'),
('Week 5 Tutorial - Inorganic Chemistry', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-18', 'CHEM1170'),
('Week 4 Tutorial - Quantum Physics', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-12', 'PHYS3431'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-10-04', 'PHYS3431'),
('Week 12 Tutorial - Thermodynamics', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-12-12', 'PHYS3431'),
('Week 11 Lecture - Quantum Physics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-13', 'PHYS3431'),
('Mineralogy: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-25', 'GEOL1019'),
('Introduction to Petrology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-06', 'GEOL1019'),
('Petrology: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-17', 'GEOL1019'),
('Mineralogy Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-26', 'GEOL1019'),
('Lecturer Office Hours - Week 3', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-09-25', 'SPAN2173'),
('Quiz 1 - Oral Expression', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-09-25', 'SPAN2173'),
('Written Composition: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-30', 'SPAN2173'),
('Week 6 Tutorial - Mechanics', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-02', 'PHYS2548'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-11-14', 'PHYS2548'),
('Tutorial: Requirements Engineering Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-20', 'SWEN2702'),
('Chapter Quiz: Agile Methods', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-02-19', 'SWEN2702'),
('DevOps Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-03', 'SWEN2702'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-09-11', 'PHYS1824'),
('Week 12 Lecture - Electromagnetism', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-14', 'PHYS1824'),
('Quantum Physics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-03', 'PHYS1824'),
('Quiz 1 - Electromagnetism', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-11-01', 'PHYS1824'),
('Week 2 Lecture - Electromagnetism', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-15', 'PHYS1824'),
('Laboratory: Spanish Grammar', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-01-19', 'SPAN1492'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-02-17', 'SPAN1492'),
('Week 12 Tutorial - Written Composition', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-04', 'SPAN1492'),
('Inorganic Chemistry: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-14', 'CHEM2075'),
('Hiragana & Katakana: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-15', 'JAPA2859'),
('Japanese Culture Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-18', 'JAPA2859'),
('Organic Chemistry In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-01-10', 'CHEM2214'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-01-20', 'CHEM2214'),
('Thermochemistry Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-05', 'CHEM2214'),
('Week 10 Lecture - Ecology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-12', 'BIOL1178'),
('Wave Optics In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-10-07', 'PHYS1866'),
('Week 13 Lecture - Character Writing', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-08', 'CHIN3356'),
('Week 8 Tutorial - Reading Comprehension', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-16', 'CHIN3356'),
('Introduction to Linear Algebra', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-04', 'MATH2070'),
('Quiz 1 - Statistics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-10-21', 'MATH2070'),
('Week 8 Lecture - Numerical Methods', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-07', 'MATH2070'),
('Week 7 Lecture - Agile Methods', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-23', 'SWEN3038'),
('Genetics In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-01-28', 'BIOL1917'),
('Week 6 Lecture - Ecology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-01', 'BIOL1917'),
('Human Biology In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-02-16', 'BIOL1917'),
('Human Biology: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-22', 'BIOL1917'),
('Week 4 Lecture - Ecology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-01', 'BIOL1917'),
('Week 3 Lecture - Ecology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-02', 'BIOL1878'),
('Human Biology: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-22', 'BIOL1878'),
('Earth History Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-16', 'GEOL1823'),
('Structural Geology: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-23', 'GEOL1823'),
('Week 6 Tutorial - Structural Geology', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-16', 'GEOL1823'),
('Tutorial: Reading Comprehension Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-14', 'CHIN2805'),
('Mandarin Tones: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-20', 'CHIN2805'),
('Introduction to Character Writing', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-17', 'CHIN2805'),
('Introduction to Mandarin Tones', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-04', 'CHIN2805'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-02-04', 'BIOL1711'),
('Chapter Quiz: Ecology', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-04-08', 'BIOL1711'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-03-18', 'BIOL2622'),
('Unit 1 Test - IT Project Management', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-01-07', 'INFO1184'),
('Laboratory: Structural Geology', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-01-18', 'GEOL2731'),
('Tutorial: Geophysics Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-01', 'GEOL2731'),
('Structural Geology Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-13', 'GEOL2731'),
('Chapter Quiz: Structural Geology', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-03-28', 'GEOL2731'),
('Week 12 Lecture - Geophysics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-08', 'GEOL2731'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-10-16', 'COMP2464'),
('Databases In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-10-27', 'COMP2464'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-10-30', 'COMP2464'),
('Introduction to Software Engineering', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-29', 'COMP2464'),
('Week 2 Tutorial - Algorithms', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-12-01', 'COMP2464'),
('Tutorial: Cell Biology Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-08', 'BIOL1904'),
('Quiz 1 - Cell Biology', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-02-12', 'BIOL1904'),
('Week 3 Lecture - Genetics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-06', 'BIOL1743'),
('Week 13 Lecture - Genetics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-27', 'BIOL1743'),
('Week 7 Tutorial - Ecology', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-10', 'BIOL1743'),
('Week 3 Tutorial - Human Biology', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-10', 'BIOL1453'),
('Ecology: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-27', 'BIOL1453'),
('Genetics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-07', 'BIOL1453'),
('Genetics Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-16', 'BIOL1453'),
('Week 7 Tutorial - Ecology', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-29', 'BIOL1453'),
('Electromagnetism: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-18', 'PHYS2914'),
('Week 4 Lecture - Mechanics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-18', 'PHYS2914'),
('Chapter Quiz: Electromagnetism', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-02-20', 'PHYS2914'),
('Week 8 Lecture - Wave Optics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-03', 'PHYS2914'),
('Mineralogy: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-30', 'GEOL1700'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-10-26', 'GEOL1700'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-01-29', 'CHEM3125'),
('Analytical Methods Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-22', 'CHEM3125'),
('Introduction to Inorganic Chemistry', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-21', 'CHEM3125'),
('Week 8 Tutorial - Thermochemistry', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-25', 'CHEM3125'),
('Linear Algebra: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-15', 'MATH1139'),
('Statistics Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-28', 'MATH1139'),
('Discrete Mathematics In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-04-24', 'MATH1139'),
('Tutorial: Statistics Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-26', 'MATH1139'),
('Week 4 Lecture - Geophysics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-28', 'GEOL2467'),
('Week 13 Lecture - Geophysics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-23', 'GEOL2467'),
('Introduction to Geophysics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-29', 'GEOL2467'),
('Geophysics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-30', 'GEOL2467'),
('Inorganic Chemistry In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-10-20', 'CHEM2208'),
('Week 2 Lecture - Electromagnetism', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-23', 'PHYS1944'),
('Introduction to Mechanics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-21', 'PHYS1944'),
('Mechanics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-28', 'PHYS1944'),
('Wave Optics Practical', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-04-14', 'PHYS1944'),
('Tutorial: Electromagnetism Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-14', 'PHYS1944'),
('Cell Biology: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-19', 'BIOL3197'),
('Introduction to Cell Biology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-22', 'BIOL3197'),
('Tutorial: Human Biology Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-04', 'BIOL3197'),
('Microbiology Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-01', 'BIOL1635'),
('Lab Session 1 - Ecology', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-09-19', 'BIOL1635'),
('Introduction to Human Biology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-28', 'BIOL1635'),
('Introduction to Calculus', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-14', 'MATH1270'),
('Week 11 Lecture - Calculus', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-24', 'MATH1270'),
('Numerical Methods Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-26', 'MATH1270'),
('Calculus: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-09', 'MATH1270'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-09-02', 'BIOL2801'),
('Human Biology: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-01', 'BIOL2801'),
('Tutorial: Genetics Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-27', 'BIOL2801'),
('Chapter Quiz: Genetics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-10-28', 'BIOL2801'),
('Ecology Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-28', 'BIOL2801'),
('Week 6 Lecture - Ecology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-17', 'BIOL2705'),
('Laboratory: Cell Biology', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-03-02', 'BIOL2705'),
('Human Biology Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-19', 'BIOL2705'),
('Week 5 Lecture - Ecology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-27', 'BIOL2705'),
('Laboratory: Quantum Physics', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-09-12', 'PHYS1590'),
('Electromagnetism: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-30', 'PHYS1590'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-10-21', 'PHYS1590'),
('Electromagnetism: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-04', 'PHYS1590'),
('Week 6 Lecture - Wave Optics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-21', 'PHYS1590'),
('Mechanics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-01', 'PHYS2201'),
('Introduction to Quantum Physics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-15', 'PHYS2314'),
('Tutorial: Electromagnetism Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-26', 'PHYS2314'),
('Quiz 1 - Wave Optics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-03-06', 'PHYS2314'),
('Quiz 1 - Structural Geology', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-01-09', 'GEOL3310'),
('Mineralogy: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-07', 'GEOL3310'),
('Week 11 Lecture - Electromagnetism', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-05', 'PHYS2525'),
('Week 10 Lecture - Electromagnetism', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-12', 'PHYS2525'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-01-31', 'MATH3379'),
('Introduction to Discrete Mathematics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-08', 'MATH3379'),
('Introduction to Discrete Mathematics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-10', 'MATH3379'),
('Probability In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-02-27', 'MATH3379'),
('Introduction to French Grammar', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-08', 'FRENCH1240'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-09-11', 'FRENCH1240'),
('Written Composition: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-29', 'FRENCH1240'),
('French Grammar: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-09', 'FRENCH1240'),
('Laboratory: Microbiology', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-03-15', 'BIOL2516'),
('Week 9 Tutorial - Ecology', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-25', 'BIOL2516'),
('Calculus In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-02-20', 'MATH2772'),
('Week 10 Lecture - Statistics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-29', 'MATH2772'),
('Tutorial: Statistics Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-27', 'MATH2772'),
('Geophysics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-05', 'GEOL1865'),
('Mineralogy In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-09-16', 'GEOL1865'),
('Laboratory: Earth History', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-10-16', 'GEOL1865'),
('Petrology Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-02', 'GEOL1865'),
('Unit 1 Test - Geophysics', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-11-11', 'GEOL1865'),
('Quiz 1 - Organic Chemistry', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-09-05', 'CHEM1065'),
('Chapter Quiz: Analytical Methods', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-11-02', 'CHEM1065'),
('Tutorial: Analytical Methods Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-07', 'CHEM1065'),
('Week 7 Tutorial - Thermochemistry', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-26', 'CHEM1065'),
('Quiz 1 - Structural Geology', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-09-20', 'GEOL3344'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-11-25', 'GEOL3344'),
('Tutorial: Calculus Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-09', 'MATH2558'),
('Chapter Quiz: Probability', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-01-09', 'MATH2558'),
('Numerical Methods Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-27', 'MATH2558'),
('Quiz 2 - Discrete Mathematics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-02-27', 'MATH2558'),
('Week 8 Tutorial - Statistics', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-28', 'MATH2558'),
('Week 8 Tutorial - Wave Optics', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-06', 'PHYS1759'),
('Lab Session 1 - Thermodynamics', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-04-22', 'PHYS1759'),
('Software Design Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-28', 'SWEN2288'),
('Introduction to Networking', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-18', 'COMP1016'),
('Week 11 Tutorial - Data Structures', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-14', 'COMP1016'),
('Week 10 Lecture - Data Structures', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-16', 'COMP1016'),
('Computer Architecture Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-12-06', 'COMP1016'),
('Introduction to Software Engineering', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-07', 'COMP1016'),
('Lecturer Office Hours - Week 1', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-01-06', 'BIOL2374'),
('Chapter Quiz: Microbiology', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-03-12', 'BIOL2374'),
('Week 10 Tutorial - Human Biology', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-04', 'BIOL2374'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-04-12', 'BIOL2374'),
('Tutorial: Organic Chemistry Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-19', 'CHEM1880'),
('Organic Chemistry In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-04-29', 'CHEM1880'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-02-02', 'MATH2073'),
('Introduction to Probability', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-16', 'MATH2073'),
('Statistics Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-30', 'MATH2073'),
('Week 8 Lecture - Cell Biology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-23', 'BIOL2635'),
('Introduction to Human Biology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-20', 'BIOL2635'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-02-20', 'BIOL2635'),
('Laboratory: Human Biology', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-02-22', 'BIOL2635'),
('Introduction to Software Engineering', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-04', 'COMP1423'),
('Week 12 Lecture - Algorithms', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-12', 'COMP1423'),
('Inorganic Chemistry In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-10-06', 'CHEM3351'),
('Week 2 Lecture - Thermochemistry', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-08', 'CHEM3351'),
('Week 5 Tutorial - Organic Chemistry', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-20', 'CHEM3351'),
('Week 7 Tutorial - Spectroscopy', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-10', 'CHEM3351'),
('Week 3 Tutorial - Spectroscopy', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-26', 'CHEM3351'),
('Week 9 Lecture - Earth History', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-06', 'GEOL1938'),
('Tutorial: Geophysics Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-08', 'GEOL1938'),
('Quiz 1 - Statistics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-09-04', 'MATH1466'),
('Linear Algebra Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-10', 'MATH1466'),
('Chapter Quiz: Linear Algebra', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-10-25', 'MATH1466'),
('Discrete Mathematics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-09', 'MATH1466'),
('Linear Algebra Practical', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-11-28', 'MATH1466'),
('Linear Algebra Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-25', 'MATH1340'),
('Unit 1 Test - Linear Algebra', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-01-31', 'MATH1340'),
('Week 13 Tutorial - Calculus', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-05', 'MATH1340'),
('Chapter Quiz: Electromagnetism', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-10-01', 'PHYS2506'),
('Wave Optics Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-16', 'PHYS2506'),
('Tutorial: Mechanics Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-07', 'PHYS2506'),
('Tutorial: Calculus Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-13', 'MATH2086'),
('Week 5 Lecture - Linear Algebra', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-14', 'MATH1337'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-03-09', 'MATH1337'),
('Numerical Methods In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-03-11', 'MATH1337'),
('Unit 1 Test - Spanish Grammar', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-02-24', 'SPAN3483'),
('Quiz 1 - Spanish Grammar', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-02-26', 'SPAN3483'),
('Week 8 Lecture - Hispanic Literature', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-17', 'SPAN3483'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-09-29', 'CHIN1064'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-09-14', 'BIOL1910'),
('Introduction to Microbiology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-03', 'BIOL1910'),
('Genetics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-07', 'BIOL1910'),
('Genetics Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-16', 'BIOL2058'),
('Week 10 Lecture - Ecology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-01', 'BIOL2058'),
('Introduction to Human Biology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-17', 'BIOL2058'),
('Introduction to Ecology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-02', 'BIOL2058'),
('Week 8 Lecture - Ecology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-06', 'BIOL2058'),
('Introduction to Francophone Literature', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-14', 'FRENCH2325'),
('Chapter Quiz: French Grammar', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-02-23', 'FRENCH2325'),
('Tutorial: Oral Expression Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-20', 'FRENCH2325'),
('Introduction to Written Composition', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-01', 'FRENCH2325'),
('Tutorial: French Grammar Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-16', 'FRENCH2325'),
('Oral Expression: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-18', 'CHIN3274'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-02-05', 'CHIN3274'),
('Character Writing: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-20', 'CHIN3274'),
('Thermochemistry: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-06', 'CHEM2917'),
('Tutorial: Organic Chemistry Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-11', 'CHEM2917'),
('Introduction to Wave Optics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-18', 'PHYS1325'),
('Introduction to Wave Optics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-22', 'PHYS1325'),
('Week 7 Lecture - Quantum Physics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-22', 'PHYS1325'),
('Tutorial: Electromagnetism Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-25', 'PHYS1325'),
('Thermodynamics Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-12-05', 'PHYS1325'),
('Tutorial: Inorganic Chemistry Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-17', 'CHEM2468'),
('Week 5 Lecture - Organic Chemistry', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-02', 'CHEM2468'),
('Tutorial: Inorganic Chemistry Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-04', 'CHEM2468'),
('Week 9 Lecture - Microbiology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-28', 'BIOL1768'),
('Ecology: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-02', 'BIOL1768'),
('Cell Biology: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-13', 'BIOL1768'),
('Human Biology: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-21', 'BIOL1768'),
('Introduction to Discrete Mathematics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-15', 'MATH3199'),
('Week 1 Lecture - Numerical Methods', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-24', 'MATH3199'),
('Quiz 1 - Statistics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-04-11', 'MATH3199'),
('Tutorial: Thermodynamics Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-28', 'PHYS1151'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-04-20', 'PHYS1151'),
('Week 7 Lecture - Agile Methods', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-13', 'SWEN2904'),
('Chapter Quiz: Requirements Engineering', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-02-03', 'SWEN2904'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-02-21', 'SWEN2904'),
('Week 4 Tutorial - Software Testing', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-05', 'SWEN2904'),
('Introduction to Software Design', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-09', 'SWEN2904'),
('Week 11 Tutorial - Numerical Methods', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-20', 'MATH1832'),
('Tutorial: Statistics Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-01', 'MATH1832'),
('Quiz 1 - Linear Algebra', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-03-26', 'MATH1832'),
('Lecturer Office Hours - Week 8', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-03-31', 'MATH1832'),
('Numerical Methods: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-10', 'MATH1832'),
('Tutorial: Hispanic Literature Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-24', 'SPAN1689'),
('Unit 1 Test - Spanish Grammar', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-03-02', 'SPAN1689'),
('Week 2 Lecture - Spanish Grammar', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-22', 'SPAN1689'),
('Quiz 2 - Numerical Methods', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-01-16', 'MATH3380'),
('Numerical Methods Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-16', 'MATH3380'),
('Chapter Quiz: Calculus', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-04-30', 'MATH3380'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-10-04', 'CHEM2110'),
('Tutorial: Analytical Methods Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-26', 'CHEM2110'),
('Week 1 Lecture - Analytical Methods', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-01', 'CHEM2110'),
('Tutorial: Oral Expression Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-31', 'FRENCH2790'),
('Introduction to Oral Expression', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-24', 'FRENCH2790'),
('Chapter Quiz: Listening Comprehension', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-04-03', 'FRENCH2790'),
('Week 1 Lecture - Business Intelligence', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-20', 'INFO1252'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-03-06', 'INFO1252'),
('Introduction to Database Design', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-12', 'INFO1252'),
('Introduction to Business Intelligence', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-17', 'INFO1252'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-09-01', 'BIOL2115'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-10-14', 'BIOL2115'),
('Human Biology In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-11-24', 'BIOL2115'),
('Quiz 1 - Organic Chemistry', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-01-11', 'CHEM2896'),
('Introduction to Thermochemistry', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-15', 'CHEM2896'),
('Introduction to Quantum Physics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-16', 'PHYS3492'),
('Mechanics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-13', 'PHYS3492'),
('Wave Optics Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-11', 'PHYS3492'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-04-14', 'PHYS3492'),
('Tutorial: Electromagnetism Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-26', 'PHYS3492'),
('Laboratory: Statistics', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-12-09', 'MATH2061'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-10-03', 'GEOL2066'),
('Mineralogy: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-31', 'GEOL2066'),
('Quiz 1 - Geophysics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-12-13', 'GEOL2066'),
('Quiz 1 - Probability', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-10-16', 'MATH1079'),
('Mechanics Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-20', 'PHYS1028'),
('Thermodynamics Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-26', 'PHYS1028'),
('Week 5 Tutorial - Quantum Physics', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-17', 'PHYS1028'),
('Francophone Literature Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-23', 'FRENCH2015'),
('Week 4 Lecture - French Grammar', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-03', 'FRENCH2015'),
('Listening Comprehension Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-11', 'FRENCH2015'),
('Introduction to Written Composition', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-09', 'FRENCH2015'),
('Week 6 Lecture - Ecology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-10', 'BIOL3168'),
('Lecturer Office Hours - Week 1', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-02-28', 'BIOL3168'),
('Lecturer Office Hours - Week 3', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-04-11', 'BIOL3168'),
('Introduction to Mandarin Tones', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-28', 'CHIN3152'),
('Week 4 Lecture - Mandarin Tones', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-13', 'CHIN3152'),
('Week 1 Lecture - Chinese Culture', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-20', 'CHIN3152'),
('Tutorial: Networking Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-12', 'COMP2199'),
('Lecturer Office Hours - Week 10', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-01-21', 'COMP2199'),
('Databases: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-23', 'COMP2199'),
('Computer Architecture In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-04-09', 'COMP2199'),
('Tutorial: Software Engineering Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-30', 'COMP2199'),
('Week 4 Tutorial - Structural Geology', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-02', 'GEOL2634'),
('Tutorial: Petrology Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-04', 'GEOL2634'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-02-11', 'GEOL2634'),
('Petrology In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-03-22', 'GEOL2634'),
('Week 7 Lecture - Mineralogy', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-29', 'GEOL2634'),
('Week 11 Lecture - Numerical Methods', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-02', 'MATH2132'),
('Week 5 Lecture - Calculus', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-10', 'MATH2132'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-04-09', 'MATH2132'),
('Written Composition Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-16', 'SPAN2816'),
('Tutorial: Hispanic Literature Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-31', 'SPAN2816');

INSERT INTO CalendarEvent (event_name, details, event_date, c_code) VALUES
('Lecturer Office Hours - Week 4', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-11-20', 'SPAN2816'),
('Spanish Grammar In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-11-22', 'SPAN2816'),
('Week 13 Lecture - Oral Expression', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-01', 'SPAN2816'),
('Introduction to Thermochemistry', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-22', 'CHEM1364'),
('Introduction to Thermochemistry', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-24', 'CHEM1364'),
('Week 5 Tutorial - Electromagnetism', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-03', 'PHYS2242'),
('Wave Optics Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-18', 'PHYS2242'),
('Laboratory: Calculus', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-01-20', 'MATH1683'),
('Tutorial: Numerical Methods Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-31', 'MATH1683'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-02-03', 'INFO2402'),
('Week 11 Tutorial - Calculus', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-04', 'MATH1125'),
('Discrete Mathematics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-25', 'MATH1125'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-11-04', 'MATH1125'),
('Introduction to Spectroscopy', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-22', 'CHEM1649'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-10-29', 'CHEM1649'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-10-30', 'CHEM1649'),
('Thermochemistry In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-12-08', 'CHEM1649'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-10-29', 'PHYS3499'),
('Chapter Quiz: Electromagnetism', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-12-11', 'PHYS3499'),
('Week 1 Tutorial - Wave Optics', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-23', 'PHYS1864'),
('Introduction to Quantum Physics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-30', 'PHYS1864'),
('Thermodynamics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-15', 'PHYS1864'),
('Introduction to Quantum Physics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-25', 'PHYS1864'),
('Thermodynamics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-04', 'PHYS1864'),
('Week 9 Lecture - Discrete Mathematics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-04', 'MATH2082'),
('Introduction to Calculus', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-21', 'MATH2082'),
('Week 6 Tutorial - Linear Algebra', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-30', 'MATH2082'),
('Week 9 Tutorial - Linear Algebra', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-28', 'MATH2082'),
('Chapter Quiz: Earth History', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-09-07', 'GEOL2503'),
('Laboratory: Mineralogy', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-10-19', 'GEOL2503'),
('Introduction to Mineralogy', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-23', 'GEOL2503'),
('Earth History In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-12-06', 'GEOL2503'),
('Tutorial: Human Biology Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-05', 'BIOL1579'),
('Ecology: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-27', 'BIOL1579'),
('Introduction to Microbiology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-28', 'BIOL1579'),
('Week 11 Lecture - Microbiology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-04', 'BIOL1579'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-04-29', 'BIOL1579'),
('Unit 1 Test - Wave Optics', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-02-27', 'PHYS1676'),
('Week 11 Lecture - Mechanics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-05', 'PHYS1676'),
('Introduction to Quantum Physics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-23', 'PHYS1676'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-04-13', 'PHYS1676'),
('Week 6 Tutorial - Human Biology', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-28', 'BIOL1333'),
('Cell Biology Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-20', 'BIOL1333'),
('Cell Biology Practical', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-04-03', 'BIOL1333'),
('Quiz 1 - Analytical Methods', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-10-23', 'CHEM1234'),
('Week 8 Tutorial - Thermochemistry', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-04', 'CHEM1234'),
('Week 7 Lecture - Spectroscopy', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-12', 'CHEM1234'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-09-27', 'BIOL1668'),
('Week 5 Lecture - Cell Biology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-03', 'BIOL1668'),
('Introduction to Human Biology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-13', 'BIOL1668'),
('Introduction to Thermodynamics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-11', 'PHYS1457'),
('Lecturer Office Hours - Week 11', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-10-02', 'PHYS1457'),
('Chapter Quiz: Thermodynamics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-10-15', 'PHYS1457'),
('Week 12 Tutorial - Electromagnetism', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-27', 'PHYS1457'),
('Quantum Physics Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-12-03', 'PHYS1457'),
('Chapter Quiz: Thermodynamics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-09-30', 'PHYS2726'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-10-15', 'PHYS2726'),
('Wave Optics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-21', 'PHYS2726'),
('Quantum Physics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-01', 'PHYS2726'),
('Quantum Physics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-22', 'PHYS2364'),
('Thermodynamics Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-23', 'PHYS2364'),
('Week 12 Lecture - Wave Optics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-28', 'PHYS2364'),
('Week 4 Tutorial - Thermodynamics', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-02', 'PHYS2364'),
('Chapter Quiz: Electromagnetism', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-12-07', 'PHYS2364'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-03-14', 'SPAN1379'),
('Tutorial: Petrology Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-04', 'GEOL1068'),
('Chapter Quiz: Geophysics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-03-07', 'GEOL1068'),
('Earth History: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-01', 'GEOL1068'),
('Unit 1 Test - Earth History', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-04-05', 'GEOL1068'),
('Week 6 Tutorial - Geophysics', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-28', 'GEOL2238'),
('Week 4 Tutorial - Structural Geology', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-08', 'GEOL2238'),
('Week 1 Tutorial - Geophysics', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-09', 'GEOL2238'),
('Mineralogy In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-03-27', 'GEOL2238'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-10-08', 'GEOL2378'),
('Structural Geology Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-22', 'GEOL2378'),
('Lecturer Office Hours - Week 2', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-09-06', 'FRENCH2386'),
('Chapter Quiz: French Grammar', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-10-14', 'FRENCH2386'),
('Introduction to Listening Comprehension', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-27', 'FRENCH2386'),
('Chapter Quiz: Oral Expression', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-12-13', 'FRENCH2386'),
('Week 8 Lecture - Japanese Culture', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-10', 'JAPA1775'),
('Week 8 Tutorial - Japanese Grammar', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-17', 'JAPA1775'),
('Week 10 Lecture - Kanji', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-24', 'JAPA1775'),
('Hiragana & Katakana: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-23', 'JAPA1775'),
('Tutorial: Verb Conjugation Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-08', 'SPAN1764'),
('Week 10 Lecture - Spanish Grammar', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-18', 'SPAN1764'),
('Tutorial: Written Composition Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-22', 'SPAN1764'),
('Week 1 Lecture - Verb Conjugation', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-24', 'SPAN1764'),
('Week 1 Lecture - Wave Optics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-17', 'PHYS1520'),
('Electromagnetism: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-02', 'PHYS1520'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-02-17', 'PHYS2301'),
('Introduction to Wave Optics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-04', 'PHYS2172'),
('Quiz 1 - Cell Biology', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-11-15', 'BIOL1666'),
('Tutorial: Oral Expression Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-09', 'CHIN1300'),
('Quiz 1 - Discrete Mathematics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-01-07', 'MATH1168'),
('Introduction to Linear Algebra', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-10', 'MATH1168'),
('Introduction to Numerical Methods', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-20', 'MATH1168'),
('Calculus Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-15', 'MATH1168'),
('Week 3 Lecture - Linear Algebra', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-09', 'MATH1168'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-02-09', 'BIOL3360'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-02-20', 'BIOL3360'),
('Week 9 Lecture - Genetics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-24', 'BIOL3360'),
('Week 6 Tutorial - Petrology', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-18', 'GEOL2309'),
('Week 9 Tutorial - Petrology', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-11', 'GEOL2309'),
('Week 6 Lecture - Geophysics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-29', 'GEOL2309'),
('Week 11 Lecture - Earth History', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-18', 'GEOL1787'),
('Unit 1 Test - Petrology', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-02-16', 'GEOL1787'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-04-28', 'GEOL1787'),
('Quiz 1 - Cell Biology', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-01-15', 'BIOL2895');

