-- ASSIGNMENT INSERTS
INSERT INTO Assignment (a_desc, a_due_date, c_code) VALUES
('Write a field report based on the coastal erosion site visit conducted in Week 4.', '2025-02-06', 'GEOL2504'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-03-16', 'GEOL2504'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-04-01', 'GEOL2504'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-04-09', 'GEOL2504'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-10-21', 'CHEM3337'),
('Complete the reaction mechanism worksheet for organic synthesis. Clearly label all intermediates and arrow-pushing steps.', '2025-12-01', 'CHEM3337'),
('Create an annotated diagram of the DNA replication process, explaining each stage in your own words.', '2025-01-20', 'BIOL3357'),
('Design a controlled experiment to investigate the effect of an environmental variable on natural selection.', '2025-04-12', 'BIOL3357'),
('Critically evaluate two research papers on enzyme kinetics and compare their methodologies and conclusions.', '2025-04-17', 'BIOL3357'),
('Write an essay discussing the role of enzyme kinetics in human disease. Use at least six academic references.', '2025-04-28', 'BIOL3357'),
('Prepare a lab report on the cellular respiration experiment from Week 2. Include your hypothesis, results, and discussion.', '2025-04-29', 'BIOL3357'),
('Complete the problem set on probability. Show all working - answers without justification will not receive credit.', '2025-10-02', 'MATH2229'),
('Prove the following linear algebra theorems using the methods covered in lectures.', '2025-11-19', 'MATH2229'),
('Research a real-world application of wave optics and write a two-page technical summary.', '2025-10-14', 'PHYS2984'),
('Derive the equations of motion for the given projectile motion system from first principles.', '2025-10-30', 'PHYS2984'),
('Write a lab report for the quantum mechanics experiment. Compare your results to the theoretical values and discuss errors.', '2025-11-20', 'PHYS2984'),
('Solve the wave optics problem set. Include free-body diagrams where applicable.', '2025-11-25', 'PHYS2984'),
('Analyse the experimental data provided using quantum mechanics principles and present your conclusions.', '2025-12-05', 'PHYS2984'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-02-15', 'GEOL1864'),
('Research the geologic history of fault systems and write a two-page summary with cited sources.', '2025-03-07', 'GEOL1864'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-03-07', 'GEOL1864'),
('Write a field report based on the river deltas site visit conducted in Week 6.', '2025-03-10', 'GEOL1864'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-03-22', 'GEOL1864'),
('Analyse the grammatical structures in the provided French text and annotate them.', '2025-10-05', 'FRENCH1561'),
('Write a formal letter in French responding to the scenario described in the case study.', '2025-11-27', 'FRENCH1561'),
('Translate the provided passage from English to French, preserving tone and meaning.', '2025-12-08', 'FRENCH1561'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-03-11', 'GEOL3471'),
('Write a field report based on the volcanic activity site visit conducted in Week 5.', '2025-03-21', 'GEOL3471'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-03-25', 'GEOL3471'),
('Research the geologic history of river deltas and write a two-page summary with cited sources.', '2025-04-01', 'GEOL3471'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-04-18', 'GEOL3471'),
('Write a field report based on the river deltas site visit conducted in Week 6.', '2025-11-22', 'GEOL1504'),
('Research the geologic history of fault systems and write a two-page summary with cited sources.', '2025-12-07', 'GEOL1504'),
('Write a formal lab report for the electrochemistry experiment conducted in Week 4. Follow the standard report format.', '2025-10-16', 'CHEM1849'),
('Complete the reaction mechanism worksheet for acid-base reactions. Clearly label all intermediates and arrow-pushing steps.', '2025-10-29', 'CHEM1849'),
('Research and summarise the industrial applications of thermochemistry. Cite at least five peer-reviewed sources.', '2025-11-11', 'CHEM1849'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-11-24', 'CHEM1849'),
('Prepare a safety data summary for the reagents used in the polymer chemistry lab and assess associated hazards.', '2025-12-14', 'CHEM1849'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-03-01', 'GEOL1549'),
('Write a field report based on the coastal erosion site visit conducted in Week 5.', '2025-03-07', 'GEOL1549'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-03-20', 'GEOL1549'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-03-25', 'GEOL1549'),
('Research the geologic history of coastal erosion and write a two-page summary with cited sources.', '2025-04-28', 'GEOL1549'),
('Solve the projectile motion problem set. Include free-body diagrams where applicable.', '2025-03-31', 'PHYS1261'),
('Research a real-world application of quantum mechanics and write a two-page technical summary.', '2025-04-14', 'PHYS1261'),
('Analyse the experimental data provided using thermodynamics principles and present your conclusions.', '2025-04-18', 'PHYS1261'),
('Research a real-world application of wave optics and write a two-page technical summary.', '2025-02-05', 'PHYS1342'),
('Derive the equations of motion for the given projectile motion system from first principles.', '2025-03-21', 'PHYS1342'),
('Analyse the experimental data provided using projectile motion principles and present your conclusions.', '2025-04-15', 'PHYS1342'),
('Write a lab report for the thermodynamics experiment. Compare your results to the theoretical values and discuss errors.', '2025-04-25', 'PHYS1342'),
('Solve the quantum mechanics problem set. Include free-body diagrams where applicable.', '2025-04-27', 'PHYS1342'),
('Complete the problem set on number theory. Show all working - answers without justification will not receive credit.', '2025-02-07', 'MATH3379'),
('Solve the attached numerical methods problem set and verify your answers using any computational tool.', '2025-03-05', 'MATH3379'),
('Prove the following number theory theorems using the methods covered in lectures.', '2025-03-24', 'MATH3379'),
('Model the real-world scenario below using probability techniques and interpret your results.', '2025-03-26', 'MATH3379'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-10-31', 'CHEM3113'),
('Complete the reaction mechanism worksheet for thermochemistry. Clearly label all intermediates and arrow-pushing steps.', '2025-11-22', 'CHEM3113'),
('Critically evaluate two research papers on the immune system and compare their methodologies and conclusions.', '2025-11-07', 'BIOL1934'),
('Create an annotated diagram of the mitosis process, explaining each stage in your own words.', '2025-11-08', 'BIOL1934'),
('Write an essay discussing the role of DNA replication in human disease. Use at least six academic references.', '2025-11-16', 'BIOL1934'),
('Plan a two-week agile sprint for the hospital management project. Include a backlog, sprint goal, and burndown chart.', '2025-10-31', 'SWEN1876'),
('Create a UML class diagram and sequence diagram for the healthcare system described in the case study.', '2025-11-01', 'SWEN1876'),
('Perform a code review of the provided pull request. Submit written feedback addressing style, logic, and security.', '2025-11-28', 'SWEN1876'),
('Complete the problem set on numerical methods. Show all working - answers without justification will not receive credit.', '2025-02-03', 'MATH2330'),
('Model the real-world scenario below using probability techniques and interpret your results.', '2025-02-28', 'MATH2330'),
('Solve the attached probability problem set and verify your answers using any computational tool.', '2025-03-21', 'MATH2330'),
('Write a short essay comparing two approaches to numerical methods, with worked examples for each.', '2025-04-11', 'MATH2330'),
('Plan a two-week agile sprint for the hospital management project. Include a backlog, sprint goal, and burndown chart.', '2025-04-01', 'SWEN2757'),
('Perform a code review of the provided pull request. Submit written feedback addressing style, logic, and security.', '2025-04-11', 'SWEN2757'),
('Create a UML class diagram and sequence diagram for the healthcare system described in the case study.', '2025-04-19', 'SWEN2757'),
('Write a test plan and execute test cases for the provided e-learning application. Submit a defect report.', '2025-04-28', 'SWEN2757'),
('Design a controlled experiment to investigate the effect of an environmental variable on mitosis.', '2025-10-26', 'BIOL2061'),
('Create an annotated diagram of the the immune system process, explaining each stage in your own words.', '2025-11-21', 'BIOL2061'),
('Critically evaluate two research papers on enzyme kinetics and compare their methodologies and conclusions.', '2025-11-30', 'BIOL2061'),
('Write a formal lab report for the polymer chemistry experiment conducted in Week 4. Follow the standard report format.', '2025-04-17', 'CHEM1798'),
('Prepare a safety data summary for the reagents used in the organic synthesis lab and assess associated hazards.', '2025-04-25', 'CHEM1798'),
('Write a formal lab report for the thermochemistry experiment conducted in Week 6. Follow the standard report format.', '2025-02-21', 'CHEM2579'),
('Complete the reaction mechanism worksheet for electrochemistry. Clearly label all intermediates and arrow-pushing steps.', '2025-04-16', 'CHEM2579'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-10-14', 'GEOL1814'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-10-29', 'GEOL1814'),
('Research the geologic history of coastal erosion and write a two-page summary with cited sources.', '2025-11-13', 'GEOL1814'),
('Plan a two-week agile sprint for the ride-sharing project. Include a backlog, sprint goal, and burndown chart.', '2025-10-11', 'SWEN2622'),
('Perform a code review of the provided pull request. Submit written feedback addressing style, logic, and security.', '2025-11-06', 'SWEN2622'),
('Write a test plan and execute test cases for the provided e-learning application. Submit a defect report.', '2025-11-06', 'SWEN2622'),
('Write a lab report for the electromagnetic induction experiment. Compare your results to the theoretical values and discuss errors.', '2025-01-18', 'PHYS3119'),
('Analyse the experimental data provided using projectile motion principles and present your conclusions.', '2025-03-04', 'PHYS3119'),
('Derive the equations of motion for the given simple harmonic motion system from first principles.', '2025-03-11', 'PHYS3119'),
('Solve the quantum mechanics problem set. Include free-body diagrams where applicable.', '2025-03-22', 'PHYS3119'),
('Research a real-world application of electromagnetic induction and write a two-page technical summary.', '2025-04-23', 'PHYS3119'),
('Derive the equations of motion for the given wave optics system from first principles.', '2025-02-18', 'PHYS3287'),
('Analyse the experimental data provided using thermodynamics principles and present your conclusions.', '2025-04-05', 'PHYS3287'),
('Solve the quantum mechanics problem set. Include free-body diagrams where applicable.', '2025-04-25', 'PHYS3287'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-10-20', 'GEOL1856'),
('Write a field report based on the fault systems site visit conducted in Week 3.', '2025-11-14', 'GEOL1856'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-12-03', 'GEOL1856'),
('Prepare a safety data summary for the reagents used in the organic synthesis lab and assess associated hazards.', '2025-02-15', 'CHEM2209'),
('Complete the reaction mechanism worksheet for polymer chemistry. Clearly label all intermediates and arrow-pushing steps.', '2025-03-31', 'CHEM2209'),
('Research and summarise the industrial applications of spectroscopy. Cite at least five peer-reviewed sources.', '2025-04-10', 'CHEM2209'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-04-24', 'CHEM2209'),
('Write a formal lab report for the polymer chemistry experiment conducted in Week 3. Follow the standard report format.', '2025-04-25', 'CHEM2209'),
('Prepare a lab report on the natural selection experiment from Week 5. Include your hypothesis, results, and discussion.', '2025-10-13', 'BIOL1426'),
('Design a controlled experiment to investigate the effect of an environmental variable on DNA replication.', '2025-10-13', 'BIOL1426'),
('Research a real-world application of wave optics and write a two-page technical summary.', '2025-11-05', 'PHYS2946'),
('Analyse the experimental data provided using thermodynamics principles and present your conclusions.', '2025-11-14', 'PHYS2946'),
('Solve the wave optics problem set. Include free-body diagrams where applicable.', '2025-11-26', 'PHYS2946'),
('Derive the equations of motion for the given projectile motion system from first principles.', '2025-11-28', 'PHYS2946'),
('Write a lab report for the thermodynamics experiment. Compare your results to the theoretical values and discuss errors.', '2025-12-05', 'PHYS2946'),
('Research and summarise the industrial applications of acid-base reactions. Cite at least five peer-reviewed sources.', '2025-09-13', 'CHEM2233'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-10-09', 'CHEM2233'),
('Prepare a safety data summary for the reagents used in the acid-base reactions lab and assess associated hazards.', '2025-10-30', 'CHEM2233'),
('Complete the reaction mechanism worksheet for organic synthesis. Clearly label all intermediates and arrow-pushing steps.', '2025-11-28', 'CHEM2233'),
('Complete the reaction mechanism worksheet for spectroscopy. Clearly label all intermediates and arrow-pushing steps.', '2025-10-09', 'CHEM3478'),
('Write a formal lab report for the organic synthesis experiment conducted in Week 6. Follow the standard report format.', '2025-10-31', 'CHEM3478'),
('Research and summarise the industrial applications of organic synthesis. Cite at least five peer-reviewed sources.', '2025-11-24', 'CHEM3478'),
('Prepare a safety data summary for the reagents used in the acid-base reactions lab and assess associated hazards.', '2025-12-03', 'CHEM3478'),
('Write a short paragraph in Mandarin describing technology. Use a minimum of 150 characters.', '2025-03-14', 'CHIN2420'),
('Write a dialogue in Mandarin between two people discussing daily life.', '2025-04-05', 'CHIN2420'),
('Complete the problem set on numerical methods. Show all working - answers without justification will not receive credit.', '2025-03-02', 'MATH2727'),
('Write a short essay comparing two approaches to numerical methods, with worked examples for each.', '2025-03-23', 'MATH2727'),
('Solve the attached probability problem set and verify your answers using any computational tool.', '2025-04-08', 'MATH2727'),
('Prove the following number theory theorems using the methods covered in lectures.', '2025-04-13', 'MATH2727'),
('Prepare a safety data summary for the reagents used in the organic synthesis lab and assess associated hazards.', '2025-11-02', 'CHEM3074'),
('Research and summarise the industrial applications of acid-base reactions. Cite at least five peer-reviewed sources.', '2025-12-13', 'CHEM3074'),
('Prepare a safety data summary for the reagents used in the thermochemistry lab and assess associated hazards.', '2025-10-14', 'CHEM1298'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-11-14', 'CHEM1298'),
('Write a formal lab report for the electrochemistry experiment conducted in Week 8. Follow the standard report format.', '2025-12-14', 'CHEM1298'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-04-09', 'GEOL3352'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-04-23', 'GEOL3352'),
('Design a normalised relational schema for a education system. Include an ER diagram and justification.', '2025-01-26', 'INFO3250'),
('Evaluate two competing data warehouse frameworks and recommend one for a given business scenario.', '2025-04-29', 'INFO3250'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-01-19', 'GEOL3426'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-01-26', 'GEOL3426'),
('Research the geologic history of sedimentary basins and write a two-page summary with cited sources.', '2025-02-20', 'GEOL3426'),
('Write a field report based on the fault systems site visit conducted in Week 3.', '2025-04-04', 'GEOL3426'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-04-05', 'GEOL3426'),
('Research the geologic history of volcanic activity and write a two-page summary with cited sources.', '2025-10-21', 'GEOL2732'),
('Write a field report based on the volcanic activity site visit conducted in Week 6.', '2025-10-23', 'GEOL2732'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-11-09', 'GEOL2732'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-11-12', 'GEOL2732'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-12-10', 'GEOL2732'),
('Prepare a lab report on the the immune system experiment from Week 6. Include your hypothesis, results, and discussion.', '2025-10-11', 'BIOL2089'),
('Write an essay discussing the role of cellular respiration in human disease. Use at least six academic references.', '2025-10-31', 'BIOL2089'),
('Critically evaluate two research papers on cellular respiration and compare their methodologies and conclusions.', '2025-11-11', 'BIOL2089'),
('Write a 500-word essay in Spanish on the topic of the environment. Focus on grammatical accuracy and vocabulary range.', '2025-03-12', 'SPAN2974'),
('Analyse the grammatical structures used in the provided Spanish text and annotate them with explanations.', '2025-03-14', 'SPAN2974'),
('Prepare a written dialogue in Spanish between two characters discussing the environment.', '2025-03-24', 'SPAN2974'),
('Write a field report based on the coastal erosion site visit conducted in Week 4.', '2025-10-27', 'GEOL1139'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-11-19', 'GEOL1139'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-11-24', 'GEOL1139'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-11-30', 'GEOL1139'),
('Research the geologic history of fault systems and write a two-page summary with cited sources.', '2025-12-04', 'GEOL1139'),
('Translate the provided passage from English to Spanish, preserving tone and meaning.', '2025-03-07', 'SPAN3379'),
('Analyse the grammatical structures used in the provided Spanish text and annotate them with explanations.', '2025-04-01', 'SPAN3379'),
('Write a 500-word essay in Spanish on the topic of technology. Focus on grammatical accuracy and vocabulary range.', '2025-04-06', 'SPAN3379'),
('Record a two-minute spoken response in Spanish describing travel. Submit as an audio file.', '2025-04-08', 'SPAN3379'),
('Write a short essay comparing two approaches to calculus, with worked examples for each.', '2025-12-10', 'MATH1282'),
('Complete the problem set on statistics. Show all working - answers without justification will not receive credit.', '2025-12-10', 'MATH1282'),
('Write a short essay comparing two approaches to statistics, with worked examples for each.', '2025-09-25', 'MATH1378'),
('Prove the following number theory theorems using the methods covered in lectures.', '2025-11-30', 'MATH1378'),
('Model the real-world scenario below using linear algebra techniques and interpret your results.', '2025-12-06', 'MATH1378'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-02-22', 'GEOL1934'),
('Write a field report based on the volcanic activity site visit conducted in Week 5.', '2025-02-23', 'GEOL1934'),
('Research the geologic history of river deltas and write a two-page summary with cited sources.', '2025-04-11', 'GEOL1934'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-04-14', 'GEOL1934'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-04-19', 'GEOL1934'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-02-08', 'GEOL3444'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-04-02', 'GEOL3444'),
('Research the geologic history of river deltas and write a two-page summary with cited sources.', '2025-04-11', 'GEOL3444'),
('Write a field report based on the coastal erosion site visit conducted in Week 4.', '2025-04-15', 'GEOL3444'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-04-25', 'GEOL3444'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-02-27', 'GEOL2320'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-03-06', 'GEOL2320'),
('Write a field report based on the river deltas site visit conducted in Week 5.', '2025-03-15', 'GEOL2320'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-03-21', 'GEOL2320'),
('Research the geologic history of river deltas and write a two-page summary with cited sources.', '2025-03-23', 'GEOL2320'),
('Translate the provided English passage into Mandarin Chinese.', '2025-01-31', 'CHIN2864'),
('Write a dialogue in Mandarin between two people discussing technology.', '2025-02-01', 'CHIN2864'),
('Write a short paragraph in Mandarin describing travel. Use a minimum of 150 characters.', '2025-02-24', 'CHIN2864'),
('Record yourself reading the provided Mandarin text aloud. Submit as an audio file.', '2025-03-11', 'CHIN2864'),
('Answer the comprehension questions on the provided Mandarin reading passage.', '2025-03-27', 'CHIN2864'),
('Derive the equations of motion for the given simple harmonic motion system from first principles.', '2025-02-20', 'PHYS2914'),
('Write a lab report for the wave optics experiment. Compare your results to the theoretical values and discuss errors.', '2025-03-06', 'PHYS2914'),
('Analyse the experimental data provided using projectile motion principles and present your conclusions.', '2025-03-19', 'PHYS2914'),
('Research a real-world application of quantum mechanics and write a two-page technical summary.', '2025-03-24', 'PHYS2914'),
('Solve the thermodynamics problem set. Include free-body diagrams where applicable.', '2025-04-19', 'PHYS2914'),
('Complete the reaction mechanism worksheet for acid-base reactions. Clearly label all intermediates and arrow-pushing steps.', '2025-03-05', 'CHEM1642'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-03-14', 'CHEM1642'),
('Research and summarise the industrial applications of polymer chemistry. Cite at least five peer-reviewed sources.', '2025-04-28', 'CHEM1642'),
('Write a formal lab report for the organic synthesis experiment conducted in Week 7. Follow the standard report format.', '2025-04-29', 'CHEM1642'),
('Analyse the experimental data provided using projectile motion principles and present your conclusions.', '2025-03-05', 'PHYS2587'),
('Derive the equations of motion for the given projectile motion system from first principles.', '2025-04-16', 'PHYS2587'),
('Solve the simple harmonic motion problem set. Include free-body diagrams where applicable.', '2025-04-20', 'PHYS2587'),
('Write a lab report for the quantum mechanics experiment. Compare your results to the theoretical values and discuss errors.', '2025-04-28', 'PHYS2587'),
('Research and summarise the industrial applications of thermochemistry. Cite at least five peer-reviewed sources.', '2025-11-16', 'CHEM2769'),
('Write a formal lab report for the electrochemistry experiment conducted in Week 8. Follow the standard report format.', '2025-11-28', 'CHEM2769'),
('Prepare a safety data summary for the reagents used in the acid-base reactions lab and assess associated hazards.', '2025-12-14', 'CHEM2769'),
('Prepare a safety data summary for the reagents used in the organic synthesis lab and assess associated hazards.', '2025-09-19', 'CHEM3177'),
('Complete the reaction mechanism worksheet for spectroscopy. Clearly label all intermediates and arrow-pushing steps.', '2025-10-23', 'CHEM3177'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-11-17', 'CHEM3177'),
('Research and summarise the industrial applications of thermochemistry. Cite at least five peer-reviewed sources.', '2025-11-25', 'CHEM3177'),
('Prove the following numerical methods theorems using the methods covered in lectures.', '2025-10-10', 'MATH2982'),
('Complete the problem set on discrete mathematics. Show all working - answers without justification will not receive credit.', '2025-11-27', 'MATH2982'),
('Model the real-world scenario below using probability techniques and interpret your results.', '2025-11-30', 'MATH2982'),
('Solve the attached statistics problem set and verify your answers using any computational tool.', '2025-12-10', 'MATH2982'),
('Write a formal lab report for the acid-base reactions experiment conducted in Week 7. Follow the standard report format.', '2025-03-04', 'CHEM1790'),
('Complete the reaction mechanism worksheet for polymer chemistry. Clearly label all intermediates and arrow-pushing steps.', '2025-04-07', 'CHEM1790'),
('Research and summarise the industrial applications of polymer chemistry. Cite at least five peer-reviewed sources.', '2025-04-08', 'CHEM1790'),
('Prepare a safety data summary for the reagents used in the polymer chemistry lab and assess associated hazards.', '2025-04-13', 'CHEM1790'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-04-22', 'CHEM1790'),
('Complete the problem set on statistics. Show all working - answers without justification will not receive credit.', '2025-03-06', 'MATH1412'),
('Prove the following linear algebra theorems using the methods covered in lectures.', '2025-03-18', 'MATH1412'),
('Research and summarise the industrial applications of thermochemistry. Cite at least five peer-reviewed sources.', '2025-02-25', 'CHEM2782'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-04-03', 'CHEM2782'),
('Complete the reaction mechanism worksheet for polymer chemistry. Clearly label all intermediates and arrow-pushing steps.', '2025-04-06', 'CHEM2782'),
('Prepare a safety data summary for the reagents used in the acid-base reactions lab and assess associated hazards.', '2025-04-14', 'CHEM2782'),
('Prove the following numerical methods theorems using the methods covered in lectures.', '2025-02-04', 'MATH1665'),
('Model the real-world scenario below using calculus techniques and interpret your results.', '2025-03-15', 'MATH1665'),
('Write a short essay comparing two approaches to linear algebra, with worked examples for each.', '2025-03-23', 'MATH1665'),
('Complete the problem set on statistics. Show all working - answers without justification will not receive credit.', '2025-04-13', 'MATH1665'),
('Solve the attached discrete mathematics problem set and verify your answers using any computational tool.', '2025-04-21', 'MATH1665'),
('Write a 500-word essay in Spanish on the topic of technology. Focus on grammatical accuracy and vocabulary range.', '2025-09-23', 'SPAN1499'),
('Record a two-minute spoken response in Spanish describing travel. Submit as an audio file.', '2025-11-01', 'SPAN1499'),
('Analyse the experimental data provided using thermodynamics principles and present your conclusions.', '2025-11-07', 'PHYS1934'),
('Derive the equations of motion for the given wave optics system from first principles.', '2025-11-17', 'PHYS1934'),
('Research a real-world application of electromagnetic induction and write a two-page technical summary.', '2025-11-20', 'PHYS1934'),
('Write a lab report for the projectile motion experiment. Compare your results to the theoretical values and discuss errors.', '2025-11-28', 'PHYS1934'),
('Write a field report based on the sedimentary basins site visit conducted in Week 4.', '2025-01-28', 'GEOL3417'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-02-11', 'GEOL3417'),
('Research the geologic history of fault systems and write a two-page summary with cited sources.', '2025-03-09', 'GEOL3417'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-04-01', 'GEOL3417'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-04-22', 'GEOL3417'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-04-06', 'CHEM3404'),
('Complete the reaction mechanism worksheet for acid-base reactions. Clearly label all intermediates and arrow-pushing steps.', '2025-04-20', 'CHEM3404'),
('Research and summarise the industrial applications of polymer chemistry. Cite at least five peer-reviewed sources.', '2025-04-27', 'CHEM3404'),
('Write a short essay comparing two approaches to linear algebra, with worked examples for each.', '2025-11-12', 'MATH2272'),
('Model the real-world scenario below using discrete mathematics techniques and interpret your results.', '2025-12-03', 'MATH2272'),
('Complete the problem set on statistics. Show all working - answers without justification will not receive credit.', '2025-12-10', 'MATH2272'),
('Prove the following probability theorems using the methods covered in lectures.', '2025-12-12', 'MATH2272'),
('Write a short essay comparing two approaches to calculus, with worked examples for each.', '2025-10-11', 'MATH1877'),
('Complete the problem set on number theory. Show all working - answers without justification will not receive credit.', '2025-10-20', 'MATH1877'),
('Model the real-world scenario below using statistics techniques and interpret your results.', '2025-11-18', 'MATH1877'),
('Write a formal letter in French responding to the scenario described in the case study.', '2025-11-13', 'FRENCH1048'),
('Write a 500-word essay in French on the topic of French culture. Pay attention to agreement and verb conjugation.', '2025-12-10', 'FRENCH1048'),
('Design a controlled experiment to investigate the effect of an environmental variable on natural selection.', '2025-03-30', 'BIOL1005'),
('Prepare a lab report on the DNA replication experiment from Week 4. Include your hypothesis, results, and discussion.', '2025-03-31', 'BIOL1005'),
('Write an essay discussing the role of the immune system in human disease. Use at least six academic references.', '2025-03-31', 'BIOL1005'),
('Create an annotated diagram of the mitosis process, explaining each stage in your own words.', '2025-04-05', 'BIOL1005'),
('Critically evaluate two research papers on DNA replication and compare their methodologies and conclusions.', '2025-04-23', 'BIOL1005'),
('Complete the problem set on number theory. Show all working - answers without justification will not receive credit.', '2025-01-31', 'MATH3199'),
('Solve the attached statistics problem set and verify your answers using any computational tool.', '2025-03-06', 'MATH3199'),
('Model the real-world scenario below using number theory techniques and interpret your results.', '2025-03-26', 'MATH3199'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-04-16', 'GEOL3172'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-04-20', 'GEOL3172'),
('Record a spoken response in Japanese describing travel. Submit as an audio file.', '2025-03-29', 'JAPA3218'),
('Write a short essay in Japanese on the topic of technology. Minimum 200 characters.', '2025-04-12', 'JAPA3218'),
('Complete the grammar exercises for the structures covered in Weeks 5-7.', '2025-04-22', 'JAPA3218'),
('Solve the quantum mechanics problem set. Include free-body diagrams where applicable.', '2025-10-10', 'PHYS3446'),
('Analyse the experimental data provided using thermodynamics principles and present your conclusions.', '2025-11-02', 'PHYS3446'),
('Research a real-world application of projectile motion and write a two-page technical summary.', '2025-11-05', 'PHYS3446'),
('Derive the equations of motion for the given simple harmonic motion system from first principles.', '2025-11-25', 'PHYS3446'),
('Write a lab report for the electromagnetic induction experiment. Compare your results to the theoretical values and discuss errors.', '2025-12-08', 'PHYS3446'),
('Design a normalised relational schema for a healthcare system. Include an ER diagram and justification.', '2025-01-31', 'INFO2600'),
('Evaluate two competing data warehouse frameworks and recommend one for a given business scenario.', '2025-02-28', 'INFO2600'),
('Develop a business intelligence report for a banking company using the tools discussed in class.', '2025-04-06', 'INFO2600'),
('Using the provided dataset, perform exploratory data analysis and present your findings in a dashboard.', '2025-04-29', 'INFO2600'),
('Model the real-world scenario below using discrete mathematics techniques and interpret your results.', '2025-10-05', 'MATH1606'),
('Prove the following calculus theorems using the methods covered in lectures.', '2025-11-28', 'MATH1606'),
('Solve the attached numerical methods problem set and verify your answers using any computational tool.', '2025-11-30', 'MATH1606'),
('Write a short essay comparing two approaches to calculus, with worked examples for each.', '2025-12-13', 'MATH1606'),
('Produce a full requirements specification document for a hospital management system, including use cases and user stories.', '2025-01-29', 'SWEN1392'),
('Perform a code review of the provided pull request. Submit written feedback addressing style, logic, and security.', '2025-02-16', 'SWEN1392'),
('Plan a two-week agile sprint for the e-learning project. Include a backlog, sprint goal, and burndown chart.', '2025-04-10', 'SWEN1392'),
('Write a test plan and execute test cases for the provided ride-sharing application. Submit a defect report.', '2025-04-28', 'SWEN1392'),
('Write a formal lab report for the spectroscopy experiment conducted in Week 4. Follow the standard report format.', '2025-01-22', 'CHEM1646'),
('Prepare a safety data summary for the reagents used in the electrochemistry lab and assess associated hazards.', '2025-02-11', 'CHEM1646'),
('Complete the reaction mechanism worksheet for electrochemistry. Clearly label all intermediates and arrow-pushing steps.', '2025-03-20', 'CHEM1646'),
('Research and summarise the industrial applications of polymer chemistry. Cite at least five peer-reviewed sources.', '2025-04-19', 'CHEM1646'),
('Build a REST API with Go that performs full CRUD operations on a networking dataset.', '2025-10-11', 'COMP3469'),
('Analyse the time and space complexity of the provided pathfinding algorithm. Write a report justifying your findings.', '2025-11-16', 'COMP3469'),
('Implement a graph in JavaScript. Your solution must handle edge cases and include unit tests.', '2025-11-19', 'COMP3469'),
('Design and build a microservice application using Java. Submit source code and a README.', '2025-12-04', 'COMP3469'),
('Refactor the given legacy codebase to follow SOLID principles. Document every change made.', '2025-12-10', 'COMP3469'),
('Record yourself reading the provided Mandarin text aloud. Submit as an audio file.', '2025-01-18', 'CHIN1386'),
('Answer the comprehension questions on the provided Mandarin reading passage.', '2025-01-27', 'CHIN1386'),
('Write a dialogue in Mandarin between two people discussing family.', '2025-03-14', 'CHIN1386'),
('Write a short paragraph in Mandarin describing family. Use a minimum of 150 characters.', '2025-04-16', 'CHIN1386'),
('Translate the provided English passage into Mandarin Chinese.', '2025-04-20', 'CHIN1386'),
('Create an annotated diagram of the enzyme kinetics process, explaining each stage in your own words.', '2025-02-17', 'BIOL2262'),
('Write an essay discussing the role of enzyme kinetics in human disease. Use at least six academic references.', '2025-02-20', 'BIOL2262'),
('Critically evaluate two research papers on DNA replication and compare their methodologies and conclusions.', '2025-03-14', 'BIOL2262'),
('Design a controlled experiment to investigate the effect of an environmental variable on enzyme kinetics.', '2025-03-29', 'BIOL2262'),
('Prepare a lab report on the enzyme kinetics experiment from Week 5. Include your hypothesis, results, and discussion.', '2025-04-03', 'BIOL2262'),
('Write a dialogue in Japanese between two characters meeting for the first time.', '2025-02-26', 'JAPA2073'),
('Translate the provided passage from English into Japanese.', '2025-03-04', 'JAPA2073'),
('Write a formal letter in French responding to the scenario described in the case study.', '2025-09-30', 'FRENCH1592'),
('Analyse the grammatical structures in the provided French text and annotate them.', '2025-10-15', 'FRENCH1592'),
('Translate the provided passage from English to French, preserving tone and meaning.', '2025-11-20', 'FRENCH1592'),
('Write a 500-word essay in French on the topic of the environment. Pay attention to agreement and verb conjugation.', '2025-11-27', 'FRENCH1592'),
('Record a two-minute spoken response in French on the environment. Submit as an audio file.', '2025-12-14', 'FRENCH1592'),
('Complete the problem set on number theory. Show all working - answers without justification will not receive credit.', '2025-10-08', 'MATH3259'),
('Model the real-world scenario below using statistics techniques and interpret your results.', '2025-10-19', 'MATH3259'),
('Write a short essay comparing two approaches to statistics, with worked examples for each.', '2025-12-05', 'MATH3259'),
('Prove the following discrete mathematics theorems using the methods covered in lectures.', '2025-12-12', 'MATH3259'),
('Perform a code review of the provided pull request. Submit written feedback addressing style, logic, and security.', '2025-03-03', 'SWEN1361'),
('Create a UML class diagram and sequence diagram for the healthcare system described in the case study.', '2025-04-01', 'SWEN1361'),
('Plan a two-week agile sprint for the hospital management project. Include a backlog, sprint goal, and burndown chart.', '2025-04-27', 'SWEN1361'),
('Evaluate two competing cloud storage frameworks and recommend one for a given business scenario.', '2025-03-02', 'INFO3407'),
('Design a normalised relational schema for a logistics system. Include an ER diagram and justification.', '2025-03-20', 'INFO3407'),
('Develop a business intelligence report for a logistics company using the tools discussed in class.', '2025-04-18', 'INFO3407'),
('Write a report analysing the information security risks facing a education organisation.', '2025-04-22', 'INFO3407'),
('Research the geologic history of fault systems and write a two-page summary with cited sources.', '2025-02-12', 'GEOL2128'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-03-14', 'GEOL2128'),
('Write a field report based on the river deltas site visit conducted in Week 4.', '2025-04-07', 'GEOL2128'),
('Analyse the experimental data provided using simple harmonic motion principles and present your conclusions.', '2025-02-18', 'PHYS1380'),
('Research a real-world application of thermodynamics and write a two-page technical summary.', '2025-03-14', 'PHYS1380'),
('Solve the electromagnetic induction problem set. Include free-body diagrams where applicable.', '2025-03-28', 'PHYS1380'),
('Write a lab report for the projectile motion experiment. Compare your results to the theoretical values and discuss errors.', '2025-10-13', 'PHYS2672'),
('Derive the equations of motion for the given electromagnetic induction system from first principles.', '2025-12-10', 'PHYS2672'),
('Research a real-world application of simple harmonic motion and write a two-page technical summary.', '2025-12-14', 'PHYS2672'),
('Translate the provided passage from English to Spanish, preserving tone and meaning.', '2025-03-24', 'SPAN1315'),
('Write a 500-word essay in Spanish on the topic of the environment. Focus on grammatical accuracy and vocabulary range.', '2025-03-27', 'SPAN1315'),
('Analyse the grammatical structures used in the provided Spanish text and annotate them with explanations.', '2025-03-27', 'SPAN1315'),
('Write an essay discussing the role of natural selection in human disease. Use at least six academic references.', '2025-09-25', 'BIOL2863'),
('Design a controlled experiment to investigate the effect of an environmental variable on enzyme kinetics.', '2025-09-27', 'BIOL2863'),
('Create an annotated diagram of the natural selection process, explaining each stage in your own words.', '2025-10-29', 'BIOL2863'),
('Prepare a lab report on the enzyme kinetics experiment from Week 4. Include your hypothesis, results, and discussion.', '2025-10-30', 'BIOL2863'),
('Critically evaluate two research papers on DNA replication and compare their methodologies and conclusions.', '2025-12-14', 'BIOL2863'),
('Solve the attached statistics problem set and verify your answers using any computational tool.', '2025-10-20', 'MATH1103'),
('Prove the following calculus theorems using the methods covered in lectures.', '2025-11-02', 'MATH1103'),
('Write a short essay comparing two approaches to linear algebra, with worked examples for each.', '2025-12-09', 'MATH1103'),
('Write a lab report for the simple harmonic motion experiment. Compare your results to the theoretical values and discuss errors.', '2025-03-25', 'PHYS1823'),
('Analyse the experimental data provided using thermodynamics principles and present your conclusions.', '2025-03-28', 'PHYS1823'),
('Derive the equations of motion for the given projectile motion system from first principles.', '2025-04-14', 'PHYS1823'),
('Using the provided dataset, perform exploratory data analysis and present your findings in a dashboard.', '2025-03-25', 'INFO1814'),
('Develop a business intelligence report for a banking company using the tools discussed in class.', '2025-04-10', 'INFO1814'),
('Design a normalised relational schema for a banking system. Include an ER diagram and justification.', '2025-04-13', 'INFO1814'),
('Analyse the experimental data provided using projectile motion principles and present your conclusions.', '2025-02-05', 'PHYS2710'),
('Research a real-world application of simple harmonic motion and write a two-page technical summary.', '2025-03-18', 'PHYS2710'),
('Derive the equations of motion for the given projectile motion system from first principles.', '2025-04-03', 'PHYS2710'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-01-29', 'GEOL1699'),
('Research the geologic history of fault systems and write a two-page summary with cited sources.', '2025-03-29', 'GEOL1699'),
('Write a field report based on the sedimentary basins site visit conducted in Week 5.', '2025-04-09', 'GEOL1699'),
('Critically evaluate two research papers on enzyme kinetics and compare their methodologies and conclusions.', '2025-02-19', 'BIOL3375'),
('Prepare a lab report on the cellular respiration experiment from Week 6. Include your hypothesis, results, and discussion.', '2025-02-28', 'BIOL3375'),
('Create an annotated diagram of the the immune system process, explaining each stage in your own words.', '2025-03-27', 'BIOL3375'),
('Design a controlled experiment to investigate the effect of an environmental variable on DNA replication.', '2025-04-20', 'BIOL3375'),
('Write a lab report for the electromagnetic induction experiment. Compare your results to the theoretical values and discuss errors.', '2025-11-11', 'PHYS3244'),
('Analyse the experimental data provided using quantum mechanics principles and present your conclusions.', '2025-11-20', 'PHYS3244'),
('Solve the quantum mechanics problem set. Include free-body diagrams where applicable.', '2025-12-05', 'PHYS3244'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-11-24', 'GEOL1120'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-12-05', 'GEOL1120'),
('Answer the comprehension questions on the provided Mandarin reading passage.', '2025-03-27', 'CHIN1586'),
('Translate the provided English passage into Mandarin Chinese.', '2025-04-13', 'CHIN1586'),
('Record yourself reading the provided Mandarin text aloud. Submit as an audio file.', '2025-04-29', 'CHIN1586'),
('Model the real-world scenario below using number theory techniques and interpret your results.', '2025-03-01', 'MATH1636'),
('Solve the attached linear algebra problem set and verify your answers using any computational tool.', '2025-03-24', 'MATH1636'),
('Prove the following probability theorems using the methods covered in lectures.', '2025-04-13', 'MATH1636'),
('Write a short essay comparing two approaches to linear algebra, with worked examples for each.', '2025-04-22', 'MATH1636'),
('Complete the problem set on calculus. Show all working - answers without justification will not receive credit.', '2025-04-22', 'MATH1636'),
('Translate the provided passage from English into Japanese.', '2025-10-23', 'JAPA1899'),
('Write a dialogue in Japanese between two characters meeting for the first time.', '2025-11-24', 'JAPA1899'),
('Complete the grammar exercises for the structures covered in Weeks 4-6.', '2025-12-03', 'JAPA1899'),
('Write a short essay in Japanese on the topic of daily life. Minimum 200 characters.', '2025-12-13', 'JAPA1899'),
('Complete the problem set on numerical methods. Show all working - answers without justification will not receive credit.', '2025-10-11', 'MATH1521'),
('Write a short essay comparing two approaches to statistics, with worked examples for each.', '2025-10-25', 'MATH1521'),
('Solve the attached statistics problem set and verify your answers using any computational tool.', '2025-11-03', 'MATH1521'),
('Model the real-world scenario below using numerical methods techniques and interpret your results.', '2025-11-24', 'MATH1521'),
('Write a short essay comparing two approaches to statistics, with worked examples for each.', '2025-02-17', 'MATH2424'),
('Complete the problem set on statistics. Show all working - answers without justification will not receive credit.', '2025-03-13', 'MATH2424'),
('Prove the following probability theorems using the methods covered in lectures.', '2025-03-13', 'MATH2424'),
('Model the real-world scenario below using number theory techniques and interpret your results.', '2025-03-15', 'MATH2424'),
('Solve the attached number theory problem set and verify your answers using any computational tool.', '2025-04-01', 'MATH2424'),
('Analyse the experimental data provided using quantum mechanics principles and present your conclusions.', '2025-04-06', 'PHYS1478'),
('Write a lab report for the simple harmonic motion experiment. Compare your results to the theoretical values and discuss errors.', '2025-04-07', 'PHYS1478'),
('Solve the electromagnetic induction problem set. Include free-body diagrams where applicable.', '2025-04-13', 'PHYS1478'),
('Complete the grammar exercises for the structures covered in Weeks 4-5.', '2025-03-12', 'JAPA2042'),
('Write a dialogue in Japanese between two characters meeting for the first time.', '2025-04-05', 'JAPA2042'),
('Research the geologic history of coastal erosion and write a two-page summary with cited sources.', '2025-10-06', 'GEOL3335'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-11-12', 'GEOL3335'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-11-26', 'GEOL3335'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-02-02', 'GEOL1925'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-02-11', 'GEOL1925'),
('Research the geologic history of sedimentary basins and write a two-page summary with cited sources.', '2025-03-16', 'GEOL1925'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-03-16', 'GEOL1925'),
('Write a field report based on the sedimentary basins site visit conducted in Week 5.', '2025-03-27', 'GEOL1925'),
('Write a 500-word essay in French on the topic of technology. Pay attention to agreement and verb conjugation.', '2025-10-11', 'FRENCH1716'),
('Translate the provided passage from English to French, preserving tone and meaning.', '2025-11-20', 'FRENCH1716'),
('Prove the following numerical methods theorems using the methods covered in lectures.', '2025-10-07', 'MATH1002'),
('Complete the problem set on linear algebra. Show all working - answers without justification will not receive credit.', '2025-12-12', 'MATH1002'),
('Create an annotated diagram of the natural selection process, explaining each stage in your own words.', '2025-03-28', 'BIOL1115'),
('Prepare a lab report on the cellular respiration experiment from Week 5. Include your hypothesis, results, and discussion.', '2025-04-21', 'BIOL1115'),
('Design a controlled experiment to investigate the effect of an environmental variable on enzyme kinetics.', '2025-04-26', 'BIOL1115'),
('Create an annotated diagram of the natural selection process, explaining each stage in your own words.', '2025-10-11', 'BIOL2430'),
('Write an essay discussing the role of mitosis in human disease. Use at least six academic references.', '2025-10-27', 'BIOL2430'),
('Prepare a lab report on the cellular respiration experiment from Week 6. Include your hypothesis, results, and discussion.', '2025-11-22', 'BIOL2430'),
('Critically evaluate two research papers on enzyme kinetics and compare their methodologies and conclusions.', '2025-11-24', 'BIOL2430'),
('Design a controlled experiment to investigate the effect of an environmental variable on mitosis.', '2025-12-11', 'BIOL2430'),
('Translate the provided passage from English to French, preserving tone and meaning.', '2025-09-30', 'FRENCH1521'),
('Write a 500-word essay in French on the topic of technology. Pay attention to agreement and verb conjugation.', '2025-10-26', 'FRENCH1521'),
('Record a two-minute spoken response in French on travel. Submit as an audio file.', '2025-11-30', 'FRENCH1521'),
('Model the real-world scenario below using probability techniques and interpret your results.', '2025-02-18', 'MATH1045'),
('Write a short essay comparing two approaches to discrete mathematics, with worked examples for each.', '2025-02-19', 'MATH1045'),
('Complete the problem set on numerical methods. Show all working - answers without justification will not receive credit.', '2025-03-17', 'MATH1045'),
('Solve the attached statistics problem set and verify your answers using any computational tool.', '2025-03-30', 'MATH1045'),
('Prove the following discrete mathematics theorems using the methods covered in lectures.', '2025-04-29', 'MATH1045'),
('Write a 500-word essay in Spanish on the topic of family life. Focus on grammatical accuracy and vocabulary range.', '2025-09-30', 'SPAN2407'),
('Prepare a written dialogue in Spanish between two characters discussing culture.', '2025-10-28', 'SPAN2407'),
('Write a dialogue in Mandarin between two people discussing technology.', '2025-10-10', 'CHIN1620'),
('Answer the comprehension questions on the provided Mandarin reading passage.', '2025-11-24', 'CHIN1620'),
('Write a short paragraph in Mandarin describing travel. Use a minimum of 150 characters.', '2025-11-29', 'CHIN1620'),
('Write a formal lab report for the electrochemistry experiment conducted in Week 8. Follow the standard report format.', '2025-10-13', 'CHEM1373'),
('Research and summarise the industrial applications of thermochemistry. Cite at least five peer-reviewed sources.', '2025-11-16', 'CHEM1373'),
('Prepare a safety data summary for the reagents used in the spectroscopy lab and assess associated hazards.', '2025-12-03', 'CHEM1373'),
('Write a short essay comparing two approaches to calculus, with worked examples for each.', '2025-01-28', 'MATH1980'),
('Complete the problem set on discrete mathematics. Show all working - answers without justification will not receive credit.', '2025-02-11', 'MATH1980'),
('Analyse the experimental data provided using projectile motion principles and present your conclusions.', '2025-03-17', 'PHYS2664'),
('Derive the equations of motion for the given electromagnetic induction system from first principles.', '2025-04-24', 'PHYS2664'),
('Solve the quantum mechanics problem set. Include free-body diagrams where applicable.', '2025-04-25', 'PHYS2664'),
('Prove the following calculus theorems using the methods covered in lectures.', '2025-09-05', 'MATH3437'),
('Complete the problem set on probability. Show all working - answers without justification will not receive credit.', '2025-10-01', 'MATH3437'),
('Solve the attached calculus problem set and verify your answers using any computational tool.', '2025-11-04', 'MATH3437'),
('Model the real-world scenario below using statistics techniques and interpret your results.', '2025-12-11', 'MATH3437'),
('Complete the problem set on number theory. Show all working - answers without justification will not receive credit.', '2025-04-13', 'MATH2923'),
('Solve the attached discrete mathematics problem set and verify your answers using any computational tool.', '2025-04-20', 'MATH2923'),
('Create a UML class diagram and sequence diagram for the fintech system described in the case study.', '2025-10-27', 'SWEN1995'),
('Perform a code review of the provided pull request. Submit written feedback addressing style, logic, and security.', '2025-11-06', 'SWEN1995'),
('Plan a two-week agile sprint for the ride-sharing project. Include a backlog, sprint goal, and burndown chart.', '2025-11-24', 'SWEN1995'),
('Produce a full requirements specification document for a e-learning system, including use cases and user stories.', '2025-12-11', 'SWEN1995'),
('Write a test plan and execute test cases for the provided e-learning application. Submit a defect report.', '2025-12-13', 'SWEN1995'),
('Record yourself reading the provided Mandarin text aloud. Submit as an audio file.', '2025-02-02', 'CHIN1801'),
('Write a short paragraph in Mandarin describing technology. Use a minimum of 150 characters.', '2025-02-26', 'CHIN1801'),
('Write a dialogue in Mandarin between two people discussing family.', '2025-03-22', 'CHIN1801'),
('Translate the provided English passage into Mandarin Chinese.', '2025-03-31', 'CHIN1801'),
('Prove the following discrete mathematics theorems using the methods covered in lectures.', '2025-03-05', 'MATH2518'),
('Complete the problem set on statistics. Show all working - answers without justification will not receive credit.', '2025-03-28', 'MATH2518'),
('Write a dialogue in Japanese between two characters meeting for the first time.', '2025-10-15', 'JAPA2245'),
('Translate the provided passage from English into Japanese.', '2025-11-05', 'JAPA2245'),
('Write a short essay in Japanese on the topic of travel. Minimum 200 characters.', '2025-11-09', 'JAPA2245'),
('Record a spoken response in Japanese describing daily life. Submit as an audio file.', '2025-11-14', 'JAPA2245'),
('Write a field report based on the volcanic activity site visit conducted in Week 6.', '2025-01-25', 'GEOL3334'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-03-17', 'GEOL3334'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-03-29', 'GEOL3334'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-04-17', 'GEOL3334'),
('Research the geologic history of fault systems and write a two-page summary with cited sources.', '2025-04-27', 'GEOL3334'),
('Derive the equations of motion for the given quantum mechanics system from first principles.', '2025-10-01', 'PHYS1767'),
('Solve the projectile motion problem set. Include free-body diagrams where applicable.', '2025-10-11', 'PHYS1767'),
('Write a lab report for the electromagnetic induction experiment. Compare your results to the theoretical values and discuss errors.', '2025-10-26', 'PHYS1767'),
('Research a real-world application of projectile motion and write a two-page technical summary.', '2025-10-26', 'PHYS1767'),
('Write a formal lab report for the thermochemistry experiment conducted in Week 6. Follow the standard report format.', '2025-09-11', 'CHEM3043'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-09-30', 'CHEM3043'),
('Prepare a safety data summary for the reagents used in the organic synthesis lab and assess associated hazards.', '2025-10-10', 'CHEM3043'),
('Complete the reaction mechanism worksheet for electrochemistry. Clearly label all intermediates and arrow-pushing steps.', '2025-11-08', 'CHEM3043'),
('Research and summarise the industrial applications of acid-base reactions. Cite at least five peer-reviewed sources.', '2025-12-02', 'CHEM3043'),
('Critically evaluate two research papers on enzyme kinetics and compare their methodologies and conclusions.', '2025-11-04', 'BIOL2311'),
('Write an essay discussing the role of natural selection in human disease. Use at least six academic references.', '2025-11-10', 'BIOL2311'),
('Design a controlled experiment to investigate the effect of an environmental variable on the immune system.', '2025-11-12', 'BIOL2311'),
('Prepare a lab report on the mitosis experiment from Week 5. Include your hypothesis, results, and discussion.', '2025-11-23', 'BIOL2311'),
('Create an annotated diagram of the the immune system process, explaining each stage in your own words.', '2025-12-03', 'BIOL2311'),
('Analyse the grammatical structures in the provided French text and annotate them.', '2025-10-07', 'FRENCH2645'),
('Write a 500-word essay in French on the topic of travel. Pay attention to agreement and verb conjugation.', '2025-11-14', 'FRENCH2645'),
('Record a two-minute spoken response in French on travel. Submit as an audio file.', '2025-11-23', 'FRENCH2645'),
('Complete the reaction mechanism worksheet for acid-base reactions. Clearly label all intermediates and arrow-pushing steps.', '2025-02-03', 'CHEM3273'),
('Research and summarise the industrial applications of acid-base reactions. Cite at least five peer-reviewed sources.', '2025-04-07', 'CHEM3273'),
('Complete the problem set on linear algebra. Show all working - answers without justification will not receive credit.', '2025-02-13', 'MATH2963'),
('Solve the attached number theory problem set and verify your answers using any computational tool.', '2025-03-02', 'MATH2963'),
('Prove the following statistics theorems using the methods covered in lectures.', '2025-03-20', 'MATH2963'),
('Model the real-world scenario below using discrete mathematics techniques and interpret your results.', '2025-04-26', 'MATH2963'),
('Write a short essay comparing two approaches to linear algebra, with worked examples for each.', '2025-04-29', 'MATH2963'),
('Complete the reaction mechanism worksheet for organic synthesis. Clearly label all intermediates and arrow-pushing steps.', '2025-03-29', 'CHEM2403'),
('Research and summarise the industrial applications of acid-base reactions. Cite at least five peer-reviewed sources.', '2025-04-01', 'CHEM2403'),
('Prepare a safety data summary for the reagents used in the polymer chemistry lab and assess associated hazards.', '2025-04-15', 'CHEM2403'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-04-29', 'CHEM2403'),
('Write an essay discussing the role of natural selection in human disease. Use at least six academic references.', '2025-10-12', 'BIOL1499'),
('Critically evaluate two research papers on mitosis and compare their methodologies and conclusions.', '2025-10-16', 'BIOL1499'),
('Design a controlled experiment to investigate the effect of an environmental variable on cellular respiration.', '2025-11-02', 'BIOL1499'),
('Prepare a lab report on the cellular respiration experiment from Week 5. Include your hypothesis, results, and discussion.', '2025-11-08', 'BIOL1499'),
('Create an annotated diagram of the the immune system process, explaining each stage in your own words.', '2025-11-18', 'BIOL1499'),
('Translate the provided passage from English to Spanish, preserving tone and meaning.', '2025-10-13', 'SPAN2935'),
('Record a two-minute spoken response in Spanish describing technology. Submit as an audio file.', '2025-11-20', 'SPAN2935'),
('Analyse the grammatical structures used in the provided Spanish text and annotate them with explanations.', '2025-12-04', 'SPAN2935'),
('Write a 500-word essay in Spanish on the topic of travel. Focus on grammatical accuracy and vocabulary range.', '2025-12-09', 'SPAN2935'),
('Complete the reaction mechanism worksheet for thermochemistry. Clearly label all intermediates and arrow-pushing steps.', '2025-03-01', 'CHEM2397'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-03-06', 'CHEM2397'),
('Prepare a safety data summary for the reagents used in the organic synthesis lab and assess associated hazards.', '2025-03-28', 'CHEM2397'),
('Write a formal lab report for the electrochemistry experiment conducted in Week 3. Follow the standard report format.', '2025-11-11', 'CHEM2730'),
('Research and summarise the industrial applications of thermochemistry. Cite at least five peer-reviewed sources.', '2025-11-24', 'CHEM2730'),
('Prepare a safety data summary for the reagents used in the thermochemistry lab and assess associated hazards.', '2025-12-05', 'CHEM2730'),
('Complete the reaction mechanism worksheet for acid-base reactions. Clearly label all intermediates and arrow-pushing steps.', '2025-12-06', 'CHEM2730'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-12-10', 'CHEM2730'),
('Research and summarise the industrial applications of spectroscopy. Cite at least five peer-reviewed sources.', '2025-02-23', 'CHEM2025'),
('Write a formal lab report for the electrochemistry experiment conducted in Week 5. Follow the standard report format.', '2025-03-25', 'CHEM2025'),
('Critically evaluate two research papers on natural selection and compare their methodologies and conclusions.', '2025-01-25', 'BIOL1061'),
('Create an annotated diagram of the cellular respiration process, explaining each stage in your own words.', '2025-04-16', 'BIOL1061'),
('Using the provided dataset, perform exploratory data analysis and present your findings in a dashboard.', '2025-10-05', 'INFO1671'),
('Design a normalised relational schema for a education system. Include an ER diagram and justification.', '2025-11-24', 'INFO1671'),
('Write a report analysing the information security risks facing a logistics organisation.', '2025-12-03', 'INFO1671'),
('Evaluate two competing ERP frameworks and recommend one for a given business scenario.', '2025-12-06', 'INFO1671'),
('Write a lab report for the thermodynamics experiment. Compare your results to the theoretical values and discuss errors.', '2025-10-24', 'PHYS2913'),
('Derive the equations of motion for the given simple harmonic motion system from first principles.', '2025-11-17', 'PHYS2913'),
('Critically evaluate two research papers on mitosis and compare their methodologies and conclusions.', '2025-02-23', 'BIOL2796');

INSERT INTO Assignment (a_desc, a_due_date, c_code) VALUES
('Create an annotated diagram of the DNA replication process, explaining each stage in your own words.', '2025-02-24', 'BIOL2796'),
('Write an essay discussing the role of enzyme kinetics in human disease. Use at least six academic references.', '2025-02-26', 'BIOL2796'),
('Prepare a lab report on the natural selection experiment from Week 3. Include your hypothesis, results, and discussion.', '2025-03-09', 'BIOL2796'),
('Critically evaluate two research papers on DNA replication and compare their methodologies and conclusions.', '2025-12-11', 'BIOL2870'),
('Prepare a lab report on the natural selection experiment from Week 3. Include your hypothesis, results, and discussion.', '2025-12-11', 'BIOL2870'),
('Write a short essay in Japanese on the topic of technology. Minimum 200 characters.', '2025-11-01', 'JAPA3464'),
('Complete the grammar exercises for the structures covered in Weeks 4-6.', '2025-12-01', 'JAPA3464'),
('Translate the provided passage from English into Japanese.', '2025-12-04', 'JAPA3464'),
('Plan a two-week agile sprint for the mobile banking project. Include a backlog, sprint goal, and burndown chart.', '2025-03-26', 'SWEN2407'),
('Write a test plan and execute test cases for the provided mobile banking application. Submit a defect report.', '2025-04-02', 'SWEN2407'),
('Create a UML class diagram and sequence diagram for the healthcare system described in the case study.', '2025-04-14', 'SWEN2407'),
('Model the real-world scenario below using number theory techniques and interpret your results.', '2025-10-17', 'MATH2177'),
('Write a short essay comparing two approaches to calculus, with worked examples for each.', '2025-12-10', 'MATH2177'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-10-06', 'GEOL2192'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-11-02', 'GEOL2192'),
('Build a REST API with Go that performs full CRUD operations on a memory management dataset.', '2025-04-02', 'COMP2005'),
('Analyse the time and space complexity of the provided compression algorithm. Write a report justifying your findings.', '2025-04-15', 'COMP2005'),
('Implement a linked list in Go. Your solution must handle edge cases and include unit tests.', '2025-04-21', 'COMP2005'),
('Refactor the given legacy codebase to follow SOLID principles. Document every change made.', '2025-04-22', 'COMP2005'),
('Write a dialogue in Japanese between two characters meeting for the first time.', '2025-12-02', 'JAPA1518'),
('Record a spoken response in Japanese describing daily life. Submit as an audio file.', '2025-12-03', 'JAPA1518'),
('Solve the electromagnetic induction problem set. Include free-body diagrams where applicable.', '2025-02-07', 'PHYS2170'),
('Research a real-world application of thermodynamics and write a two-page technical summary.', '2025-04-05', 'PHYS2170'),
('Research and summarise the industrial applications of electrochemistry. Cite at least five peer-reviewed sources.', '2025-02-26', 'CHEM1671'),
('Prepare a safety data summary for the reagents used in the electrochemistry lab and assess associated hazards.', '2025-04-01', 'CHEM1671'),
('Write a formal lab report for the spectroscopy experiment conducted in Week 3. Follow the standard report format.', '2025-04-13', 'CHEM1671'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-04-21', 'CHEM1671'),
('Complete the reaction mechanism worksheet for acid-base reactions. Clearly label all intermediates and arrow-pushing steps.', '2025-04-27', 'CHEM1671'),
('Write a short paragraph in Mandarin describing food. Use a minimum of 150 characters.', '2025-11-17', 'CHIN3361'),
('Record yourself reading the provided Mandarin text aloud. Submit as an audio file.', '2025-12-13', 'CHIN3361'),
('Write an essay discussing the role of cellular respiration in human disease. Use at least six academic references.', '2025-11-22', 'BIOL3204'),
('Critically evaluate two research papers on the immune system and compare their methodologies and conclusions.', '2025-12-08', 'BIOL3204'),
('Prepare a lab report on the mitosis experiment from Week 5. Include your hypothesis, results, and discussion.', '2025-12-11', 'BIOL3204'),
('Write a formal lab report for the polymer chemistry experiment conducted in Week 4. Follow the standard report format.', '2025-10-07', 'CHEM1070'),
('Research and summarise the industrial applications of organic synthesis. Cite at least five peer-reviewed sources.', '2025-10-30', 'CHEM1070'),
('Solve the projectile motion problem set. Include free-body diagrams where applicable.', '2025-03-01', 'PHYS1272'),
('Research a real-world application of wave optics and write a two-page technical summary.', '2025-03-02', 'PHYS1272'),
('Derive the equations of motion for the given projectile motion system from first principles.', '2025-03-10', 'PHYS1272'),
('Write a lab report for the quantum mechanics experiment. Compare your results to the theoretical values and discuss errors.', '2025-04-24', 'PHYS1272'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-01-17', 'CHEM2100'),
('Research and summarise the industrial applications of polymer chemistry. Cite at least five peer-reviewed sources.', '2025-03-16', 'CHEM2100'),
('Complete the reaction mechanism worksheet for thermochemistry. Clearly label all intermediates and arrow-pushing steps.', '2025-03-21', 'CHEM2100'),
('Prepare a safety data summary for the reagents used in the thermochemistry lab and assess associated hazards.', '2025-04-06', 'CHEM2100'),
('Create a UML class diagram and sequence diagram for the healthcare system described in the case study.', '2025-01-20', 'SWEN2261'),
('Write a test plan and execute test cases for the provided hospital management application. Submit a defect report.', '2025-02-22', 'SWEN2261'),
('Record a two-minute spoken response in Spanish describing travel. Submit as an audio file.', '2025-11-16', 'SPAN2038'),
('Analyse the grammatical structures used in the provided Spanish text and annotate them with explanations.', '2025-11-17', 'SPAN2038'),
('Prepare a written dialogue in Spanish between two characters discussing family life.', '2025-11-29', 'SPAN2038'),
('Write an essay discussing the role of the immune system in human disease. Use at least six academic references.', '2025-02-24', 'BIOL1186'),
('Design a controlled experiment to investigate the effect of an environmental variable on natural selection.', '2025-02-26', 'BIOL1186'),
('Critically evaluate two research papers on cellular respiration and compare their methodologies and conclusions.', '2025-04-12', 'BIOL1186'),
('Prepare a lab report on the cellular respiration experiment from Week 6. Include your hypothesis, results, and discussion.', '2025-04-26', 'BIOL1186'),
('Model the real-world scenario below using numerical methods techniques and interpret your results.', '2025-03-26', 'MATH3063'),
('Complete the problem set on numerical methods. Show all working - answers without justification will not receive credit.', '2025-03-30', 'MATH3063'),
('Model the real-world scenario below using calculus techniques and interpret your results.', '2025-01-30', 'MATH1403'),
('Prove the following calculus theorems using the methods covered in lectures.', '2025-03-05', 'MATH1403'),
('Solve the attached discrete mathematics problem set and verify your answers using any computational tool.', '2025-03-12', 'MATH1403'),
('Write a short essay comparing two approaches to calculus, with worked examples for each.', '2025-04-06', 'MATH1403'),
('Complete the problem set on probability. Show all working - answers without justification will not receive credit.', '2025-04-19', 'MATH1403'),
('Prepare a safety data summary for the reagents used in the polymer chemistry lab and assess associated hazards.', '2025-10-22', 'CHEM2657'),
('Write a formal lab report for the acid-base reactions experiment conducted in Week 8. Follow the standard report format.', '2025-11-30', 'CHEM2657'),
('Complete the reaction mechanism worksheet for thermochemistry. Clearly label all intermediates and arrow-pushing steps.', '2025-12-01', 'CHEM2657'),
('Research and summarise the industrial applications of polymer chemistry. Cite at least five peer-reviewed sources.', '2025-12-06', 'CHEM2657'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-12-11', 'CHEM2657'),
('Prepare a lab report on the mitosis experiment from Week 2. Include your hypothesis, results, and discussion.', '2025-11-06', 'BIOL2872'),
('Design a controlled experiment to investigate the effect of an environmental variable on natural selection.', '2025-11-17', 'BIOL2872'),
('Create an annotated diagram of the DNA replication process, explaining each stage in your own words.', '2025-12-07', 'BIOL2872'),
('Write an essay discussing the role of mitosis in human disease. Use at least six academic references.', '2025-12-07', 'BIOL2872'),
('Critically evaluate two research papers on enzyme kinetics and compare their methodologies and conclusions.', '2025-01-17', 'BIOL3135'),
('Write an essay discussing the role of the immune system in human disease. Use at least six academic references.', '2025-02-18', 'BIOL3135'),
('Create an annotated diagram of the enzyme kinetics process, explaining each stage in your own words.', '2025-03-21', 'BIOL3135'),
('Design a controlled experiment to investigate the effect of an environmental variable on cellular respiration.', '2025-04-11', 'BIOL3135'),
('Prepare a lab report on the DNA replication experiment from Week 6. Include your hypothesis, results, and discussion.', '2025-04-25', 'BIOL3135'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-01-17', 'GEOL2250'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-03-18', 'GEOL2250'),
('Write a field report based on the sedimentary basins site visit conducted in Week 3.', '2025-03-24', 'GEOL2250'),
('Research the geologic history of volcanic activity and write a two-page summary with cited sources.', '2025-03-30', 'GEOL2250'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-04-22', 'GEOL2250'),
('Implement a linked list in Go. Your solution must handle edge cases and include unit tests.', '2025-11-11', 'COMP3003'),
('Refactor the given legacy codebase to follow SOLID principles. Document every change made.', '2025-12-03', 'COMP3003'),
('Design and build a web application using Java. Submit source code and a README.', '2025-12-04', 'COMP3003'),
('Write an essay discussing the role of DNA replication in human disease. Use at least six academic references.', '2025-02-28', 'BIOL1384'),
('Critically evaluate two research papers on natural selection and compare their methodologies and conclusions.', '2025-03-02', 'BIOL1384'),
('Complete the reaction mechanism worksheet for thermochemistry. Clearly label all intermediates and arrow-pushing steps.', '2025-09-22', 'CHEM2459'),
('Prepare a safety data summary for the reagents used in the acid-base reactions lab and assess associated hazards.', '2025-10-12', 'CHEM2459'),
('Write a formal lab report for the organic synthesis experiment conducted in Week 8. Follow the standard report format.', '2025-11-13', 'CHEM2459'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-11-21', 'CHEM2459'),
('Research the geologic history of fault systems and write a two-page summary with cited sources.', '2025-03-04', 'GEOL1547'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-03-28', 'GEOL1547'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-04-18', 'GEOL1547'),
('Write a formal letter in French responding to the scenario described in the case study.', '2025-11-03', 'FRENCH1121'),
('Translate the provided passage from English to French, preserving tone and meaning.', '2025-11-14', 'FRENCH1121'),
('Write a 500-word essay in French on the topic of the environment. Pay attention to agreement and verb conjugation.', '2025-11-24', 'FRENCH1121'),
('Record a two-minute spoken response in French on French culture. Submit as an audio file.', '2025-11-26', 'FRENCH1121'),
('Analyse the grammatical structures in the provided French text and annotate them.', '2025-12-04', 'FRENCH1121'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-09-15', 'GEOL1317'),
('Research the geologic history of sedimentary basins and write a two-page summary with cited sources.', '2025-09-29', 'GEOL1317'),
('Write a field report based on the fault systems site visit conducted in Week 5.', '2025-11-23', 'GEOL1317'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-12-08', 'GEOL1317'),
('Solve the projectile motion problem set. Include free-body diagrams where applicable.', '2025-04-06', 'PHYS2774'),
('Analyse the experimental data provided using projectile motion principles and present your conclusions.', '2025-04-10', 'PHYS2774'),
('Write a lab report for the thermodynamics experiment. Compare your results to the theoretical values and discuss errors.', '2025-04-12', 'PHYS2774'),
('Model the real-world scenario below using linear algebra techniques and interpret your results.', '2025-10-03', 'MATH3444'),
('Complete the problem set on statistics. Show all working - answers without justification will not receive credit.', '2025-11-14', 'MATH3444'),
('Solve the attached calculus problem set and verify your answers using any computational tool.', '2025-12-02', 'MATH3444'),
('Write a formal lab report for the acid-base reactions experiment conducted in Week 5. Follow the standard report format.', '2025-10-07', 'CHEM2523'),
('Complete the reaction mechanism worksheet for acid-base reactions. Clearly label all intermediates and arrow-pushing steps.', '2025-11-07', 'CHEM2523'),
('Research and summarise the industrial applications of polymer chemistry. Cite at least five peer-reviewed sources.', '2025-12-08', 'CHEM2523'),
('Write a formal lab report for the polymer chemistry experiment conducted in Week 7. Follow the standard report format.', '2025-10-13', 'CHEM1470'),
('Prepare a safety data summary for the reagents used in the spectroscopy lab and assess associated hazards.', '2025-10-24', 'CHEM1470'),
('Research and summarise the industrial applications of thermochemistry. Cite at least five peer-reviewed sources.', '2025-11-02', 'CHEM1470'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-12-01', 'CHEM1470'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-09-08', 'GEOL2242'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-10-16', 'GEOL2242'),
('Research the geologic history of fault systems and write a two-page summary with cited sources.', '2025-10-25', 'GEOL2242'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-11-23', 'GEOL2242'),
('Write a field report based on the fault systems site visit conducted in Week 6.', '2025-12-13', 'GEOL2242'),
('Plan a two-week agile sprint for the mobile banking project. Include a backlog, sprint goal, and burndown chart.', '2025-11-17', 'SWEN1016'),
('Write a test plan and execute test cases for the provided ride-sharing application. Submit a defect report.', '2025-11-26', 'SWEN1016'),
('Create a UML class diagram and sequence diagram for the healthcare system described in the case study.', '2025-12-11', 'SWEN1016'),
('Perform a code review of the provided pull request. Submit written feedback addressing style, logic, and security.', '2025-12-11', 'SWEN1016'),
('Using the provided dataset, perform exploratory data analysis and present your findings in a dashboard.', '2025-10-27', 'INFO3305'),
('Write a report analysing the information security risks facing a retail organisation.', '2025-11-11', 'INFO3305'),
('Develop a business intelligence report for a banking company using the tools discussed in class.', '2025-12-10', 'INFO3305'),
('Design a normalised relational schema for a education system. Include an ER diagram and justification.', '2025-12-14', 'INFO3305'),
('Research a real-world application of projectile motion and write a two-page technical summary.', '2025-09-14', 'PHYS3378'),
('Derive the equations of motion for the given electromagnetic induction system from first principles.', '2025-10-31', 'PHYS3378'),
('Analyse the experimental data provided using simple harmonic motion principles and present your conclusions.', '2025-11-29', 'PHYS3378'),
('Write a lab report for the electromagnetic induction experiment. Compare your results to the theoretical values and discuss errors.', '2025-12-01', 'PHYS3378'),
('Analyse the time and space complexity of the provided compression algorithm. Write a report justifying your findings.', '2025-10-29', 'COMP2059'),
('Refactor the given legacy codebase to follow SOLID principles. Document every change made.', '2025-11-03', 'COMP2059'),
('Implement a stack in Java. Your solution must handle edge cases and include unit tests.', '2025-12-13', 'COMP2059'),
('Design and build a web application using Java. Submit source code and a README.', '2025-09-24', 'COMP2868'),
('Build a REST API with C++ that performs full CRUD operations on a memory management dataset.', '2025-10-16', 'COMP2868'),
('Implement a hash map in Java. Your solution must handle edge cases and include unit tests.', '2025-11-20', 'COMP2868'),
('Analyse the time and space complexity of the provided searching algorithm. Write a report justifying your findings.', '2025-11-23', 'COMP2868'),
('Critically evaluate two research papers on DNA replication and compare their methodologies and conclusions.', '2025-03-07', 'BIOL2206'),
('Write an essay discussing the role of enzyme kinetics in human disease. Use at least six academic references.', '2025-03-09', 'BIOL2206'),
('Prepare a lab report on the cellular respiration experiment from Week 6. Include your hypothesis, results, and discussion.', '2025-04-02', 'BIOL2206'),
('Create an annotated diagram of the DNA replication process, explaining each stage in your own words.', '2025-04-03', 'BIOL2206'),
('Prepare a safety data summary for the reagents used in the electrochemistry lab and assess associated hazards.', '2025-01-12', 'CHEM1185'),
('Write a formal lab report for the polymer chemistry experiment conducted in Week 7. Follow the standard report format.', '2025-02-05', 'CHEM1185'),
('Research and summarise the industrial applications of polymer chemistry. Cite at least five peer-reviewed sources.', '2025-04-20', 'CHEM1185'),
('Complete the reaction mechanism worksheet for spectroscopy. Clearly label all intermediates and arrow-pushing steps.', '2025-10-07', 'CHEM2642'),
('Write a formal lab report for the electrochemistry experiment conducted in Week 4. Follow the standard report format.', '2025-10-29', 'CHEM2642'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-12-01', 'CHEM2642'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-01-28', 'GEOL1787'),
('Write a field report based on the river deltas site visit conducted in Week 3.', '2025-03-12', 'GEOL1787'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-03-13', 'GEOL1787'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-04-16', 'GEOL1787'),
('Research the geologic history of river deltas and write a two-page summary with cited sources.', '2025-04-27', 'GEOL1787'),
('Solve the attached calculus problem set and verify your answers using any computational tool.', '2025-11-10', 'MATH1004'),
('Write a short essay comparing two approaches to linear algebra, with worked examples for each.', '2025-11-26', 'MATH1004'),
('Model the real-world scenario below using statistics techniques and interpret your results.', '2025-12-07', 'MATH1004'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-10-28', 'GEOL1379'),
('Write a field report based on the volcanic activity site visit conducted in Week 6.', '2025-11-20', 'GEOL1379'),
('Research the geologic history of fault systems and write a two-page summary with cited sources.', '2025-12-12', 'GEOL1379'),
('Write a short essay comparing two approaches to number theory, with worked examples for each.', '2025-01-27', 'MATH1102'),
('Complete the problem set on probability. Show all working - answers without justification will not receive credit.', '2025-02-18', 'MATH1102'),
('Model the real-world scenario below using probability techniques and interpret your results.', '2025-03-04', 'MATH1102'),
('Prove the following linear algebra theorems using the methods covered in lectures.', '2025-04-15', 'MATH1102'),
('Complete the reaction mechanism worksheet for organic synthesis. Clearly label all intermediates and arrow-pushing steps.', '2025-02-16', 'CHEM3213'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-04-04', 'CHEM3213'),
('Write an essay discussing the role of cellular respiration in human disease. Use at least six academic references.', '2025-01-19', 'BIOL2226'),
('Critically evaluate two research papers on cellular respiration and compare their methodologies and conclusions.', '2025-03-13', 'BIOL2226'),
('Design a controlled experiment to investigate the effect of an environmental variable on mitosis.', '2025-03-18', 'BIOL2226'),
('Prepare a lab report on the the immune system experiment from Week 2. Include your hypothesis, results, and discussion.', '2025-04-05', 'BIOL2226'),
('Create an annotated diagram of the cellular respiration process, explaining each stage in your own words.', '2025-04-22', 'BIOL2226'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-10-04', 'GEOL2064'),
('Research the geologic history of river deltas and write a two-page summary with cited sources.', '2025-11-22', 'GEOL2064'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-12-09', 'GEOL2064'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-12-11', 'GEOL2064'),
('Write a field report based on the river deltas site visit conducted in Week 4.', '2025-12-13', 'GEOL2064'),
('Record yourself reading the provided Mandarin text aloud. Submit as an audio file.', '2025-01-26', 'CHIN1591'),
('Translate the provided English passage into Mandarin Chinese.', '2025-03-18', 'CHIN1591'),
('Write a dialogue in Mandarin between two people discussing family.', '2025-03-26', 'CHIN1591'),
('Answer the comprehension questions on the provided Mandarin reading passage.', '2025-04-11', 'CHIN1591'),
('Write a short paragraph in Mandarin describing daily life. Use a minimum of 150 characters.', '2025-04-25', 'CHIN1591'),
('Write a lab report for the wave optics experiment. Compare your results to the theoretical values and discuss errors.', '2025-04-04', 'PHYS2431'),
('Analyse the experimental data provided using quantum mechanics principles and present your conclusions.', '2025-04-27', 'PHYS2431'),
('Solve the quantum mechanics problem set. Include free-body diagrams where applicable.', '2025-04-29', 'PHYS2431'),
('Write a field report based on the sedimentary basins site visit conducted in Week 3.', '2025-09-13', 'GEOL2330'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-12-11', 'GEOL2330'),
('Using the provided dataset, perform exploratory data analysis and present your findings in a dashboard.', '2025-09-17', 'INFO1921'),
('Design a normalised relational schema for a banking system. Include an ER diagram and justification.', '2025-10-20', 'INFO1921'),
('Develop a business intelligence report for a healthcare company using the tools discussed in class.', '2025-11-24', 'INFO1921'),
('Evaluate two competing data warehouse frameworks and recommend one for a given business scenario.', '2025-12-14', 'INFO1921'),
('Solve the wave optics problem set. Include free-body diagrams where applicable.', '2025-03-30', 'PHYS2318'),
('Analyse the experimental data provided using projectile motion principles and present your conclusions.', '2025-04-07', 'PHYS2318'),
('Derive the equations of motion for the given quantum mechanics system from first principles.', '2025-04-28', 'PHYS2318'),
('Prove the following linear algebra theorems using the methods covered in lectures.', '2025-10-02', 'MATH1718'),
('Complete the problem set on discrete mathematics. Show all working - answers without justification will not receive credit.', '2025-11-02', 'MATH1718'),
('Model the real-world scenario below using number theory techniques and interpret your results.', '2025-11-27', 'MATH1718'),
('Solve the attached numerical methods problem set and verify your answers using any computational tool.', '2025-12-07', 'MATH1718'),
('Research a real-world application of wave optics and write a two-page technical summary.', '2025-10-04', 'PHYS1253'),
('Derive the equations of motion for the given wave optics system from first principles.', '2025-10-24', 'PHYS1253'),
('Write a lab report for the wave optics experiment. Compare your results to the theoretical values and discuss errors.', '2025-11-01', 'PHYS1253'),
('Analyse the experimental data provided using wave optics principles and present your conclusions.', '2025-12-11', 'PHYS1253'),
('Create an annotated diagram of the cellular respiration process, explaining each stage in your own words.', '2025-02-01', 'BIOL1249'),
('Write an essay discussing the role of natural selection in human disease. Use at least six academic references.', '2025-02-02', 'BIOL1249'),
('Prepare a lab report on the enzyme kinetics experiment from Week 6. Include your hypothesis, results, and discussion.', '2025-03-13', 'BIOL1249'),
('Design a controlled experiment to investigate the effect of an environmental variable on natural selection.', '2025-03-26', 'BIOL1249'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-10-29', 'GEOL3326'),
('Research the geologic history of river deltas and write a two-page summary with cited sources.', '2025-10-31', 'GEOL3326'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-11-26', 'GEOL3326'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-11-28', 'GEOL3326'),
('Write a field report based on the fault systems site visit conducted in Week 4.', '2025-12-08', 'GEOL3326'),
('Write a formal lab report for the electrochemistry experiment conducted in Week 8. Follow the standard report format.', '2025-10-13', 'CHEM2815'),
('Research and summarise the industrial applications of acid-base reactions. Cite at least five peer-reviewed sources.', '2025-11-19', 'CHEM2815'),
('Complete the reaction mechanism worksheet for polymer chemistry. Clearly label all intermediates and arrow-pushing steps.', '2025-11-20', 'CHEM2815'),
('Prepare a safety data summary for the reagents used in the polymer chemistry lab and assess associated hazards.', '2025-11-28', 'CHEM2815'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-12-03', 'CHEM2815'),
('Write a short essay comparing two approaches to linear algebra, with worked examples for each.', '2025-02-23', 'MATH3120'),
('Prove the following number theory theorems using the methods covered in lectures.', '2025-03-23', 'MATH3120'),
('Solve the attached probability problem set and verify your answers using any computational tool.', '2025-03-24', 'MATH3120'),
('Complete the problem set on linear algebra. Show all working - answers without justification will not receive credit.', '2025-04-15', 'MATH3120'),
('Model the real-world scenario below using calculus techniques and interpret your results.', '2025-04-18', 'MATH3120');

