-- CALENDAR EVENT INSERTS
INSERT INTO CalendarEvent (event_name, details, event_date, c_code) VALUES
('Introduction to Geophysics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-07', 'GEOL2504'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-02-10', 'GEOL2504'),
('Week 5 Lecture - Earth History', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-09', 'GEOL2504'),
('Geophysics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-20', 'GEOL2504'),
('Thermochemistry: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-22', 'CHEM3337'),
('Week 8 Lecture - Organic Chemistry', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-20', 'CHEM3337'),
('Introduction to Analytical Methods', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-30', 'CHEM3337'),
('Introduction to Ecology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-14', 'BIOL3357'),
('Tutorial: Human Biology Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-26', 'BIOL3357'),
('Week 2 Lecture - Human Biology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-06', 'BIOL3357'),
('Week 4 Lecture - Genetics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-17', 'BIOL3357'),
('Week 13 Tutorial - Human Biology', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-29', 'BIOL3357'),
('Probability Practical', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-09-07', 'MATH2229'),
('Discrete Mathematics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-13', 'MATH2229'),
('Week 6 Lecture - Linear Algebra', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-06', 'MATH2229'),
('Week 5 Lecture - Statistics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-22', 'MATH2229'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-09-14', 'PHYS2984'),
('Tutorial: Wave Optics Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-20', 'PHYS2984'),
('Wave Optics Practical', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-10-24', 'PHYS2984'),
('Wave Optics Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-26', 'PHYS2984'),
('Introduction to Petrology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-07', 'GEOL1864'),
('Introduction to Petrology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-20', 'GEOL1864'),
('Tutorial: Structural Geology Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-01', 'GEOL1864'),
('Petrology Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-09', 'GEOL1864'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-10-29', 'FRENCH1561'),
('Week 6 Lecture - Earth History', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-04', 'GEOL3471'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-02-24', 'GEOL3471'),
('Quiz 1 - Earth History', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-09-13', 'GEOL1504'),
('Mineralogy: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-04', 'GEOL1504'),
('Mineralogy: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-30', 'GEOL1504'),
('Geophysics Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-12-12', 'GEOL1504'),
('Spectroscopy Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-13', 'CHEM1849'),
('Lecturer Office Hours - Week 5', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-11-03', 'CHEM1849'),
('Thermochemistry In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-11-07', 'CHEM1849'),
('Earth History Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-19', 'GEOL1549'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-03-23', 'GEOL1549'),
('Earth History: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-29', 'GEOL1549'),
('Quiz 1 - Thermodynamics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-01-07', 'PHYS1261'),
('Introduction to Quantum Physics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-23', 'PHYS1261'),
('Quantum Physics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-05', 'PHYS1261'),
('Lecturer Office Hours - Week 11', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-03-24', 'PHYS1261'),
('Introduction to Quantum Physics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-19', 'PHYS1342'),
('Calculus: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-16', 'MATH3379'),
('Probability Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-15', 'MATH3379'),
('Unit 1 Test - Analytical Methods', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-10-22', 'CHEM3113'),
('Organic Chemistry: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-23', 'CHEM3113'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-11-03', 'CHEM3113'),
('Week 11 Lecture - Spectroscopy', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-25', 'CHEM3113'),
('Quiz 1 - Microbiology', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-09-27', 'BIOL1934'),
('Human Biology: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-02', 'BIOL1934'),
('Week 12 Lecture - Microbiology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-17', 'BIOL1934'),
('Week 11 Tutorial - Genetics', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-22', 'BIOL1934'),
('Chapter Quiz: Agile Methods', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-09-12', 'SWEN1876'),
('Lecturer Office Hours - Week 2', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-09-24', 'SWEN1876'),
('Requirements Engineering: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-07', 'SWEN1876'),
('Week 8 Tutorial - Linear Algebra', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-06', 'MATH2330'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-02-02', 'MATH2330'),
('Week 6 Lecture - Linear Algebra', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-05', 'MATH2330'),
('Unit 1 Test - Numerical Methods', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-02-05', 'MATH2330'),
('Week 12 Lecture - Calculus', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-25', 'MATH2330'),
('Agile Methods: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-07', 'SWEN2757'),
('Software Design In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-03-21', 'SWEN2757'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-04-03', 'SWEN2757'),
('Requirements Engineering In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-04-10', 'SWEN2757'),
('Introduction to Software Design', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-13', 'SWEN2757'),
('Week 9 Lecture - Microbiology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-03', 'BIOL2061'),
('Week 5 Lecture - Cell Biology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-17', 'BIOL2061'),
('Lecturer Office Hours - Week 10', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-10-21', 'BIOL2061'),
('Tutorial: Cell Biology Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-12-05', 'BIOL2061'),
('Week 4 Lecture - Inorganic Chemistry', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-05', 'CHEM1798'),
('Introduction to Analytical Methods', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-16', 'CHEM1798'),
('Introduction to Analytical Methods', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-13', 'CHEM1798'),
('Week 1 Lecture - Inorganic Chemistry', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-20', 'CHEM2579'),
('Week 11 Lecture - Spectroscopy', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-02', 'CHEM2579'),
('Analytical Methods Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-11', 'CHEM2579'),
('Analytical Methods: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-15', 'CHEM2579'),
('Organic Chemistry Practical', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-02-15', 'CHEM2579'),
('Lab Session 1 - Mineralogy', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-10-04', 'GEOL1814'),
('Petrology: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-08', 'GEOL1814'),
('Tutorial: Earth History Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-29', 'GEOL1814'),
('Earth History: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-02', 'GEOL1814'),
('Introduction to Petrology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-25', 'GEOL1814'),
('Tutorial: Agile Methods Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-20', 'SWEN2622'),
('Introduction to Software Testing', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-08', 'SWEN2622'),
('Week 8 Lecture - Software Testing', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-14', 'SWEN2622'),
('Chapter Quiz: Software Design', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-10-27', 'SWEN2622'),
('Lecturer Office Hours - Week 9', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-01-18', 'PHYS3119'),
('Electromagnetism: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-08', 'PHYS3119'),
('Tutorial: Thermodynamics Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-04', 'PHYS3287'),
('Introduction to Wave Optics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-21', 'PHYS3287'),
('Electromagnetism: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-25', 'PHYS3287'),
('Week 6 Lecture - Mechanics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-19', 'PHYS3287'),
('Petrology Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-11', 'GEOL1856'),
('Week 5 Tutorial - Inorganic Chemistry', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-29', 'CHEM2209'),
('Week 10 Lecture - Spectroscopy', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-14', 'CHEM2209'),
('Analytical Methods In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-04-03', 'CHEM2209'),
('Ecology: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-25', 'BIOL1426'),
('Week 12 Tutorial - Microbiology', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-12-10', 'BIOL1426'),
('Mechanics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-17', 'PHYS2946'),
('Lab Session 1 - Thermodynamics', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-11-12', 'PHYS2946'),
('Week 2 Lecture - Wave Optics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-26', 'PHYS2946'),
('Tutorial: Spectroscopy Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-02', 'CHEM2233'),
('Spectroscopy: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-23', 'CHEM2233'),
('Introduction to Organic Chemistry', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-08', 'CHEM2233'),
('Spectroscopy: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-10', 'CHEM2233'),
('Tutorial: Spectroscopy Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-30', 'CHEM3478'),
('Spectroscopy Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-27', 'CHEM3478'),
('Reading Comprehension Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-17', 'CHIN2420'),
('Week 4 Tutorial - Linear Algebra', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-18', 'MATH2727'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-10-29', 'CHEM3074'),
('Quiz 2 - Thermochemistry', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-11-16', 'CHEM3074'),
('Thermochemistry In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-12-01', 'CHEM3074'),
('Inorganic Chemistry Practical', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-09-18', 'CHEM1298'),
('Tutorial: Organic Chemistry Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-13', 'CHEM1298'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-12-01', 'CHEM1298'),
('Week 13 Lecture - Inorganic Chemistry', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-11', 'CHEM1298'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-02-21', 'GEOL3352'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-03-31', 'GEOL3352'),
('Tutorial: Geophysics Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-03', 'GEOL3352'),
('Lecturer Office Hours - Week 9', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-01-09', 'INFO3250'),
('Data Analytics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-15', 'INFO3250'),
('Week 9 Lecture - Information Security', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-01', 'INFO3250'),
('Introduction to Information Security', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-31', 'INFO3250'),
('Lecturer Office Hours - Week 7', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-04-27', 'INFO3250'),
('Week 2 Lecture - Structural Geology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-04', 'GEOL3426'),
('Earth History Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-11', 'GEOL2732'),
('Week 8 Lecture - Cell Biology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-05', 'BIOL2089'),
('Introduction to Human Biology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-13', 'BIOL2089'),
('Ecology: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-05', 'BIOL2089'),
('Week 2 Lecture - Ecology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-29', 'BIOL2089'),
('Week 8 Tutorial - Spanish Grammar', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-27', 'SPAN2974'),
('Oral Expression: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-27', 'SPAN2974'),
('Week 10 Tutorial - Oral Expression', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-01', 'SPAN2974'),
('Quiz 1 - Spanish Grammar', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-04-15', 'SPAN2974'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-04-21', 'SPAN2974'),
('Tutorial: Earth History Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-01', 'GEOL1139'),
('Week 4 Tutorial - Mineralogy', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-13', 'GEOL1139'),
('Introduction to Verb Conjugation', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-18', 'SPAN3379'),
('Numerical Methods: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-02', 'MATH1282'),
('Quiz 1 - Calculus', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-12-12', 'MATH1282'),
('Week 2 Tutorial - Numerical Methods', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-11', 'MATH1378'),
('Lecturer Office Hours - Week 12', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-01-12', 'GEOL1934'),
('Introduction to Petrology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-07', 'GEOL1934'),
('Earth History Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-05', 'GEOL1934'),
('Introduction to Structural Geology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-06', 'GEOL3444'),
('Introduction to Mineralogy', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-28', 'GEOL3444'),
('Petrology Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-13', 'GEOL3444'),
('Introduction to Earth History', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-27', 'GEOL3444'),
('Week 7 Tutorial - Mineralogy', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-27', 'GEOL2320'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-03-01', 'CHIN2864'),
('Tutorial: Oral Expression Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-16', 'CHIN2864'),
('Week 8 Lecture - Quantum Physics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-05', 'PHYS2914'),
('Lecturer Office Hours - Week 9', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-02-14', 'PHYS2914'),
('Wave Optics Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-01', 'PHYS2914'),
('Mechanics Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-29', 'PHYS2914'),
('Tutorial: Analytical Methods Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-06', 'CHEM1642'),
('Analytical Methods In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-02-01', 'CHEM1642'),
('Chapter Quiz: Thermochemistry', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-03-08', 'CHEM1642'),
('Introduction to Organic Chemistry', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-12', 'CHEM1642'),
('Thermochemistry: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-29', 'CHEM1642'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-01-12', 'PHYS2587'),
('Week 9 Lecture - Mechanics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-18', 'PHYS2587'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-01-25', 'PHYS2587'),
('Electromagnetism: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-26', 'PHYS2587'),
('Quantum Physics In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-02-02', 'PHYS2587'),
('Lecturer Office Hours - Week 5', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-09-12', 'CHEM2769'),
('Chapter Quiz: Thermochemistry', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-09-23', 'CHEM2769'),
('Introduction to Inorganic Chemistry', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-17', 'CHEM2769'),
('Week 11 Lecture - Spectroscopy', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-09', 'CHEM3177'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-09-12', 'CHEM3177'),
('Lab Session 1 - Thermochemistry', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-10-16', 'CHEM3177'),
('Week 1 Lecture - Inorganic Chemistry', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-27', 'CHEM3177'),
('Probability Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-03', 'MATH2982'),
('Linear Algebra In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-09-22', 'MATH2982'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-10-13', 'MATH2982'),
('Introduction to Discrete Mathematics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-04', 'MATH2982'),
('Week 13 Lecture - Statistics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-07', 'MATH2982'),
('Tutorial: Spectroscopy Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-21', 'CHEM1790'),
('Thermochemistry Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-28', 'CHEM1790'),
('Laboratory: Organic Chemistry', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-02-20', 'CHEM1790'),
('Introduction to Organic Chemistry', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-14', 'CHEM1790'),
('Spectroscopy In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-03-20', 'CHEM1790'),
('Week 5 Tutorial - Linear Algebra', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-18', 'MATH1412'),
('Week 6 Tutorial - Thermochemistry', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-23', 'CHEM2782'),
('Tutorial: Spectroscopy Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-10', 'CHEM2782'),
('Chapter Quiz: Analytical Methods', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-03-19', 'CHEM2782'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-04-26', 'MATH1665'),
('Oral Expression Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-29', 'SPAN1499'),
('Chapter Quiz: Wave Optics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-09-01', 'PHYS1934'),
('Quiz 2 - Wave Optics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-10-11', 'PHYS1934'),
('Tutorial: Quantum Physics Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-28', 'PHYS1934'),
('Quantum Physics Practical', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-11-30', 'PHYS1934'),
('Laboratory: Mechanics', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-12-14', 'PHYS1934'),
('Chapter Quiz: Geophysics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-01-23', 'GEOL3417'),
('Quiz 1 - Thermochemistry', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-02-01', 'CHEM3404'),
('Calculus Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-03', 'MATH2272'),
('Probability In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-11-22', 'MATH2272'),
('Week 13 Lecture - Discrete Mathematics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-27', 'MATH2272'),
('Week 12 Tutorial - Calculus', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-27', 'MATH2272'),
('Discrete Mathematics Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-30', 'MATH2272'),
('Introduction to Calculus', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-12', 'MATH1877'),
('Introduction to Statistics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-15', 'MATH1877'),
('Statistics Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-12', 'MATH1877'),
('Statistics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-01', 'MATH1877'),
('Unit 1 Test - French Grammar', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-11-03', 'FRENCH1048'),
('Microbiology: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-16', 'BIOL1005'),
('Introduction to Microbiology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-02', 'BIOL1005'),
('Ecology: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-23', 'BIOL1005'),
('Week 3 Lecture - Probability', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-10', 'MATH3199'),
('Lecturer Office Hours - Week 9', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-03-02', 'GEOL3172'),
('Petrology Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-02', 'GEOL3172'),
('Week 1 Tutorial - Geophysics', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-16', 'GEOL3172'),
('Earth History In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-04-16', 'GEOL3172'),
('Hiragana & Katakana: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-22', 'JAPA3218'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-02-05', 'JAPA3218'),
('Chapter Quiz: Kanji', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-03-19', 'JAPA3218'),
('Lab Session 1 - Japanese Grammar', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-04-16', 'JAPA3218'),
('Week 3 Lecture - Wave Optics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-05', 'PHYS3446'),
('Quiz 1 - Business Intelligence', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-01-10', 'INFO2600'),
('Data Analytics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-16', 'INFO2600'),
('Tutorial: IT Project Management Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-06', 'INFO2600'),
('Tutorial: Data Analytics Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-24', 'INFO2600'),
('Introduction to Business Intelligence', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-09', 'INFO2600'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-09-15', 'MATH1606'),
('Chapter Quiz: Statistics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-11-27', 'MATH1606'),
('Discrete Mathematics Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-12-10', 'MATH1606'),
('Requirements Engineering: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-06', 'SWEN1392'),
('Week 5 Lecture - Requirements Engineering', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-26', 'SWEN1392'),
('DevOps: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-26', 'SWEN1392'),
('Week 9 Lecture - DevOps', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-28', 'SWEN1392'),
('Quiz 1 - Thermochemistry', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-03-04', 'CHEM1646'),
('Introduction to Spectroscopy', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-10', 'CHEM1646'),
('Organic Chemistry: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-12', 'CHEM1646'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-04-13', 'CHEM1646'),
('Week 12 Lecture - Databases', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-03', 'COMP3469'),
('Tutorial: Computer Architecture Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-04', 'COMP3469'),
('Tutorial: Computer Architecture Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-13', 'COMP3469'),
('Laboratory: Operating Systems', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-10-27', 'COMP3469'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-03-21', 'CHIN1386'),
('Human Biology: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-15', 'BIOL2262'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-01-26', 'JAPA2073'),
('Introduction to Japanese Grammar', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-18', 'JAPA2073'),
('Quiz 1 - Hiragana & Katakana', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-04-28', 'JAPA2073'),
('Introduction to Written Composition', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-08', 'FRENCH1592'),
('Week 10 Lecture - Listening Comprehension', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-29', 'FRENCH1592'),
('Tutorial: Listening Comprehension Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-31', 'FRENCH1592'),
('Quiz 1 - Oral Expression', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-11-14', 'FRENCH1592'),
('Oral Expression Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-12-15', 'FRENCH1592'),
('Introduction to Linear Algebra', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-20', 'MATH3259'),
('Week 1 Lecture - Probability', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-06', 'MATH3259'),
('Introduction to Numerical Methods', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-16', 'MATH3259'),
('Discrete Mathematics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-01', 'MATH3259'),
('Numerical Methods: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-13', 'MATH3259'),
('DevOps In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-01-06', 'SWEN1361'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-01-29', 'SWEN1361'),
('Requirements Engineering: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-02', 'SWEN1361'),
('Agile Methods Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-20', 'SWEN1361'),
('Software Testing: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-18', 'SWEN1361'),
('Week 5 Tutorial - Database Design', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-21', 'INFO3407'),
('IT Project Management Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-02', 'INFO3407'),
('Week 3 Tutorial - Petrology', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-04', 'GEOL2128'),
('Week 2 Lecture - Geophysics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-14', 'GEOL2128'),
('Quiz 1 - Mechanics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-01-08', 'PHYS1380'),
('Introduction to Quantum Physics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-27', 'PHYS1380'),
('Week 12 Lecture - Electromagnetism', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-27', 'PHYS1380'),
('Wave Optics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-01', 'PHYS1380'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-04-17', 'PHYS1380'),
('Quiz 1 - Wave Optics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-09-03', 'PHYS2672'),
('Week 13 Lecture - Electromagnetism', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-08', 'PHYS2672'),
('Wave Optics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-18', 'PHYS2672'),
('Chapter Quiz: Written Composition', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-01-27', 'SPAN1315'),
('Week 11 Lecture - Hispanic Literature', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-22', 'SPAN1315'),
('Lab Session 1 - Oral Expression', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-03-07', 'SPAN1315'),
('Unit 1 Test - Cell Biology', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-10-07', 'BIOL2863'),
('Ecology Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-11', 'BIOL2863'),
('Genetics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-13', 'BIOL2863'),
('Microbiology: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-29', 'BIOL2863'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-09-14', 'MATH1103'),
('Week 3 Lecture - Discrete Mathematics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-21', 'MATH1103'),
('Introduction to Calculus', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-04', 'MATH1103'),
('Laboratory: Probability', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-11-20', 'MATH1103'),
('Calculus In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-11-27', 'MATH1103'),
('Week 1 Lecture - Thermodynamics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-26', 'PHYS1823'),
('Thermodynamics In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-03-05', 'PHYS1823'),
('Quiz 1 - Data Analytics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-02-08', 'INFO1814'),
('Quiz 1 - Quantum Physics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-01-14', 'PHYS2710'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-04-04', 'PHYS2710'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-04-19', 'PHYS2710'),
('Tutorial: Earth History Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-10', 'GEOL1699'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-02-15', 'GEOL1699'),
('Lecturer Office Hours - Week 3', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-03-17', 'GEOL1699'),
('Tutorial: Earth History Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-17', 'GEOL1699'),
('Lecturer Office Hours - Week 1', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-04-06', 'GEOL1699'),
('Cell Biology: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-20', 'BIOL3375'),
('Week 7 Tutorial - Cell Biology', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-14', 'BIOL3375'),
('Unit 1 Test - Human Biology', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-04-23', 'BIOL3375'),
('Week 10 Tutorial - Mechanics', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-23', 'PHYS3244'),
('Petrology: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-18', 'GEOL1120'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-10-27', 'GEOL1120'),
('Character Writing: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-17', 'CHIN1586'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-01-18', 'CHIN1586'),
('Introduction to Reading Comprehension', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-30', 'CHIN1586'),
('Week 7 Lecture - Reading Comprehension', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-30', 'CHIN1586'),
('Week 13 Tutorial - Discrete Mathematics', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-31', 'MATH1636'),
('Lab Session 1 - Numerical Methods', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-03-21', 'MATH1636'),
('Introduction to Statistics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-05', 'MATH1636'),
('Discrete Mathematics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-13', 'MATH1636'),
('Probability: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-21', 'MATH1636'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-09-20', 'JAPA1899'),
('Oral Expression Practical', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-10-10', 'JAPA1899'),
('Introduction to Kanji', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-31', 'JAPA1899'),
('Tutorial: Japanese Culture Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-10', 'JAPA1899'),
('Japanese Culture Practical', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-12-01', 'JAPA1899'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-10-01', 'MATH1521'),
('Numerical Methods Practical', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-10-25', 'MATH1521'),
('Chapter Quiz: Discrete Mathematics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-01-13', 'MATH2424'),
('Introduction to Calculus', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-25', 'MATH2424'),
('Week 8 Tutorial - Probability', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-25', 'MATH2424'),
('Probability In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-03-22', 'MATH2424'),
('Thermodynamics Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-17', 'PHYS1478'),
('Tutorial: Quantum Physics Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-21', 'PHYS1478'),
('Introduction to Electromagnetism', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-02', 'PHYS1478'),
('Week 8 Tutorial - Thermodynamics', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-10', 'PHYS1478'),
('Mechanics Practical', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-04-20', 'PHYS1478'),
('Oral Expression Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-09', 'JAPA2042'),
('Japanese Culture In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-01-25', 'JAPA2042'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-02-19', 'JAPA2042'),
('Week 7 Lecture - Hiragana & Katakana', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-09', 'JAPA2042'),
('Tutorial: Hiragana & Katakana Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-15', 'JAPA2042'),
('Quiz 1 - Structural Geology', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-09-02', 'GEOL3335'),
('Lab Session 1 - Structural Geology', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-09-05', 'GEOL3335'),
('Petrology: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-16', 'GEOL3335'),
('Tutorial: Geophysics Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-15', 'GEOL1925'),
('Chapter Quiz: Francophone Literature', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-10-05', 'FRENCH1716'),
('Chapter Quiz: Written Composition', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-10-31', 'FRENCH1716'),
('Francophone Literature: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-17', 'FRENCH1716'),
('Listening Comprehension Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-24', 'FRENCH1716'),
('Chapter Quiz: Numerical Methods', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-09-13', 'MATH1002'),
('Quiz 1 - Human Biology', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-01-10', 'BIOL1115'),
('Lab Session 1 - Human Biology', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-01-14', 'BIOL1115'),
('Tutorial: Genetics Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-26', 'BIOL1115'),
('Tutorial: Microbiology Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-23', 'BIOL1115'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-04-08', 'BIOL1115'),
('Cell Biology: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-05', 'BIOL2430'),
('Week 1 Lecture - Human Biology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-12', 'BIOL2430'),
('Introduction to Cell Biology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-16', 'BIOL2430'),
('Week 10 Lecture - Human Biology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-26', 'BIOL2430'),
('Human Biology Practical', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-11-30', 'BIOL2430'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-09-06', 'FRENCH1521'),
('Week 5 Lecture - Listening Comprehension', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-16', 'FRENCH1521'),
('Quiz 1 - Listening Comprehension', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-12-03', 'FRENCH1521'),
('Quiz 2 - Written Composition', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-12-06', 'FRENCH1521'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-12-10', 'FRENCH1521'),
('Introduction to Statistics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-17', 'MATH1045'),
('Week 13 Lecture - Probability', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-16', 'MATH1045'),
('Discrete Mathematics Practical', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-03-07', 'MATH1045'),
('Week 9 Tutorial - Linear Algebra', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-02', 'MATH1045'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-09-15', 'SPAN2407'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-10-25', 'SPAN2407'),
('Oral Expression Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-21', 'SPAN2407'),
('Unit 1 Test - Hispanic Literature', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-12-03', 'SPAN2407'),
('Week 4 Tutorial - Mandarin Tones', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-12-13', 'CHIN1620'),
('Organic Chemistry: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-06', 'CHEM1373'),
('Quiz 1 - Spectroscopy', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-10-29', 'CHEM1373'),
('Introduction to Spectroscopy', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-11', 'CHEM1373'),
('Discrete Mathematics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-05', 'MATH1980'),
('Introduction to Linear Algebra', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-13', 'MATH1980'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-03-16', 'MATH1980'),
('Chapter Quiz: Discrete Mathematics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-03-28', 'MATH1980'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-04-18', 'MATH1980'),
('Week 9 Lecture - Electromagnetism', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-23', 'PHYS2664'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-09-13', 'MATH3437'),
('Week 2 Lecture - Numerical Methods', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-14', 'MATH3437'),
('Tutorial: Statistics Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-26', 'MATH3437'),
('Lecturer Office Hours - Week 13', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-01-13', 'MATH2923'),
('Quiz 1 - Statistics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-02-16', 'MATH2923'),
('Statistics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-20', 'MATH2923'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-03-30', 'MATH2923'),
('Week 5 Tutorial - DevOps', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-14', 'SWEN1995'),
('Chinese Culture: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-24', 'CHIN1801'),
('Week 3 Tutorial - Reading Comprehension', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-13', 'CHIN1801'),
('Week 6 Tutorial - Chinese Culture', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-26', 'CHIN1801'),
('Chapter Quiz: Reading Comprehension', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-04-22', 'CHIN1801'),
('Introduction to Statistics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-02', 'MATH2518'),
('Laboratory: Statistics', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-03-07', 'MATH2518'),
('Tutorial: Probability Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-09', 'MATH2518'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-09-02', 'JAPA2245'),
('Week 1 Lecture - Oral Expression', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-15', 'JAPA2245'),
('Oral Expression Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-21', 'JAPA2245'),
('Hiragana & Katakana Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-22', 'JAPA2245'),
('Unit 1 Test - Mineralogy', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-01-16', 'GEOL3334'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-02-04', 'GEOL3334'),
('Tutorial: Thermodynamics Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-01', 'PHYS1767'),
('Quantum Physics Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-23', 'PHYS1767'),
('Electromagnetism: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-27', 'PHYS1767'),
('Wave Optics In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-10-31', 'PHYS1767'),
('Week 1 Tutorial - Quantum Physics', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-12-09', 'PHYS1767'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-09-05', 'CHEM3043'),
('Tutorial: Thermochemistry Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-24', 'CHEM3043'),
('Tutorial: Inorganic Chemistry Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-13', 'CHEM3043'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-09-10', 'BIOL2311'),
('Human Biology Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-27', 'BIOL2311'),
('Chapter Quiz: Genetics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-11-03', 'BIOL2311'),
('Cell Biology: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-11', 'BIOL2311'),
('Cell Biology Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-12-05', 'BIOL2311'),
('Week 6 Lecture - French Grammar', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-18', 'FRENCH2645'),
('Francophone Literature Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-24', 'FRENCH2645'),
('Written Composition Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-12-01', 'FRENCH2645'),
('Oral Expression Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-12-02', 'FRENCH2645'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-01-23', 'CHEM3273'),
('Thermochemistry: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-03', 'CHEM3273'),
('Organic Chemistry: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-04', 'CHEM3273'),
('Introduction to Spectroscopy', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-23', 'CHEM3273'),
('Week 4 Tutorial - Calculus', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-03', 'MATH2963'),
('Numerical Methods: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-06', 'MATH2963'),
('Calculus: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-07', 'MATH2963'),
('Linear Algebra: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-28', 'MATH2963'),
('Week 10 Lecture - Thermochemistry', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-08', 'CHEM2403'),
('Organic Chemistry Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-22', 'CHEM2403'),
('Organic Chemistry Practical', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-02-05', 'CHEM2403'),
('Introduction to Spectroscopy', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-18', 'CHEM2403'),
('Lecturer Office Hours - Week 1', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-04-08', 'CHEM2403'),
('Cell Biology: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-09', 'BIOL1499'),
('Lab Session 1 - Spanish Grammar', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-09-24', 'SPAN2935'),
('Week 5 Tutorial - Spanish Grammar', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-21', 'SPAN2935'),
('Laboratory: Organic Chemistry', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-01-27', 'CHEM2397'),
('Thermochemistry Practical', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-02-28', 'CHEM2397'),
('Tutorial: Analytical Methods Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-05', 'CHEM2397'),
('Introduction to Spectroscopy', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-25', 'CHEM2397'),
('Introduction to Spectroscopy', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-03', 'CHEM2730'),
('Week 10 Lecture - Analytical Methods', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-09', 'CHEM2730'),
('Thermochemistry: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-23', 'CHEM2025'),
('Introduction to Organic Chemistry', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-10', 'CHEM2025'),
('Tutorial: Analytical Methods Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-28', 'CHEM2025'),
('Introduction to Human Biology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-01', 'BIOL1061'),
('Chapter Quiz: Database Design', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-10-20', 'INFO1671'),
('Introduction to Database Design', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-04', 'INFO1671'),
('Lecturer Office Hours - Week 10', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-12-08', 'INFO1671'),
('Mechanics Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-16', 'PHYS2913'),
('Week 6 Lecture - Ecology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-14', 'BIOL2796'),
('Week 9 Tutorial - Microbiology', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-14', 'BIOL2796'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-02-15', 'BIOL2796'),
('Week 13 Tutorial - Microbiology', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-04', 'BIOL2796'),
('Week 5 Lecture - Ecology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-20', 'BIOL2796'),
('Week 9 Tutorial - Cell Biology', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-11', 'BIOL2870'),
('Human Biology Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-12-04', 'BIOL2870'),
('Japanese Grammar: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-13', 'JAPA3464'),
('Introduction to Software Design', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-19', 'SWEN2407'),
('Week 8 Lecture - Agile Methods', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-22', 'SWEN2407'),
('Laboratory: Calculus', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-09-18', 'MATH2177'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-10-06', 'MATH2177'),
('Quiz 1 - Statistics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-10-11', 'MATH2177'),
('Week 2 Lecture - Discrete Mathematics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-21', 'MATH2177'),
('Quiz 2 - Probability', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-12-15', 'MATH2177'),
('Introduction to Petrology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-02', 'GEOL2192'),
('Earth History In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-09-16', 'GEOL2192'),
('Chapter Quiz: Mineralogy', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-09-21', 'GEOL2192'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-10-28', 'GEOL2192'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-11-12', 'GEOL2192'),
('Week 10 Lecture - Networking', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-05', 'COMP2005'),
('Japanese Culture In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-10-11', 'JAPA1518'),
('Lecturer Office Hours - Week 9', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-10-14', 'JAPA1518'),
('Laboratory: Japanese Grammar', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-11-09', 'JAPA1518'),
('Introduction to Kanji', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-25', 'JAPA1518'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-01-28', 'PHYS2170'),
('Introduction to Mechanics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-01', 'PHYS2170'),
('Quiz 1 - Electromagnetism', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-03-17', 'PHYS2170'),
('Introduction to Mechanics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-21', 'PHYS2170'),
('Week 10 Lecture - Organic Chemistry', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-10', 'CHEM1671'),
('Week 1 Lecture - Organic Chemistry', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-10', 'CHEM1671'),
('Inorganic Chemistry Practical', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-03-16', 'CHEM1671'),
('Tutorial: Thermochemistry Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-29', 'CHEM1671'),
('Tutorial: Oral Expression Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-10', 'CHIN3361'),
('Quiz 1 - Ecology', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-10-01', 'BIOL3204'),
('Chapter Quiz: Analytical Methods', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-10-22', 'CHEM1070'),
('Week 11 Lecture - Inorganic Chemistry', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-05', 'CHEM1070'),
('Tutorial: Inorganic Chemistry Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-08', 'CHEM1070'),
('Analytical Methods: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-18', 'CHEM1070'),
('Mechanics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-23', 'PHYS1272'),
('Unit 1 Test - Electromagnetism', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-04-01', 'PHYS1272'),
('Mechanics Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-03', 'PHYS1272'),
('Week 12 Lecture - Mechanics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-08', 'PHYS1272'),
('Electromagnetism: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-18', 'PHYS1272'),
('Spectroscopy Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-21', 'CHEM2100'),
('Quiz 1 - Inorganic Chemistry', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-02-16', 'CHEM2100'),
('Organic Chemistry Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-24', 'CHEM2100'),
('Week 5 Lecture - Organic Chemistry', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-22', 'CHEM2100'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-01-18', 'SWEN2261'),
('Chapter Quiz: Agile Methods', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-04-02', 'SWEN2261'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-04-17', 'SWEN2261'),
('Hispanic Literature Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-03', 'SPAN2038'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-04-09', 'BIOL1186'),
('Discrete Mathematics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-07', 'MATH3063'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-04-30', 'MATH3063'),
('Chapter Quiz: Numerical Methods', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-02-10', 'MATH1403'),
('Introduction to Probability', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-13', 'MATH1403'),
('Tutorial: Discrete Mathematics Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-25', 'MATH1403'),
('Tutorial: Numerical Methods Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-28', 'MATH1403'),
('Lecturer Office Hours - Week 9', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-04-26', 'MATH1403'),
('Quiz 1 - Thermochemistry', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-11-26', 'CHEM2657');

INSERT INTO CalendarEvent (event_name, details, event_date, c_code) VALUES
('Week 10 Tutorial - Ecology', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-08', 'BIOL2872'),
('Week 12 Lecture - Microbiology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-15', 'BIOL2872'),
('Human Biology: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-23', 'BIOL3135'),
('Genetics Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-01', 'BIOL3135'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-02-12', 'BIOL3135'),
('Genetics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-16', 'BIOL3135'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-01-28', 'GEOL2250'),
('Tutorial: Structural Geology Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-04', 'GEOL2250'),
('Lecturer Office Hours - Week 8', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-03-15', 'GEOL2250'),
('Week 2 Lecture - Geophysics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-30', 'GEOL2250'),
('Tutorial: Earth History Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-28', 'GEOL2250'),
('Algorithms Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-24', 'COMP3003'),
('Tutorial: Algorithms Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-11', 'COMP3003'),
('Chapter Quiz: Databases', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-10-16', 'COMP3003'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-10-24', 'COMP3003'),
('Week 13 Lecture - Software Engineering', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-13', 'COMP3003'),
('Ecology Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-23', 'BIOL1384'),
('Lecturer Office Hours - Week 1', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-02-28', 'BIOL1384'),
('Tutorial: Microbiology Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-15', 'BIOL1384'),
('Cell Biology: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-23', 'BIOL1384'),
('Spectroscopy Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-21', 'CHEM2459'),
('Quiz 1 - Thermochemistry', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-11-23', 'CHEM2459'),
('Unit 1 Test - Thermochemistry', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-11-24', 'CHEM2459'),
('Quiz 2 - Mineralogy', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-01-06', 'GEOL1547'),
('Earth History In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-01-23', 'GEOL1547'),
('Quiz 3 - Petrology', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-02-25', 'GEOL1547'),
('Mineralogy Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-13', 'GEOL1547'),
('Week 9 Tutorial - Oral Expression', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-13', 'FRENCH1121'),
('Introduction to Written Composition', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-19', 'FRENCH1121'),
('Earth History: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-11', 'GEOL1317'),
('Quantum Physics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-04', 'PHYS2774'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-09-22', 'MATH3444'),
('Week 13 Tutorial - Probability', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-22', 'MATH3444'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-09-06', 'CHEM2523'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-09-16', 'CHEM2523'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-10-25', 'CHEM2523'),
('Spectroscopy Practical', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-11-25', 'CHEM2523'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-09-04', 'CHEM1470'),
('Spectroscopy: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-13', 'CHEM1470'),
('Spectroscopy: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-20', 'CHEM1470'),
('Tutorial: Thermochemistry Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-27', 'CHEM1470'),
('Chapter Quiz: Earth History', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-09-16', 'GEOL2242'),
('Week 3 Lecture - Mineralogy', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-15', 'GEOL2242'),
('Introduction to Mineralogy', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-16', 'GEOL2242'),
('DevOps Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-12-05', 'SWEN1016'),
('Laboratory: Information Security', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-09-07', 'INFO3305'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-10-19', 'PHYS3378'),
('Mechanics Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-31', 'PHYS3378'),
('Introduction to Quantum Physics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-08', 'PHYS3378'),
('Quiz 1 - Software Engineering', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-09-02', 'COMP2059'),
('Lab Session 1 - Algorithms', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-10-02', 'COMP2059'),
('Introduction to Networking', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-29', 'COMP2059'),
('Week 3 Lecture - Data Structures', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-30', 'COMP2059'),
('Introduction to Software Engineering', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-09', 'COMP2059'),
('Week 4 Tutorial - Operating Systems', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-12-13', 'COMP2868'),
('Introduction to Ecology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-21', 'BIOL2206'),
('Tutorial: Human Biology Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-26', 'BIOL2206'),
('Unit 1 Test - Genetics', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-02-15', 'BIOL2206'),
('Lab Session 1 - Human Biology', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-04-09', 'BIOL2206'),
('Introduction to Genetics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-21', 'BIOL2206'),
('Week 6 Lecture - Analytical Methods', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-19', 'CHEM1185'),
('Quiz 1 - Inorganic Chemistry', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-04-08', 'CHEM1185'),
('Week 12 Tutorial - Thermochemistry', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-06', 'CHEM2642'),
('Week 2 Lecture - Organic Chemistry', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-07', 'CHEM2642'),
('Week 6 Tutorial - Organic Chemistry', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-05', 'CHEM2642'),
('Lab Session 1 - Thermochemistry', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-12-08', 'CHEM2642'),
('Earth History In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-01-14', 'GEOL1787'),
('Introduction to Structural Geology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-05', 'GEOL1787'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-09-24', 'MATH1004'),
('Numerical Methods: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-19', 'MATH1004'),
('Week 11 Lecture - Numerical Methods', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-27', 'MATH1004'),
('Linear Algebra: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-25', 'MATH1004'),
('Week 13 Lecture - Earth History', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-08', 'GEOL1379'),
('Unit 1 Test - Probability', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-02-27', 'MATH1102'),
('Week 12 Tutorial - Linear Algebra', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-10', 'MATH1102'),
('Statistics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-11', 'MATH1102'),
('Discrete Mathematics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-17', 'MATH1102'),
('Lecturer Office Hours - Week 10', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-01-11', 'CHEM3213'),
('Spectroscopy: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-24', 'CHEM3213'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-01-22', 'BIOL2226'),
('Introduction to Cell Biology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-14', 'BIOL2226'),
('Week 3 Lecture - Genetics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-28', 'BIOL2226'),
('Chapter Quiz: Microbiology', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-03-18', 'BIOL2226'),
('Tutorial: Genetics Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-30', 'BIOL2226'),
('Week 2 Lecture - Earth History', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-24', 'GEOL2064'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-01-20', 'CHIN1591'),
('Week 2 Lecture - Mandarin Tones', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-08', 'CHIN1591'),
('Unit 1 Test - Mandarin Tones', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-03-20', 'CHIN1591'),
('Character Writing: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-20', 'CHIN1591'),
('Tutorial: Oral Expression Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-28', 'CHIN1591'),
('Week 10 Lecture - Thermodynamics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-12', 'PHYS2431'),
('Week 11 Lecture - Mineralogy', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-19', 'GEOL2330'),
('IT Project Management: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-20', 'INFO1921'),
('Quiz 1 - Database Design', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-11-22', 'INFO1921'),
('Wave Optics In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-02-21', 'PHYS2318'),
('Introduction to Quantum Physics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-22', 'PHYS2318'),
('Chapter Quiz: Wave Optics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-04-07', 'PHYS2318'),
('Week 1 Lecture - Calculus', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-11', 'MATH1718'),
('Tutorial: Probability Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-18', 'MATH1718'),
('Chapter Quiz: Linear Algebra', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-11-17', 'MATH1718'),
('Lecturer Office Hours - Week 5', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-11-26', 'MATH1718'),
('Introduction to Discrete Mathematics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-07', 'MATH1718'),
('Wave Optics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-19', 'PHYS1253'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-11-27', 'PHYS1253'),
('Electromagnetism Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-12-10', 'PHYS1253'),
('Lab Session 1 - Microbiology', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-02-11', 'BIOL1249'),
('Geophysics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-22', 'GEOL3326'),
('Week 10 Tutorial - Petrology', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-26', 'GEOL3326'),
('Week 5 Tutorial - Mineralogy', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-12-01', 'GEOL3326'),
('Introduction to Structural Geology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-03', 'GEOL3326'),
('Analytical Methods Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-08', 'CHEM2815'),
('Analytical Methods: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-08', 'CHEM2815'),
('Chapter Quiz: Statistics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-02-16', 'MATH3120'),
('Chapter Quiz: Probability', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-02-21', 'MATH3120'),
('Numerical Methods Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-13', 'MATH3120'),
('Week 13 Tutorial - Linear Algebra', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-09', 'MATH3120');

