-- Generated by Claude AI

Use University;

-- a. At least 100,000 students
SELECT COUNT(*) AS total_students
FROM Student;

-- b. At least 200 courses
SELECT COUNT(*) AS total_courses
FROM Course;

-- c. No student enrolled in more than 6 courses
SELECT MAX(course_count) AS max_courses_per_student
FROM (
    SELECT st_ID, COUNT(*) AS course_count
    FROM Register_for
    GROUP BY st_ID
) AS student_courses;

-- d. Every student is enrolled in at least 3 courses
SELECT COUNT(*) AS students_below_minimum
FROM (
    SELECT st_ID, COUNT(*) AS course_count
    FROM Register_for
    GROUP BY st_ID
    HAVING COUNT(*) < 3
) AS violations;

-- e. Every course has at least 10 members (students + lecturer)
SELECT COUNT(*) AS courses_below_minimum
FROM (
    SELECT 
        c.c_code,
        COUNT(r.st_ID) + CASE WHEN c.lect_ID IS NOT NULL THEN 1 ELSE 0 END AS member_count
    FROM Course c
    LEFT JOIN Register_for r ON c.c_code = r.c_code
    GROUP BY c.c_code, c.lect_ID
    HAVING COUNT(r.st_ID) + CASE WHEN c.lect_ID IS NOT NULL THEN 1 ELSE 0 END < 10
) AS violations;

-- f. No lecturer teaches more than 5 courses
SELECT MAX(course_count) AS max_courses_per_lecturer
FROM (
    SELECT lect_ID, COUNT(*) AS course_count
    FROM Course
    GROUP BY lect_ID
) AS lecturer_courses;

-- g. Every lecturer teaches at least 1 course
SELECT COUNT(*) AS lecturers_teaching_zero
FROM Lecturer l
LEFT JOIN Course c ON l.lect_ID = c.lect_ID
WHERE c.lect_ID IS NULL;