-- ASSIGNMENT INSERTS
INSERT INTO Assignment (a_desc, a_due_date, c_code) VALUES
('Solve the attached number theory problem set and verify your answers using any computational tool.', '2025-11-08', 'MATH2300'),
('Complete the problem set on discrete mathematics. Show all working - answers without justification will not receive credit.', '2025-11-08', 'MATH2300'),
('Model the real-world scenario below using discrete mathematics techniques and interpret your results.', '2025-11-18', 'MATH2300'),
('Prove the following probability theorems using the methods covered in lectures.', '2025-11-29', 'MATH2300'),
('Write a short essay comparing two approaches to statistics, with worked examples for each.', '2025-12-09', 'MATH2300'),
('Record a two-minute spoken response in French on the environment. Submit as an audio file.', '2025-03-08', 'FRENCH1586'),
('Translate the provided passage from English to French, preserving tone and meaning.', '2025-04-01', 'FRENCH1586'),
('Solve the quantum mechanics problem set. Include free-body diagrams where applicable.', '2025-12-03', 'PHYS1266'),
('Research a real-world application of quantum mechanics and write a two-page technical summary.', '2025-12-06', 'PHYS1266'),
('Record a spoken response in Japanese describing travel. Submit as an audio file.', '2025-01-31', 'JAPA1692'),
('Write a dialogue in Japanese between two characters meeting for the first time.', '2025-03-21', 'JAPA1692'),
('Translate the provided passage from English into Japanese.', '2025-04-01', 'JAPA1692'),
('Write a short essay in Japanese on the topic of technology. Minimum 200 characters.', '2025-04-20', 'JAPA1692'),
('Write a lab report for the projectile motion experiment. Compare your results to the theoretical values and discuss errors.', '2025-11-06', 'PHYS1990'),
('Analyse the experimental data provided using quantum mechanics principles and present your conclusions.', '2025-11-15', 'PHYS1990'),
('Solve the quantum mechanics problem set. Include free-body diagrams where applicable.', '2025-11-20', 'PHYS1990'),
('Research a real-world application of thermodynamics and write a two-page technical summary.', '2025-11-27', 'PHYS1990'),
('Record a two-minute spoken response in Spanish describing family life. Submit as an audio file.', '2025-10-15', 'SPAN1013'),
('Prepare a written dialogue in Spanish between two characters discussing travel.', '2025-11-06', 'SPAN1013'),
('Prepare a lab report on the enzyme kinetics experiment from Week 5. Include your hypothesis, results, and discussion.', '2025-02-07', 'BIOL1674'),
('Write an essay discussing the role of DNA replication in human disease. Use at least six academic references.', '2025-02-15', 'BIOL1674'),
('Create an annotated diagram of the the immune system process, explaining each stage in your own words.', '2025-03-30', 'BIOL1674'),
('Design a controlled experiment to investigate the effect of an environmental variable on DNA replication.', '2025-04-13', 'BIOL1674'),
('Write a dialogue in Mandarin between two people discussing family.', '2025-03-08', 'CHIN3331'),
('Write a short paragraph in Mandarin describing food. Use a minimum of 150 characters.', '2025-03-28', 'CHIN3331'),
('Translate the provided English passage into Mandarin Chinese.', '2025-04-17', 'CHIN3331'),
('Record yourself reading the provided Mandarin text aloud. Submit as an audio file.', '2025-04-26', 'CHIN3331'),
('Translate the provided passage from English to Spanish, preserving tone and meaning.', '2025-10-14', 'SPAN2889'),
('Prepare a written dialogue in Spanish between two characters discussing culture.', '2025-12-05', 'SPAN2889'),
('Research and summarise the industrial applications of spectroscopy. Cite at least five peer-reviewed sources.', '2025-02-15', 'CHEM1330'),
('Complete the reaction mechanism worksheet for acid-base reactions. Clearly label all intermediates and arrow-pushing steps.', '2025-03-25', 'CHEM1330'),
('Prepare a safety data summary for the reagents used in the organic synthesis lab and assess associated hazards.', '2025-04-07', 'CHEM1330'),
('Solve the attached statistics problem set and verify your answers using any computational tool.', '2025-09-30', 'MATH1116'),
('Prove the following calculus theorems using the methods covered in lectures.', '2025-11-20', 'MATH1116'),
('Model the real-world scenario below using number theory techniques and interpret your results.', '2025-11-28', 'MATH1116'),
('Complete the problem set on numerical methods. Show all working - answers without justification will not receive credit.', '2025-12-11', 'MATH1116'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-02-26', 'GEOL1664'),
('Research the geologic history of fault systems and write a two-page summary with cited sources.', '2025-03-06', 'GEOL1664'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-03-11', 'GEOL1664'),
('Write a field report based on the fault systems site visit conducted in Week 5.', '2025-04-28', 'GEOL1664'),
('Write an essay discussing the role of the immune system in human disease. Use at least six academic references.', '2025-10-13', 'BIOL1341'),
('Prepare a lab report on the mitosis experiment from Week 4. Include your hypothesis, results, and discussion.', '2025-10-31', 'BIOL1341'),
('Create an annotated diagram of the cellular respiration process, explaining each stage in your own words.', '2025-11-02', 'BIOL1341'),
('Design a controlled experiment to investigate the effect of an environmental variable on the immune system.', '2025-12-08', 'BIOL1341'),
('Analyse the grammatical structures used in the provided Spanish text and annotate them with explanations.', '2025-03-12', 'SPAN2282'),
('Record a two-minute spoken response in Spanish describing technology. Submit as an audio file.', '2025-04-09', 'SPAN2282'),
('Translate the provided passage from English to Spanish, preserving tone and meaning.', '2025-03-14', 'SPAN2699'),
('Write a 500-word essay in Spanish on the topic of the environment. Focus on grammatical accuracy and vocabulary range.', '2025-03-23', 'SPAN2699'),
('Analyse the grammatical structures used in the provided Spanish text and annotate them with explanations.', '2025-04-22', 'SPAN2699'),
('Record a two-minute spoken response in French on daily routines. Submit as an audio file.', '2025-11-01', 'FRENCH1558'),
('Analyse the grammatical structures in the provided French text and annotate them.', '2025-11-22', 'FRENCH1558'),
('Write a formal letter in French responding to the scenario described in the case study.', '2025-12-10', 'FRENCH1558'),
('Research a real-world application of wave optics and write a two-page technical summary.', '2025-03-01', 'PHYS3306'),
('Derive the equations of motion for the given simple harmonic motion system from first principles.', '2025-03-03', 'PHYS3306'),
('Analyse the experimental data provided using simple harmonic motion principles and present your conclusions.', '2025-04-02', 'PHYS3306'),
('Create an annotated diagram of the enzyme kinetics process, explaining each stage in your own words.', '2025-03-23', 'BIOL3106'),
('Prepare a lab report on the natural selection experiment from Week 3. Include your hypothesis, results, and discussion.', '2025-04-16', 'BIOL3106'),
('Write a 500-word essay in French on the topic of technology. Pay attention to agreement and verb conjugation.', '2025-12-08', 'FRENCH1916'),
('Analyse the grammatical structures in the provided French text and annotate them.', '2025-12-14', 'FRENCH1916'),
('Design a normalised relational schema for a education system. Include an ER diagram and justification.', '2025-11-12', 'INFO1150'),
('Using the provided dataset, perform exploratory data analysis and present your findings in a dashboard.', '2025-11-21', 'INFO1150'),
('Develop a business intelligence report for a retail company using the tools discussed in class.', '2025-12-10', 'INFO1150'),
('Complete the problem set on statistics. Show all working - answers without justification will not receive credit.', '2025-10-02', 'MATH2236'),
('Write a short essay comparing two approaches to number theory, with worked examples for each.', '2025-10-03', 'MATH2236'),
('Prove the following calculus theorems using the methods covered in lectures.', '2025-10-21', 'MATH2236'),
('Model the real-world scenario below using calculus techniques and interpret your results.', '2025-12-02', 'MATH2236'),
('Solve the attached calculus problem set and verify your answers using any computational tool.', '2025-12-03', 'MATH2236'),
('Create an annotated diagram of the cellular respiration process, explaining each stage in your own words.', '2025-10-22', 'BIOL2364'),
('Design a controlled experiment to investigate the effect of an environmental variable on the immune system.', '2025-11-30', 'BIOL2364'),
('Prepare a lab report on the cellular respiration experiment from Week 6. Include your hypothesis, results, and discussion.', '2025-12-14', 'BIOL2364'),
('Research the geologic history of sedimentary basins and write a two-page summary with cited sources.', '2025-02-01', 'GEOL2984'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-04-20', 'GEOL2984'),
('Write a field report based on the fault systems site visit conducted in Week 4.', '2025-04-21', 'GEOL2984'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-03-06', 'GEOL1927'),
('Write a field report based on the volcanic activity site visit conducted in Week 6.', '2025-03-14', 'GEOL1927'),
('Research the geologic history of river deltas and write a two-page summary with cited sources.', '2025-04-15', 'GEOL1927'),
('Research the geologic history of river deltas and write a two-page summary with cited sources.', '2025-04-08', 'GEOL1015'),
('Write a field report based on the sedimentary basins site visit conducted in Week 4.', '2025-04-14', 'GEOL1015'),
('Write an essay discussing the role of cellular respiration in human disease. Use at least six academic references.', '2025-11-13', 'BIOL2128'),
('Prepare a lab report on the cellular respiration experiment from Week 4. Include your hypothesis, results, and discussion.', '2025-11-21', 'BIOL2128'),
('Design a controlled experiment to investigate the effect of an environmental variable on natural selection.', '2025-12-01', 'BIOL2128'),
('Prepare a safety data summary for the reagents used in the acid-base reactions lab and assess associated hazards.', '2025-02-28', 'CHEM2751'),
('Write a formal lab report for the thermochemistry experiment conducted in Week 3. Follow the standard report format.', '2025-03-25', 'CHEM2751'),
('Research and summarise the industrial applications of acid-base reactions. Cite at least five peer-reviewed sources.', '2025-04-19', 'CHEM2751'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-04-23', 'CHEM2751'),
('Complete the reaction mechanism worksheet for electrochemistry. Clearly label all intermediates and arrow-pushing steps.', '2025-04-24', 'CHEM2751'),
('Complete the reaction mechanism worksheet for polymer chemistry. Clearly label all intermediates and arrow-pushing steps.', '2025-09-10', 'CHEM2787'),
('Write a formal lab report for the acid-base reactions experiment conducted in Week 5. Follow the standard report format.', '2025-09-26', 'CHEM2787'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-10-28', 'CHEM2787'),
('Prepare a safety data summary for the reagents used in the spectroscopy lab and assess associated hazards.', '2025-12-06', 'CHEM2787'),
('Research and summarise the industrial applications of spectroscopy. Cite at least five peer-reviewed sources.', '2025-12-07', 'CHEM2787'),
('Prepare a safety data summary for the reagents used in the electrochemistry lab and assess associated hazards.', '2025-11-02', 'CHEM2035'),
('Complete the reaction mechanism worksheet for thermochemistry. Clearly label all intermediates and arrow-pushing steps.', '2025-11-15', 'CHEM2035'),
('Research and summarise the industrial applications of polymer chemistry. Cite at least five peer-reviewed sources.', '2025-11-27', 'CHEM2035'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-12-08', 'CHEM2035'),
('Write a formal lab report for the spectroscopy experiment conducted in Week 5. Follow the standard report format.', '2025-12-11', 'CHEM2035'),
('Produce a full requirements specification document for a hospital management system, including use cases and user stories.', '2025-02-03', 'SWEN2456'),
('Create a UML class diagram and sequence diagram for the retail system described in the case study.', '2025-03-13', 'SWEN2456'),
('Write a test plan and execute test cases for the provided ride-sharing application. Submit a defect report.', '2025-03-14', 'SWEN2456'),
('Write an essay discussing the role of mitosis in human disease. Use at least six academic references.', '2025-02-22', 'BIOL2329'),
('Create an annotated diagram of the natural selection process, explaining each stage in your own words.', '2025-04-06', 'BIOL2329'),
('Critically evaluate two research papers on DNA replication and compare their methodologies and conclusions.', '2025-04-22', 'BIOL2329'),
('Prepare a lab report on the cellular respiration experiment from Week 3. Include your hypothesis, results, and discussion.', '2025-04-23', 'BIOL2329'),
('Analyse the experimental data provided using projectile motion principles and present your conclusions.', '2025-03-06', 'PHYS3052'),
('Write a lab report for the simple harmonic motion experiment. Compare your results to the theoretical values and discuss errors.', '2025-03-25', 'PHYS3052'),
('Solve the wave optics problem set. Include free-body diagrams where applicable.', '2025-04-16', 'PHYS3052'),
('Derive the equations of motion for the given wave optics system from first principles.', '2025-09-13', 'PHYS2478'),
('Research a real-world application of electromagnetic induction and write a two-page technical summary.', '2025-10-22', 'PHYS2478'),
('Write a lab report for the quantum mechanics experiment. Compare your results to the theoretical values and discuss errors.', '2025-10-24', 'PHYS2478'),
('Analyse the experimental data provided using projectile motion principles and present your conclusions.', '2025-11-19', 'PHYS2478'),
('Prove the following discrete mathematics theorems using the methods covered in lectures.', '2025-02-24', 'MATH1762'),
('Write a short essay comparing two approaches to probability, with worked examples for each.', '2025-04-04', 'MATH1762'),
('Analyse the experimental data provided using quantum mechanics principles and present your conclusions.', '2025-09-23', 'PHYS1134'),
('Research a real-world application of thermodynamics and write a two-page technical summary.', '2025-10-30', 'PHYS1134'),
('Derive the equations of motion for the given projectile motion system from first principles.', '2025-11-16', 'PHYS1134'),
('Solve the quantum mechanics problem set. Include free-body diagrams where applicable.', '2025-11-21', 'PHYS1134'),
('Write a lab report for the electromagnetic induction experiment. Compare your results to the theoretical values and discuss errors.', '2025-11-21', 'PHYS1134'),
('Solve the attached linear algebra problem set and verify your answers using any computational tool.', '2025-02-28', 'MATH2398'),
('Model the real-world scenario below using probability techniques and interpret your results.', '2025-03-26', 'MATH2398'),
('Produce a full requirements specification document for a mobile banking system, including use cases and user stories.', '2025-10-09', 'SWEN1786'),
('Plan a two-week agile sprint for the ride-sharing project. Include a backlog, sprint goal, and burndown chart.', '2025-10-22', 'SWEN1786'),
('Perform a code review of the provided pull request. Submit written feedback addressing style, logic, and security.', '2025-10-31', 'SWEN1786'),
('Create a UML class diagram and sequence diagram for the retail system described in the case study.', '2025-12-01', 'SWEN1786'),
('Write a formal lab report for the polymer chemistry experiment conducted in Week 6. Follow the standard report format.', '2025-03-16', 'CHEM2153'),
('Complete the reaction mechanism worksheet for electrochemistry. Clearly label all intermediates and arrow-pushing steps.', '2025-04-12', 'CHEM2153'),
('Prepare a safety data summary for the reagents used in the polymer chemistry lab and assess associated hazards.', '2025-04-16', 'CHEM2153'),
('Research and summarise the industrial applications of polymer chemistry. Cite at least five peer-reviewed sources.', '2025-04-28', 'CHEM2153'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-04-29', 'CHEM2153'),
('Solve the electromagnetic induction problem set. Include free-body diagrams where applicable.', '2025-09-25', 'PHYS2502'),
('Analyse the experimental data provided using wave optics principles and present your conclusions.', '2025-10-22', 'PHYS2502'),
('Research a real-world application of simple harmonic motion and write a two-page technical summary.', '2025-11-01', 'PHYS2502'),
('Write a lab report for the quantum mechanics experiment. Compare your results to the theoretical values and discuss errors.', '2025-11-06', 'PHYS2502'),
('Derive the equations of motion for the given simple harmonic motion system from first principles.', '2025-12-10', 'PHYS2502'),
('Solve the attached linear algebra problem set and verify your answers using any computational tool.', '2025-11-04', 'MATH1437'),
('Prove the following linear algebra theorems using the methods covered in lectures.', '2025-11-05', 'MATH1437'),
('Model the real-world scenario below using statistics techniques and interpret your results.', '2025-12-13', 'MATH1437'),
('Prepare a lab report on the enzyme kinetics experiment from Week 6. Include your hypothesis, results, and discussion.', '2025-02-15', 'BIOL1621'),
('Design a controlled experiment to investigate the effect of an environmental variable on the immune system.', '2025-03-19', 'BIOL1621'),
('Create an annotated diagram of the mitosis process, explaining each stage in your own words.', '2025-04-03', 'BIOL1621'),
('Critically evaluate two research papers on cellular respiration and compare their methodologies and conclusions.', '2025-04-09', 'BIOL1621'),
('Write an essay discussing the role of cellular respiration in human disease. Use at least six academic references.', '2025-04-18', 'BIOL1621'),
('Record a two-minute spoken response in Spanish describing culture. Submit as an audio file.', '2025-10-19', 'SPAN2427'),
('Write a 500-word essay in Spanish on the topic of family life. Focus on grammatical accuracy and vocabulary range.', '2025-11-01', 'SPAN2427'),
('Prepare a written dialogue in Spanish between two characters discussing culture.', '2025-11-09', 'SPAN2427'),
('Translate the provided passage from English to Spanish, preserving tone and meaning.', '2025-11-24', 'SPAN2427'),
('Analyse the grammatical structures used in the provided Spanish text and annotate them with explanations.', '2025-12-07', 'SPAN2427'),
('Write a lab report for the simple harmonic motion experiment. Compare your results to the theoretical values and discuss errors.', '2025-09-06', 'PHYS3493'),
('Derive the equations of motion for the given thermodynamics system from first principles.', '2025-10-18', 'PHYS3493'),
('Analyse the experimental data provided using thermodynamics principles and present your conclusions.', '2025-10-19', 'PHYS3493'),
('Solve the electromagnetic induction problem set. Include free-body diagrams where applicable.', '2025-10-24', 'PHYS3493'),
('Research a real-world application of electromagnetic induction and write a two-page technical summary.', '2025-11-13', 'PHYS3493'),
('Perform a code review of the provided pull request. Submit written feedback addressing style, logic, and security.', '2025-10-16', 'SWEN2103'),
('Create a UML class diagram and sequence diagram for the fintech system described in the case study.', '2025-12-05', 'SWEN2103'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-11-10', 'CHEM2758'),
('Prepare a safety data summary for the reagents used in the spectroscopy lab and assess associated hazards.', '2025-11-24', 'CHEM2758'),
('Write a formal lab report for the electrochemistry experiment conducted in Week 6. Follow the standard report format.', '2025-12-03', 'CHEM2758'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-03-04', 'GEOL1110'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-03-07', 'GEOL1110'),
('Write a field report based on the volcanic activity site visit conducted in Week 3.', '2025-03-31', 'GEOL1110'),
('Research a real-world application of quantum mechanics and write a two-page technical summary.', '2025-01-12', 'PHYS1823'),
('Solve the electromagnetic induction problem set. Include free-body diagrams where applicable.', '2025-03-30', 'PHYS1823'),
('Prepare a lab report on the DNA replication experiment from Week 3. Include your hypothesis, results, and discussion.', '2025-04-08', 'BIOL1825'),
('Write an essay discussing the role of DNA replication in human disease. Use at least six academic references.', '2025-04-14', 'BIOL1825'),
('Create an annotated diagram of the natural selection process, explaining each stage in your own words.', '2025-04-17', 'BIOL1825'),
('Design a controlled experiment to investigate the effect of an environmental variable on natural selection.', '2025-04-24', 'BIOL1825'),
('Critically evaluate two research papers on the immune system and compare their methodologies and conclusions.', '2025-04-25', 'BIOL1825'),
('Answer the comprehension questions on the provided Mandarin reading passage.', '2025-02-19', 'CHIN2420'),
('Write a dialogue in Mandarin between two people discussing travel.', '2025-03-12', 'CHIN2420'),
('Write a short paragraph in Mandarin describing technology. Use a minimum of 150 characters.', '2025-03-12', 'CHIN2420'),
('Record yourself reading the provided Mandarin text aloud. Submit as an audio file.', '2025-04-15', 'CHIN2420'),
('Write a lab report for the projectile motion experiment. Compare your results to the theoretical values and discuss errors.', '2025-01-18', 'PHYS1665'),
('Solve the simple harmonic motion problem set. Include free-body diagrams where applicable.', '2025-03-05', 'PHYS1665'),
('Derive the equations of motion for the given quantum mechanics system from first principles.', '2025-03-25', 'PHYS1665'),
('Research a real-world application of projectile motion and write a two-page technical summary.', '2025-04-07', 'PHYS1665'),
('Analyse the experimental data provided using projectile motion principles and present your conclusions.', '2025-04-17', 'PHYS1665'),
('Write a lab report for the quantum mechanics experiment. Compare your results to the theoretical values and discuss errors.', '2025-02-16', 'PHYS2266'),
('Derive the equations of motion for the given thermodynamics system from first principles.', '2025-03-09', 'PHYS2266'),
('Research a real-world application of thermodynamics and write a two-page technical summary.', '2025-03-16', 'PHYS2266'),
('Analyse the experimental data provided using projectile motion principles and present your conclusions.', '2025-03-30', 'PHYS2266'),
('Solve the electromagnetic induction problem set. Include free-body diagrams where applicable.', '2025-04-18', 'PHYS2266'),
('Write a formal lab report for the electrochemistry experiment conducted in Week 4. Follow the standard report format.', '2025-03-16', 'CHEM3059'),
('Research and summarise the industrial applications of acid-base reactions. Cite at least five peer-reviewed sources.', '2025-03-21', 'CHEM3059'),
('Complete the reaction mechanism worksheet for spectroscopy. Clearly label all intermediates and arrow-pushing steps.', '2025-04-08', 'CHEM3059'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-04-22', 'CHEM3059'),
('Research and summarise the industrial applications of spectroscopy. Cite at least five peer-reviewed sources.', '2025-09-22', 'CHEM2637'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-10-27', 'CHEM2637'),
('Design and build a desktop application using Python. Submit source code and a README.', '2025-03-14', 'COMP1723'),
('Implement a stack in Python. Your solution must handle edge cases and include unit tests.', '2025-03-17', 'COMP1723'),
('Build a REST API with Go that performs full CRUD operations on a memory management dataset.', '2025-04-12', 'COMP1723'),
('Analyse the time and space complexity of the provided sorting algorithm. Write a report justifying your findings.', '2025-04-28', 'COMP1723'),
('Write a lab report for the quantum mechanics experiment. Compare your results to the theoretical values and discuss errors.', '2025-10-23', 'PHYS1095'),
('Analyse the experimental data provided using simple harmonic motion principles and present your conclusions.', '2025-12-04', 'PHYS1095'),
('Research a real-world application of simple harmonic motion and write a two-page technical summary.', '2025-02-27', 'PHYS2293'),
('Solve the quantum mechanics problem set. Include free-body diagrams where applicable.', '2025-03-29', 'PHYS2293'),
('Write a lab report for the wave optics experiment. Compare your results to the theoretical values and discuss errors.', '2025-04-09', 'PHYS2293'),
('Analyse the experimental data provided using quantum mechanics principles and present your conclusions.', '2025-04-29', 'PHYS2293'),
('Create a UML class diagram and sequence diagram for the government system described in the case study.', '2025-02-15', 'SWEN2287'),
('Plan a two-week agile sprint for the ride-sharing project. Include a backlog, sprint goal, and burndown chart.', '2025-02-15', 'SWEN2287'),
('Write a test plan and execute test cases for the provided mobile banking application. Submit a defect report.', '2025-04-02', 'SWEN2287'),
('Perform a code review of the provided pull request. Submit written feedback addressing style, logic, and security.', '2025-04-17', 'SWEN2287'),
('Produce a full requirements specification document for a hospital management system, including use cases and user stories.', '2025-04-27', 'SWEN2287'),
('Analyse the grammatical structures used in the provided Spanish text and annotate them with explanations.', '2025-09-24', 'SPAN1451'),
('Record a two-minute spoken response in Spanish describing culture. Submit as an audio file.', '2025-11-04', 'SPAN1451'),
('Translate the provided passage from English to Spanish, preserving tone and meaning.', '2025-11-18', 'SPAN1451'),
('Translate the provided passage from English to Spanish, preserving tone and meaning.', '2025-02-12', 'SPAN3252'),
('Analyse the grammatical structures used in the provided Spanish text and annotate them with explanations.', '2025-04-01', 'SPAN3252'),
('Prepare a written dialogue in Spanish between two characters discussing family life.', '2025-04-19', 'SPAN3252'),
('Research a real-world application of simple harmonic motion and write a two-page technical summary.', '2025-09-15', 'PHYS2311'),
('Write a lab report for the electromagnetic induction experiment. Compare your results to the theoretical values and discuss errors.', '2025-09-26', 'PHYS2311'),
('Analyse the experimental data provided using wave optics principles and present your conclusions.', '2025-10-11', 'PHYS2311'),
('Solve the electromagnetic induction problem set. Include free-body diagrams where applicable.', '2025-11-29', 'PHYS2311'),
('Derive the equations of motion for the given projectile motion system from first principles.', '2025-12-11', 'PHYS2311'),
('Prepare a safety data summary for the reagents used in the electrochemistry lab and assess associated hazards.', '2025-10-06', 'CHEM1328'),
('Write a formal lab report for the polymer chemistry experiment conducted in Week 8. Follow the standard report format.', '2025-10-06', 'CHEM1328'),
('Complete the reaction mechanism worksheet for organic synthesis. Clearly label all intermediates and arrow-pushing steps.', '2025-11-17', 'CHEM1328'),
('Research and summarise the industrial applications of electrochemistry. Cite at least five peer-reviewed sources.', '2025-12-11', 'CHEM1328'),
('Model the real-world scenario below using linear algebra techniques and interpret your results.', '2025-01-31', 'MATH2336'),
('Prove the following linear algebra theorems using the methods covered in lectures.', '2025-04-19', 'MATH2336'),
('Solve the attached number theory problem set and verify your answers using any computational tool.', '2025-04-24', 'MATH2336'),
('Prepare a lab report on the the immune system experiment from Week 2. Include your hypothesis, results, and discussion.', '2025-02-07', 'BIOL3113'),
('Critically evaluate two research papers on mitosis and compare their methodologies and conclusions.', '2025-04-14', 'BIOL3113'),
('Design a controlled experiment to investigate the effect of an environmental variable on cellular respiration.', '2025-04-20', 'BIOL3113'),
('Write an essay discussing the role of cellular respiration in human disease. Use at least six academic references.', '2025-04-22', 'BIOL3113'),
('Prepare a lab report on the the immune system experiment from Week 4. Include your hypothesis, results, and discussion.', '2025-09-25', 'BIOL2124'),
('Critically evaluate two research papers on mitosis and compare their methodologies and conclusions.', '2025-10-24', 'BIOL2124'),
('Create an annotated diagram of the the immune system process, explaining each stage in your own words.', '2025-11-02', 'BIOL2124'),
('Derive the equations of motion for the given simple harmonic motion system from first principles.', '2025-02-07', 'PHYS3432'),
('Research a real-world application of quantum mechanics and write a two-page technical summary.', '2025-02-28', 'PHYS3432'),
('Solve the wave optics problem set. Include free-body diagrams where applicable.', '2025-03-31', 'PHYS3432'),
('Write a lab report for the projectile motion experiment. Compare your results to the theoretical values and discuss errors.', '2025-04-10', 'PHYS3432'),
('Analyse the experimental data provided using electromagnetic induction principles and present your conclusions.', '2025-04-25', 'PHYS3432'),
('Create an annotated diagram of the enzyme kinetics process, explaining each stage in your own words.', '2025-01-24', 'BIOL2536'),
('Prepare a lab report on the mitosis experiment from Week 3. Include your hypothesis, results, and discussion.', '2025-02-23', 'BIOL2536'),
('Design a controlled experiment to investigate the effect of an environmental variable on DNA replication.', '2025-03-25', 'BIOL2536'),
('Critically evaluate two research papers on DNA replication and compare their methodologies and conclusions.', '2025-04-04', 'BIOL2536'),
('Write an essay discussing the role of cellular respiration in human disease. Use at least six academic references.', '2025-04-11', 'BIOL2536'),
('Analyse the experimental data provided using quantum mechanics principles and present your conclusions.', '2025-03-07', 'PHYS2109'),
('Research a real-world application of electromagnetic induction and write a two-page technical summary.', '2025-03-11', 'PHYS2109'),
('Write a lab report for the thermodynamics experiment. Compare your results to the theoretical values and discuss errors.', '2025-03-25', 'PHYS2109'),
('Derive the equations of motion for the given wave optics system from first principles.', '2025-04-03', 'PHYS2109'),
('Solve the wave optics problem set. Include free-body diagrams where applicable.', '2025-04-17', 'PHYS2109'),
('Solve the projectile motion problem set. Include free-body diagrams where applicable.', '2025-01-10', 'PHYS2275'),
('Derive the equations of motion for the given projectile motion system from first principles.', '2025-04-04', 'PHYS2275'),
('Analyse the grammatical structures used in the provided Spanish text and annotate them with explanations.', '2025-10-08', 'SPAN1574'),
('Translate the provided passage from English to Spanish, preserving tone and meaning.', '2025-10-25', 'SPAN1574'),
('Record a two-minute spoken response in Spanish describing family life. Submit as an audio file.', '2025-10-26', 'SPAN1574'),
('Prepare a written dialogue in Spanish between two characters discussing travel.', '2025-11-03', 'SPAN1574'),
('Write a 500-word essay in Spanish on the topic of the environment. Focus on grammatical accuracy and vocabulary range.', '2025-12-03', 'SPAN1574'),
('Research and summarise the industrial applications of electrochemistry. Cite at least five peer-reviewed sources.', '2025-04-15', 'CHEM2654'),
('Prepare a safety data summary for the reagents used in the polymer chemistry lab and assess associated hazards.', '2025-04-21', 'CHEM2654'),
('Prepare a safety data summary for the reagents used in the polymer chemistry lab and assess associated hazards.', '2025-10-13', 'CHEM2846'),
('Research and summarise the industrial applications of acid-base reactions. Cite at least five peer-reviewed sources.', '2025-10-25', 'CHEM2846'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-11-02', 'CHEM2846'),
('Complete the reaction mechanism worksheet for polymer chemistry. Clearly label all intermediates and arrow-pushing steps.', '2025-11-04', 'CHEM2846'),
('Create an annotated diagram of the enzyme kinetics process, explaining each stage in your own words.', '2025-03-14', 'BIOL1380'),
('Critically evaluate two research papers on the immune system and compare their methodologies and conclusions.', '2025-03-29', 'BIOL1380'),
('Write an essay discussing the role of cellular respiration in human disease. Use at least six academic references.', '2025-04-26', 'BIOL1380'),
('Analyse the experimental data provided using projectile motion principles and present your conclusions.', '2025-10-30', 'PHYS1187'),
('Derive the equations of motion for the given projectile motion system from first principles.', '2025-12-02', 'PHYS1187'),
('Research a real-world application of simple harmonic motion and write a two-page technical summary.', '2025-12-03', 'PHYS1187'),
('Solve the electromagnetic induction problem set. Include free-body diagrams where applicable.', '2025-12-04', 'PHYS1187'),
('Design and build a CLI application using Python. Submit source code and a README.', '2025-03-18', 'COMP2715'),
('Build a REST API with Go that performs full CRUD operations on a networking dataset.', '2025-04-22', 'COMP2715'),
('Analyse the time and space complexity of the provided searching algorithm. Write a report justifying your findings.', '2025-04-29', 'COMP2715'),
('Evaluate two competing cloud storage frameworks and recommend one for a given business scenario.', '2025-11-27', 'INFO3101'),
('Design a normalised relational schema for a education system. Include an ER diagram and justification.', '2025-12-02', 'INFO3101'),
('Analyse the grammatical structures used in the provided Spanish text and annotate them with explanations.', '2025-11-10', 'SPAN2900'),
('Record a two-minute spoken response in Spanish describing technology. Submit as an audio file.', '2025-11-10', 'SPAN2900'),
('Write a 500-word essay in Spanish on the topic of the environment. Focus on grammatical accuracy and vocabulary range.', '2025-11-29', 'SPAN2900'),
('Design and build a microservice application using Go. Submit source code and a README.', '2025-09-06', 'COMP2343'),
('Analyse the time and space complexity of the provided sorting algorithm. Write a report justifying your findings.', '2025-11-17', 'COMP2343'),
('Build a REST API with Python that performs full CRUD operations on a memory management dataset.', '2025-12-14', 'COMP2343'),
('Write a short essay in Japanese on the topic of travel. Minimum 200 characters.', '2025-02-12', 'JAPA2549'),
('Write a dialogue in Japanese between two characters meeting for the first time.', '2025-03-21', 'JAPA2549'),
('Translate the provided passage from English into Japanese.', '2025-04-01', 'JAPA2549'),
('Complete the grammar exercises for the structures covered in Weeks 3-5.', '2025-04-03', 'JAPA2549'),
('Record a spoken response in Japanese describing Japanese culture. Submit as an audio file.', '2025-04-26', 'JAPA2549'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-10-20', 'CHEM1249'),
('Prepare a safety data summary for the reagents used in the electrochemistry lab and assess associated hazards.', '2025-11-01', 'CHEM1249'),
('Write a formal lab report for the spectroscopy experiment conducted in Week 8. Follow the standard report format.', '2025-11-17', 'CHEM1249'),
('Research and summarise the industrial applications of thermochemistry. Cite at least five peer-reviewed sources.', '2025-12-13', 'CHEM1249'),
('Write a formal lab report for the electrochemistry experiment conducted in Week 5. Follow the standard report format.', '2025-03-21', 'CHEM2113'),
('Prepare a safety data summary for the reagents used in the organic synthesis lab and assess associated hazards.', '2025-04-21', 'CHEM2113'),
('Solve the attached calculus problem set and verify your answers using any computational tool.', '2025-11-27', 'MATH2263'),
('Complete the problem set on number theory. Show all working - answers without justification will not receive credit.', '2025-11-28', 'MATH2263'),
('Prove the following statistics theorems using the methods covered in lectures.', '2025-11-28', 'MATH2263'),
('Model the real-world scenario below using statistics techniques and interpret your results.', '2025-12-03', 'MATH2263'),
('Using the provided dataset, perform exploratory data analysis and present your findings in a dashboard.', '2025-02-23', 'INFO1373'),
('Design a normalised relational schema for a banking system. Include an ER diagram and justification.', '2025-03-18', 'INFO1373'),
('Evaluate two competing cloud storage frameworks and recommend one for a given business scenario.', '2025-04-12', 'INFO1373'),
('Write a report analysing the information security risks facing a logistics organisation.', '2025-04-13', 'INFO1373'),
('Develop a business intelligence report for a banking company using the tools discussed in class.', '2025-04-19', 'INFO1373'),
('Prove the following discrete mathematics theorems using the methods covered in lectures.', '2025-03-02', 'MATH1069'),
('Complete the problem set on linear algebra. Show all working - answers without justification will not receive credit.', '2025-04-22', 'MATH1069'),
('Model the real-world scenario below using numerical methods techniques and interpret your results.', '2025-04-27', 'MATH1069'),
('Refactor the given legacy codebase to follow SOLID principles. Document every change made.', '2025-02-06', 'COMP3369'),
('Analyse the time and space complexity of the provided pathfinding algorithm. Write a report justifying your findings.', '2025-04-21', 'COMP3369'),
('Research and summarise the industrial applications of organic synthesis. Cite at least five peer-reviewed sources.', '2025-09-21', 'CHEM1456'),
('Complete the reaction mechanism worksheet for acid-base reactions. Clearly label all intermediates and arrow-pushing steps.', '2025-11-10', 'CHEM1456'),
('Prepare a safety data summary for the reagents used in the polymer chemistry lab and assess associated hazards.', '2025-11-22', 'CHEM1456'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-12-02', 'CHEM1456'),
('Write a formal lab report for the polymer chemistry experiment conducted in Week 8. Follow the standard report format.', '2025-12-14', 'CHEM1456'),
('Prepare a lab report on the natural selection experiment from Week 6. Include your hypothesis, results, and discussion.', '2025-03-05', 'BIOL2714'),
('Design a controlled experiment to investigate the effect of an environmental variable on natural selection.', '2025-03-10', 'BIOL2714'),
('Create an annotated diagram of the enzyme kinetics process, explaining each stage in your own words.', '2025-03-22', 'BIOL2714'),
('Solve the quantum mechanics problem set. Include free-body diagrams where applicable.', '2025-09-25', 'PHYS3390'),
('Write a lab report for the thermodynamics experiment. Compare your results to the theoretical values and discuss errors.', '2025-10-22', 'PHYS3390'),
('Analyse the experimental data provided using electromagnetic induction principles and present your conclusions.', '2025-10-24', 'PHYS3390'),
('Research a real-world application of quantum mechanics and write a two-page technical summary.', '2025-12-04', 'PHYS3390'),
('Prepare a safety data summary for the reagents used in the spectroscopy lab and assess associated hazards.', '2025-10-24', 'CHEM2316'),
('Research and summarise the industrial applications of acid-base reactions. Cite at least five peer-reviewed sources.', '2025-11-14', 'CHEM2316'),
('Prove the following linear algebra theorems using the methods covered in lectures.', '2025-03-04', 'MATH3342'),
('Model the real-world scenario below using numerical methods techniques and interpret your results.', '2025-04-10', 'MATH3342'),
('Write a short essay comparing two approaches to number theory, with worked examples for each.', '2025-04-11', 'MATH3342'),
('Derive the equations of motion for the given thermodynamics system from first principles.', '2025-09-21', 'PHYS2434'),
('Research a real-world application of electromagnetic induction and write a two-page technical summary.', '2025-12-03', 'PHYS2434'),
('Solve the quantum mechanics problem set. Include free-body diagrams where applicable.', '2025-12-06', 'PHYS2434'),
('Write a lab report for the quantum mechanics experiment. Compare your results to the theoretical values and discuss errors.', '2025-12-13', 'PHYS2434'),
('Research and summarise the industrial applications of electrochemistry. Cite at least five peer-reviewed sources.', '2025-11-01', 'CHEM3131'),
('Write a formal lab report for the spectroscopy experiment conducted in Week 6. Follow the standard report format.', '2025-11-18', 'CHEM3131'),
('Prepare a lab report on the cellular respiration experiment from Week 5. Include your hypothesis, results, and discussion.', '2025-02-26', 'BIOL3331'),
('Write an essay discussing the role of natural selection in human disease. Use at least six academic references.', '2025-03-16', 'BIOL3331'),
('Critically evaluate two research papers on enzyme kinetics and compare their methodologies and conclusions.', '2025-03-16', 'BIOL3331'),
('Create an annotated diagram of the DNA replication process, explaining each stage in your own words.', '2025-03-21', 'BIOL3331'),
('Design a controlled experiment to investigate the effect of an environmental variable on the immune system.', '2025-03-28', 'BIOL3331'),
('Research a real-world application of electromagnetic induction and write a two-page technical summary.', '2025-03-17', 'PHYS3298'),
('Write a lab report for the wave optics experiment. Compare your results to the theoretical values and discuss errors.', '2025-04-05', 'PHYS3298'),
('Solve the quantum mechanics problem set. Include free-body diagrams where applicable.', '2025-04-23', 'PHYS3298'),
('Analyse the experimental data provided using projectile motion principles and present your conclusions.', '2025-04-28', 'PHYS3298'),
('Critically evaluate two research papers on cellular respiration and compare their methodologies and conclusions.', '2025-02-07', 'BIOL2747'),
('Prepare a lab report on the enzyme kinetics experiment from Week 2. Include your hypothesis, results, and discussion.', '2025-03-22', 'BIOL2747'),
('Write an essay discussing the role of the immune system in human disease. Use at least six academic references.', '2025-03-29', 'BIOL2747'),
('Translate the provided passage from English to French, preserving tone and meaning.', '2025-01-31', 'FRENCH2200'),
('Analyse the grammatical structures in the provided French text and annotate them.', '2025-02-21', 'FRENCH2200'),
('Write an essay discussing the role of natural selection in human disease. Use at least six academic references.', '2025-09-30', 'BIOL1712'),
('Create an annotated diagram of the enzyme kinetics process, explaining each stage in your own words.', '2025-11-24', 'BIOL1712'),
('Prepare a lab report on the DNA replication experiment from Week 3. Include your hypothesis, results, and discussion.', '2025-12-13', 'BIOL1712'),
('Evaluate two competing CRM frameworks and recommend one for a given business scenario.', '2025-02-07', 'INFO1371'),
('Write a report analysing the information security risks facing a healthcare organisation.', '2025-03-14', 'INFO1371'),
('Develop a business intelligence report for a education company using the tools discussed in class.', '2025-03-31', 'INFO1371'),
('Solve the attached calculus problem set and verify your answers using any computational tool.', '2025-03-10', 'MATH2114'),
('Prove the following calculus theorems using the methods covered in lectures.', '2025-03-19', 'MATH2114'),
('Model the real-world scenario below using calculus techniques and interpret your results.', '2025-04-25', 'MATH2114'),
('Write a report analysing the information security risks facing a education organisation.', '2025-11-09', 'INFO1664'),
('Evaluate two competing ERP frameworks and recommend one for a given business scenario.', '2025-11-16', 'INFO1664'),
('Write a field report based on the sedimentary basins site visit conducted in Week 6.', '2025-02-22', 'GEOL1400'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-03-29', 'GEOL1400'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-03-29', 'GEOL1400'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-03-29', 'GEOL1400'),
('Research the geologic history of coastal erosion and write a two-page summary with cited sources.', '2025-04-05', 'GEOL1400'),
('Solve the attached linear algebra problem set and verify your answers using any computational tool.', '2025-11-07', 'MATH1910'),
('Model the real-world scenario below using discrete mathematics techniques and interpret your results.', '2025-11-08', 'MATH1910'),
('Complete the problem set on linear algebra. Show all working - answers without justification will not receive credit.', '2025-11-10', 'MATH1910'),
('Prove the following numerical methods theorems using the methods covered in lectures.', '2025-11-13', 'MATH1910'),
('Prepare a safety data summary for the reagents used in the polymer chemistry lab and assess associated hazards.', '2025-11-02', 'CHEM2949'),
('Research and summarise the industrial applications of polymer chemistry. Cite at least five peer-reviewed sources.', '2025-12-10', 'CHEM2949'),
('Analyse the experimental data provided using wave optics principles and present your conclusions.', '2025-01-24', 'PHYS1272'),
('Solve the quantum mechanics problem set. Include free-body diagrams where applicable.', '2025-02-03', 'PHYS1272'),
('Implement a hash map in Python. Your solution must handle edge cases and include unit tests.', '2025-11-28', 'COMP2471'),
('Analyse the time and space complexity of the provided pathfinding algorithm. Write a report justifying your findings.', '2025-11-29', 'COMP2471'),
('Refactor the given legacy codebase to follow SOLID principles. Document every change made.', '2025-12-10', 'COMP2471'),
('Build a REST API with Java that performs full CRUD operations on a networking dataset.', '2025-12-10', 'COMP2471'),
('Write a 500-word essay in Spanish on the topic of family life. Focus on grammatical accuracy and vocabulary range.', '2025-03-21', 'SPAN2626'),
('Record a two-minute spoken response in Spanish describing technology. Submit as an audio file.', '2025-03-24', 'SPAN2626'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-11-09', 'GEOL3241'),
('Write a field report based on the river deltas site visit conducted in Week 4.', '2025-11-28', 'GEOL3241'),
('Research the geologic history of sedimentary basins and write a two-page summary with cited sources.', '2025-12-04', 'GEOL3241'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-12-06', 'GEOL3241'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-12-14', 'GEOL3241'),
('Solve the quantum mechanics problem set. Include free-body diagrams where applicable.', '2025-01-29', 'PHYS2095'),
('Write a lab report for the quantum mechanics experiment. Compare your results to the theoretical values and discuss errors.', '2025-02-11', 'PHYS2095'),
('Research a real-world application of wave optics and write a two-page technical summary.', '2025-04-15', 'PHYS2095'),
('Analyse the experimental data provided using electromagnetic induction principles and present your conclusions.', '2025-04-20', 'PHYS2095'),
('Answer the comprehension questions on the provided Mandarin reading passage.', '2025-02-11', 'CHIN1469'),
('Record yourself reading the provided Mandarin text aloud. Submit as an audio file.', '2025-03-03', 'CHIN1469'),
('Write a short paragraph in Mandarin describing technology. Use a minimum of 150 characters.', '2025-04-15', 'CHIN1469'),
('Write a short essay in Japanese on the topic of Japanese culture. Minimum 200 characters.', '2025-01-31', 'JAPA1276'),
('Translate the provided passage from English into Japanese.', '2025-02-06', 'JAPA1276'),
('Complete the grammar exercises for the structures covered in Weeks 4-6.', '2025-03-23', 'JAPA1276'),
('Write a dialogue in Japanese between two characters meeting for the first time.', '2025-03-30', 'JAPA1276'),
('Write a dialogue in Japanese between two characters meeting for the first time.', '2025-01-23', 'JAPA2433'),
('Record a spoken response in Japanese describing travel. Submit as an audio file.', '2025-03-03', 'JAPA2433'),
('Model the real-world scenario below using probability techniques and interpret your results.', '2025-02-16', 'MATH3232'),
('Write a short essay comparing two approaches to number theory, with worked examples for each.', '2025-03-02', 'MATH3232'),
('Solve the attached discrete mathematics problem set and verify your answers using any computational tool.', '2025-03-02', 'MATH3232'),
('Prove the following probability theorems using the methods covered in lectures.', '2025-03-05', 'MATH3232'),
('Write a formal lab report for the electrochemistry experiment conducted in Week 8. Follow the standard report format.', '2025-03-03', 'CHEM1822'),
('Complete the reaction mechanism worksheet for organic synthesis. Clearly label all intermediates and arrow-pushing steps.', '2025-04-14', 'CHEM1822'),
('Research a real-world application of thermodynamics and write a two-page technical summary.', '2025-02-05', 'PHYS2976'),
('Analyse the experimental data provided using simple harmonic motion principles and present your conclusions.', '2025-03-23', 'PHYS2976'),
('Solve the quantum mechanics problem set. Include free-body diagrams where applicable.', '2025-03-25', 'PHYS2976'),
('Write a lab report for the thermodynamics experiment. Compare your results to the theoretical values and discuss errors.', '2025-04-04', 'PHYS2976'),
('Derive the equations of motion for the given simple harmonic motion system from first principles.', '2025-04-14', 'PHYS2976'),
('Write an essay discussing the role of natural selection in human disease. Use at least six academic references.', '2025-03-10', 'BIOL1614'),
('Prepare a lab report on the DNA replication experiment from Week 2. Include your hypothesis, results, and discussion.', '2025-04-01', 'BIOL1614'),
('Record a two-minute spoken response in French on travel. Submit as an audio file.', '2025-10-25', 'FRENCH2928'),
('Write a formal letter in French responding to the scenario described in the case study.', '2025-11-11', 'FRENCH2928'),
('Translate the provided passage from English to French, preserving tone and meaning.', '2025-11-30', 'FRENCH2928'),
('Write a 500-word essay in French on the topic of travel. Pay attention to agreement and verb conjugation.', '2025-12-06', 'FRENCH2928'),
('Prove the following linear algebra theorems using the methods covered in lectures.', '2025-11-02', 'MATH2944'),
('Complete the problem set on calculus. Show all working - answers without justification will not receive credit.', '2025-12-08', 'MATH2944'),
('Write an essay discussing the role of mitosis in human disease. Use at least six academic references.', '2025-09-11', 'BIOL3303'),
('Create an annotated diagram of the the immune system process, explaining each stage in your own words.', '2025-09-17', 'BIOL3303'),
('Prepare a lab report on the mitosis experiment from Week 2. Include your hypothesis, results, and discussion.', '2025-09-23', 'BIOL3303'),
('Critically evaluate two research papers on mitosis and compare their methodologies and conclusions.', '2025-11-06', 'BIOL3303'),
('Design a controlled experiment to investigate the effect of an environmental variable on DNA replication.', '2025-12-10', 'BIOL3303'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-10-09', 'CHEM2727'),
('Prepare a safety data summary for the reagents used in the electrochemistry lab and assess associated hazards.', '2025-11-12', 'CHEM2727'),
('Research and summarise the industrial applications of polymer chemistry. Cite at least five peer-reviewed sources.', '2025-11-28', 'CHEM2727'),
('Solve the thermodynamics problem set. Include free-body diagrams where applicable.', '2025-09-15', 'PHYS2191'),
('Derive the equations of motion for the given simple harmonic motion system from first principles.', '2025-11-05', 'PHYS2191'),
('Analyse the experimental data provided using projectile motion principles and present your conclusions.', '2025-11-09', 'PHYS2191'),
('Write a lab report for the electromagnetic induction experiment. Compare your results to the theoretical values and discuss errors.', '2025-12-14', 'PHYS2191'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-02-15', 'CHEM1149'),
('Prepare a safety data summary for the reagents used in the spectroscopy lab and assess associated hazards.', '2025-02-27', 'CHEM1149'),
('Complete the reaction mechanism worksheet for thermochemistry. Clearly label all intermediates and arrow-pushing steps.', '2025-04-03', 'CHEM1149'),
('Write a formal lab report for the organic synthesis experiment conducted in Week 3. Follow the standard report format.', '2025-04-13', 'CHEM1149'),
('Write a report analysing the information security risks facing a logistics organisation.', '2025-02-20', 'INFO1502'),
('Develop a business intelligence report for a retail company using the tools discussed in class.', '2025-03-20', 'INFO1502'),
('Design a normalised relational schema for a logistics system. Include an ER diagram and justification.', '2025-04-12', 'INFO1502'),
('Complete the problem set on number theory. Show all working - answers without justification will not receive credit.', '2025-02-17', 'MATH1669'),
('Write a short essay comparing two approaches to calculus, with worked examples for each.', '2025-03-06', 'MATH1669'),
('Solve the attached discrete mathematics problem set and verify your answers using any computational tool.', '2025-03-14', 'MATH1669'),
('Model the real-world scenario below using linear algebra techniques and interpret your results.', '2025-04-14', 'MATH1669'),
('Write a short essay comparing two approaches to statistics, with worked examples for each.', '2025-11-24', 'MATH2087'),
('Model the real-world scenario below using linear algebra techniques and interpret your results.', '2025-11-28', 'MATH2087'),
('Produce a full requirements specification document for a ride-sharing system, including use cases and user stories.', '2025-01-21', 'SWEN2928'),
('Plan a two-week agile sprint for the e-learning project. Include a backlog, sprint goal, and burndown chart.', '2025-02-14', 'SWEN2928'),
('Write a dialogue in Mandarin between two people discussing family.', '2025-03-27', 'CHIN3353'),
('Answer the comprehension questions on the provided Mandarin reading passage.', '2025-04-16', 'CHIN3353'),
('Record yourself reading the provided Mandarin text aloud. Submit as an audio file.', '2025-04-23', 'CHIN3353'),
('Record a two-minute spoken response in Spanish describing the environment. Submit as an audio file.', '2025-10-05', 'SPAN3251'),
('Write a 500-word essay in Spanish on the topic of the environment. Focus on grammatical accuracy and vocabulary range.', '2025-10-18', 'SPAN3251'),
('Prepare a written dialogue in Spanish between two characters discussing the environment.', '2025-10-29', 'SPAN3251'),
('Translate the provided passage from English to Spanish, preserving tone and meaning.', '2025-11-12', 'SPAN3251'),
('Write a field report based on the coastal erosion site visit conducted in Week 5.', '2025-03-10', 'GEOL3439'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-03-19', 'GEOL3439'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-04-16', 'GEOL3439'),
('Research the geologic history of river deltas and write a two-page summary with cited sources.', '2025-04-28', 'GEOL3439'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-04-29', 'GEOL3439'),
('Implement a binary search tree in Python. Your solution must handle edge cases and include unit tests.', '2025-11-29', 'COMP1450'),
('Build a REST API with C++ that performs full CRUD operations on a networking dataset.', '2025-12-07', 'COMP1450'),
('Prepare a safety data summary for the reagents used in the spectroscopy lab and assess associated hazards.', '2025-04-04', 'CHEM3088'),
('Research and summarise the industrial applications of organic synthesis. Cite at least five peer-reviewed sources.', '2025-04-17', 'CHEM3088'),
('Write a formal lab report for the electrochemistry experiment conducted in Week 8. Follow the standard report format.', '2025-04-22', 'CHEM3088'),
('Complete the reaction mechanism worksheet for acid-base reactions. Clearly label all intermediates and arrow-pushing steps.', '2025-04-26', 'CHEM3088'),
('Model the real-world scenario below using discrete mathematics techniques and interpret your results.', '2025-10-03', 'MATH2278'),
('Write a short essay comparing two approaches to calculus, with worked examples for each.', '2025-11-10', 'MATH2278'),
('Solve the attached statistics problem set and verify your answers using any computational tool.', '2025-11-28', 'MATH2278'),
('Complete the problem set on number theory. Show all working - answers without justification will not receive credit.', '2025-12-04', 'MATH2278'),
('Prove the following number theory theorems using the methods covered in lectures.', '2025-12-11', 'MATH2278'),
('Critically evaluate two research papers on enzyme kinetics and compare their methodologies and conclusions.', '2025-02-11', 'BIOL2569'),
('Prepare a lab report on the enzyme kinetics experiment from Week 6. Include your hypothesis, results, and discussion.', '2025-03-22', 'BIOL2569'),
('Write an essay discussing the role of enzyme kinetics in human disease. Use at least six academic references.', '2025-04-08', 'BIOL2569'),
('Create an annotated diagram of the mitosis process, explaining each stage in your own words.', '2025-04-19', 'BIOL2569'),
('Complete the problem set on numerical methods. Show all working - answers without justification will not receive credit.', '2025-02-09', 'MATH1726'),
('Prove the following calculus theorems using the methods covered in lectures.', '2025-03-10', 'MATH1726'),
('Write a short essay comparing two approaches to linear algebra, with worked examples for each.', '2025-03-10', 'MATH1726'),
('Model the real-world scenario below using probability techniques and interpret your results.', '2025-03-20', 'MATH1726'),
('Solve the attached probability problem set and verify your answers using any computational tool.', '2025-03-31', 'MATH1726'),
('Write a formal lab report for the spectroscopy experiment conducted in Week 5. Follow the standard report format.', '2025-11-30', 'CHEM1799'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-12-01', 'CHEM1799'),
('Complete the reaction mechanism worksheet for spectroscopy. Clearly label all intermediates and arrow-pushing steps.', '2025-12-02', 'CHEM1799'),
('Refactor the given legacy codebase to follow SOLID principles. Document every change made.', '2025-02-11', 'COMP3228'),
('Analyse the time and space complexity of the provided compression algorithm. Write a report justifying your findings.', '2025-03-10', 'COMP3228'),
('Design and build a CLI application using Python. Submit source code and a README.', '2025-03-15', 'COMP3228'),
('Design a controlled experiment to investigate the effect of an environmental variable on the immune system.', '2025-11-18', 'BIOL3356'),
('Critically evaluate two research papers on the immune system and compare their methodologies and conclusions.', '2025-11-18', 'BIOL3356'),
('Write an essay discussing the role of enzyme kinetics in human disease. Use at least six academic references.', '2025-12-02', 'BIOL3356'),
('Analyse the experimental data provided using thermodynamics principles and present your conclusions.', '2025-03-25', 'PHYS1957'),
('Research a real-world application of electromagnetic induction and write a two-page technical summary.', '2025-03-29', 'PHYS1957'),
('Derive the equations of motion for the given quantum mechanics system from first principles.', '2025-03-29', 'PHYS1957'),
('Write a lab report for the wave optics experiment. Compare your results to the theoretical values and discuss errors.', '2025-04-04', 'PHYS1957'),
('Write a field report based on the fault systems site visit conducted in Week 6.', '2025-03-22', 'GEOL1338'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-04-17', 'GEOL1338'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-04-29', 'GEOL1338'),
('Design and build a microservice application using C++. Submit source code and a README.', '2025-09-07', 'COMP3445'),
('Analyse the time and space complexity of the provided compression algorithm. Write a report justifying your findings.', '2025-10-15', 'COMP3445'),
('Implement a stack in JavaScript. Your solution must handle edge cases and include unit tests.', '2025-11-08', 'COMP3445'),
('Build a REST API with JavaScript that performs full CRUD operations on a networking dataset.', '2025-11-19', 'COMP3445'),
('Refactor the given legacy codebase to follow SOLID principles. Document every change made.', '2025-12-13', 'COMP3445'),
('Implement a stack in C++. Your solution must handle edge cases and include unit tests.', '2025-02-23', 'COMP1624'),
('Analyse the time and space complexity of the provided pathfinding algorithm. Write a report justifying your findings.', '2025-03-20', 'COMP1624'),
('Build a REST API with Go that performs full CRUD operations on a concurrency dataset.', '2025-04-06', 'COMP1624'),
('Design and build a CLI application using Java. Submit source code and a README.', '2025-04-19', 'COMP1624'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-11-11', 'GEOL2129'),
('Write a field report based on the river deltas site visit conducted in Week 3.', '2025-11-29', 'GEOL2129'),
('Research the geologic history of river deltas and write a two-page summary with cited sources.', '2025-12-02', 'GEOL2129'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-12-07', 'GEOL2129'),
('Critically evaluate two research papers on mitosis and compare their methodologies and conclusions.', '2025-03-02', 'BIOL1935'),
('Write an essay discussing the role of the immune system in human disease. Use at least six academic references.', '2025-03-08', 'BIOL1935'),
('Design a controlled experiment to investigate the effect of an environmental variable on mitosis.', '2025-03-19', 'BIOL1935'),
('Using the provided dataset, perform exploratory data analysis and present your findings in a dashboard.', '2025-02-04', 'INFO1959'),
('Evaluate two competing ERP frameworks and recommend one for a given business scenario.', '2025-03-17', 'INFO1959'),
('Write a report analysing the information security risks facing a retail organisation.', '2025-04-23', 'INFO1959'),
('Research the geologic history of volcanic activity and write a two-page summary with cited sources.', '2025-09-26', 'GEOL2833'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-11-04', 'GEOL2833'),
('Write a field report based on the fault systems site visit conducted in Week 5.', '2025-12-01', 'GEOL2833'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-12-04', 'GEOL2833'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-12-13', 'GEOL2833');

INSERT INTO Assignment (a_desc, a_due_date, c_code) VALUES
('Analyse the experimental data provided using electromagnetic induction principles and present your conclusions.', '2025-03-24', 'PHYS3393'),
('Derive the equations of motion for the given electromagnetic induction system from first principles.', '2025-03-24', 'PHYS3393'),
('Write a lab report for the quantum mechanics experiment. Compare your results to the theoretical values and discuss errors.', '2025-04-10', 'PHYS3393'),
('Research a real-world application of quantum mechanics and write a two-page technical summary.', '2025-04-19', 'PHYS3393'),
('Write a short essay comparing two approaches to discrete mathematics, with worked examples for each.', '2025-11-21', 'MATH3004'),
('Model the real-world scenario below using discrete mathematics techniques and interpret your results.', '2025-11-28', 'MATH3004'),
('Solve the attached probability problem set and verify your answers using any computational tool.', '2025-12-02', 'MATH3004'),
('Prepare a lab report on the DNA replication experiment from Week 3. Include your hypothesis, results, and discussion.', '2025-03-05', 'BIOL1818'),
('Create an annotated diagram of the enzyme kinetics process, explaining each stage in your own words.', '2025-04-08', 'BIOL1818'),
('Write a dialogue in Japanese between two characters meeting for the first time.', '2025-11-04', 'JAPA2115'),
('Translate the provided passage from English into Japanese.', '2025-11-23', 'JAPA2115'),
('Record a spoken response in Japanese describing Japanese culture. Submit as an audio file.', '2025-11-26', 'JAPA2115'),
('Complete the grammar exercises for the structures covered in Weeks 3-6.', '2025-12-03', 'JAPA2115'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-10-10', 'GEOL2884'),
('Write a field report based on the fault systems site visit conducted in Week 3.', '2025-11-28', 'GEOL2884'),
('Model the real-world scenario below using numerical methods techniques and interpret your results.', '2025-10-23', 'MATH2153'),
('Write a short essay comparing two approaches to numerical methods, with worked examples for each.', '2025-12-01', 'MATH2153'),
('Critically evaluate two research papers on the immune system and compare their methodologies and conclusions.', '2025-09-22', 'BIOL3141'),
('Design a controlled experiment to investigate the effect of an environmental variable on cellular respiration.', '2025-11-11', 'BIOL3141'),
('Create an annotated diagram of the cellular respiration process, explaining each stage in your own words.', '2025-11-20', 'BIOL3141'),
('Write an essay discussing the role of the immune system in human disease. Use at least six academic references.', '2025-12-11', 'BIOL3141'),
('Analyse the time and space complexity of the provided compression algorithm. Write a report justifying your findings.', '2025-10-15', 'COMP3162'),
('Refactor the given legacy codebase to follow SOLID principles. Document every change made.', '2025-11-06', 'COMP3162'),
('Build a REST API with Go that performs full CRUD operations on a security dataset.', '2025-11-07', 'COMP3162'),
('Design and build a web application using JavaScript. Submit source code and a README.', '2025-11-22', 'COMP3162'),
('Prove the following linear algebra theorems using the methods covered in lectures.', '2025-10-13', 'MATH2933'),
('Complete the problem set on linear algebra. Show all working - answers without justification will not receive credit.', '2025-10-23', 'MATH2933'),
('Write a short essay comparing two approaches to linear algebra, with worked examples for each.', '2025-10-29', 'MATH2933'),
('Model the real-world scenario below using discrete mathematics techniques and interpret your results.', '2025-11-15', 'MATH2933'),
('Solve the attached numerical methods problem set and verify your answers using any computational tool.', '2025-11-19', 'MATH2933'),
('Analyse the experimental data provided using simple harmonic motion principles and present your conclusions.', '2025-02-15', 'PHYS1762'),
('Derive the equations of motion for the given wave optics system from first principles.', '2025-04-28', 'PHYS1762'),
('Research the geologic history of volcanic activity and write a two-page summary with cited sources.', '2025-09-30', 'GEOL1496'),
('Write a field report based on the volcanic activity site visit conducted in Week 4.', '2025-10-04', 'GEOL1496'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-10-31', 'GEOL1496'),
('Complete the grammar exercises for the structures covered in Weeks 4-5.', '2025-10-02', 'JAPA2339'),
('Record a spoken response in Japanese describing technology. Submit as an audio file.', '2025-11-25', 'JAPA2339'),
('Translate the provided passage from English into Japanese.', '2025-12-03', 'JAPA2339'),
('Research and summarise the industrial applications of electrochemistry. Cite at least five peer-reviewed sources.', '2025-09-20', 'CHEM3173'),
('Prepare a safety data summary for the reagents used in the spectroscopy lab and assess associated hazards.', '2025-10-24', 'CHEM3173'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-11-16', 'CHEM3173'),
('Write a formal lab report for the polymer chemistry experiment conducted in Week 3. Follow the standard report format.', '2025-12-11', 'CHEM3173'),
('Solve the quantum mechanics problem set. Include free-body diagrams where applicable.', '2025-09-15', 'PHYS1770'),
('Research a real-world application of quantum mechanics and write a two-page technical summary.', '2025-10-14', 'PHYS1770'),
('Analyse the experimental data provided using thermodynamics principles and present your conclusions.', '2025-11-13', 'PHYS1770'),
('Write a lab report for the simple harmonic motion experiment. Compare your results to the theoretical values and discuss errors.', '2025-11-19', 'PHYS1770'),
('Derive the equations of motion for the given quantum mechanics system from first principles.', '2025-11-25', 'PHYS1770'),
('Write a field report based on the sedimentary basins site visit conducted in Week 6.', '2025-03-12', 'GEOL2100'),
('Research the geologic history of coastal erosion and write a two-page summary with cited sources.', '2025-03-22', 'GEOL2100'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-04-01', 'GEOL2100'),
('Create an annotated diagram of the the immune system process, explaining each stage in your own words.', '2025-03-01', 'BIOL1757'),
('Design a controlled experiment to investigate the effect of an environmental variable on natural selection.', '2025-04-07', 'BIOL1757'),
('Critically evaluate two research papers on mitosis and compare their methodologies and conclusions.', '2025-04-09', 'BIOL1757'),
('Translate the provided passage from English to French, preserving tone and meaning.', '2025-10-23', 'FRENCH1079'),
('Write a formal letter in French responding to the scenario described in the case study.', '2025-10-27', 'FRENCH1079'),
('Analyse the grammatical structures in the provided French text and annotate them.', '2025-11-04', 'FRENCH1079'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-10-26', 'GEOL2031'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-11-10', 'GEOL2031'),
('Write a field report based on the fault systems site visit conducted in Week 4.', '2025-11-23', 'GEOL2031'),
('Complete the reaction mechanism worksheet for polymer chemistry. Clearly label all intermediates and arrow-pushing steps.', '2025-11-02', 'CHEM2495'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-11-16', 'CHEM2495'),
('Prepare a safety data summary for the reagents used in the organic synthesis lab and assess associated hazards.', '2025-12-09', 'CHEM2495'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-04-07', 'GEOL2890'),
('Research the geologic history of coastal erosion and write a two-page summary with cited sources.', '2025-04-14', 'GEOL2890'),
('Solve the simple harmonic motion problem set. Include free-body diagrams where applicable.', '2025-10-02', 'PHYS2096'),
('Write a lab report for the projectile motion experiment. Compare your results to the theoretical values and discuss errors.', '2025-10-04', 'PHYS2096'),
('Research a real-world application of quantum mechanics and write a two-page technical summary.', '2025-10-27', 'PHYS2096'),
('Analyse the experimental data provided using projectile motion principles and present your conclusions.', '2025-11-09', 'PHYS2096'),
('Prepare a lab report on the cellular respiration experiment from Week 4. Include your hypothesis, results, and discussion.', '2025-01-27', 'BIOL2143'),
('Design a controlled experiment to investigate the effect of an environmental variable on mitosis.', '2025-04-14', 'BIOL2143'),
('Write an essay discussing the role of DNA replication in human disease. Use at least six academic references.', '2025-04-18', 'BIOL2143'),
('Critically evaluate two research papers on the immune system and compare their methodologies and conclusions.', '2025-04-20', 'BIOL2143'),
('Create an annotated diagram of the DNA replication process, explaining each stage in your own words.', '2025-04-26', 'BIOL2143'),
('Analyse the grammatical structures in the provided French text and annotate them.', '2025-10-28', 'FRENCH1967'),
('Write a 500-word essay in French on the topic of French culture. Pay attention to agreement and verb conjugation.', '2025-11-10', 'FRENCH1967'),
('Record a two-minute spoken response in French on daily routines. Submit as an audio file.', '2025-11-28', 'FRENCH1967'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-02-20', 'GEOL1402'),
('Research the geologic history of sedimentary basins and write a two-page summary with cited sources.', '2025-02-25', 'GEOL1402'),
('Write a field report based on the river deltas site visit conducted in Week 6.', '2025-04-05', 'GEOL1402'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-04-21', 'GEOL1402'),
('Write a short essay in Japanese on the topic of Japanese culture. Minimum 200 characters.', '2025-02-23', 'JAPA3108'),
('Translate the provided passage from English into Japanese.', '2025-03-02', 'JAPA3108'),
('Complete the grammar exercises for the structures covered in Weeks 4-7.', '2025-03-16', 'JAPA3108'),
('Write a dialogue in Japanese between two characters meeting for the first time.', '2025-04-12', 'JAPA3108'),
('Record a spoken response in Japanese describing travel. Submit as an audio file.', '2025-04-19', 'JAPA3108'),
('Translate the provided passage from English into Japanese.', '2025-11-13', 'JAPA2151'),
('Complete the grammar exercises for the structures covered in Weeks 5-7.', '2025-12-03', 'JAPA2151'),
('Write a field report based on the fault systems site visit conducted in Week 3.', '2025-04-02', 'GEOL3084'),
('Research the geologic history of volcanic activity and write a two-page summary with cited sources.', '2025-04-07', 'GEOL3084'),
('Critically evaluate two research papers on enzyme kinetics and compare their methodologies and conclusions.', '2025-11-09', 'BIOL2803'),
('Design a controlled experiment to investigate the effect of an environmental variable on mitosis.', '2025-11-19', 'BIOL2803'),
('Create an annotated diagram of the mitosis process, explaining each stage in your own words.', '2025-11-26', 'BIOL2803'),
('Prepare a lab report on the cellular respiration experiment from Week 6. Include your hypothesis, results, and discussion.', '2025-12-04', 'BIOL2803'),
('Write an essay discussing the role of DNA replication in human disease. Use at least six academic references.', '2025-11-20', 'BIOL1804'),
('Prepare a lab report on the the immune system experiment from Week 6. Include your hypothesis, results, and discussion.', '2025-11-22', 'BIOL1804'),
('Design a controlled experiment to investigate the effect of an environmental variable on mitosis.', '2025-11-30', 'BIOL1804'),
('Critically evaluate two research papers on DNA replication and compare their methodologies and conclusions.', '2025-12-03', 'BIOL1804'),
('Write a lab report for the electromagnetic induction experiment. Compare your results to the theoretical values and discuss errors.', '2025-02-26', 'PHYS2196'),
('Analyse the experimental data provided using simple harmonic motion principles and present your conclusions.', '2025-03-05', 'PHYS2196'),
('Research a real-world application of simple harmonic motion and write a two-page technical summary.', '2025-03-31', 'PHYS2196'),
('Derive the equations of motion for the given quantum mechanics system from first principles.', '2025-04-07', 'PHYS2196'),
('Solve the quantum mechanics problem set. Include free-body diagrams where applicable.', '2025-04-28', 'PHYS2196'),
('Design a controlled experiment to investigate the effect of an environmental variable on enzyme kinetics.', '2025-11-08', 'BIOL2711'),
('Create an annotated diagram of the mitosis process, explaining each stage in your own words.', '2025-11-11', 'BIOL2711'),
('Write an essay discussing the role of enzyme kinetics in human disease. Use at least six academic references.', '2025-11-22', 'BIOL2711'),
('Critically evaluate two research papers on the immune system and compare their methodologies and conclusions.', '2025-12-04', 'BIOL2711'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-03-10', 'GEOL2731'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-03-15', 'GEOL2731'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-03-26', 'GEOL2731'),
('Write a field report based on the river deltas site visit conducted in Week 4.', '2025-03-30', 'GEOL2731'),
('Analyse the experimental data provided using quantum mechanics principles and present your conclusions.', '2025-03-02', 'PHYS2028'),
('Derive the equations of motion for the given thermodynamics system from first principles.', '2025-03-06', 'PHYS2028'),
('Solve the projectile motion problem set. Include free-body diagrams where applicable.', '2025-03-07', 'PHYS2028'),
('Research a real-world application of wave optics and write a two-page technical summary.', '2025-04-11', 'PHYS2028'),
('Write a lab report for the electromagnetic induction experiment. Compare your results to the theoretical values and discuss errors.', '2025-04-17', 'PHYS2028'),
('Write a field report based on the coastal erosion site visit conducted in Week 3.', '2025-09-21', 'GEOL1368'),
('Research the geologic history of volcanic activity and write a two-page summary with cited sources.', '2025-10-22', 'GEOL1368'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-11-05', 'GEOL1368'),
('Analyse the rock samples provided in lab and classify them with justification.', '2025-11-20', 'GEOL1368'),
('Complete the mineral identification worksheet and submit with labelled photographs.', '2025-11-23', 'GEOL1368'),
('Analyse the time and space complexity of the provided pathfinding algorithm. Write a report justifying your findings.', '2025-02-13', 'COMP2513'),
('Design and build a desktop application using C++. Submit source code and a README.', '2025-03-18', 'COMP2513'),
('Implement a stack in Go. Your solution must handle edge cases and include unit tests.', '2025-03-21', 'COMP2513'),
('Build a REST API with JavaScript that performs full CRUD operations on a networking dataset.', '2025-04-22', 'COMP2513'),
('Design a controlled experiment to investigate the effect of an environmental variable on the immune system.', '2025-09-02', 'BIOL3040'),
('Critically evaluate two research papers on DNA replication and compare their methodologies and conclusions.', '2025-10-23', 'BIOL3040'),
('Prepare a lab report on the cellular respiration experiment from Week 5. Include your hypothesis, results, and discussion.', '2025-11-02', 'BIOL3040'),
('Write an essay discussing the role of the immune system in human disease. Use at least six academic references.', '2025-12-11', 'BIOL3040'),
('Write a formal letter in French responding to the scenario described in the case study.', '2025-11-02', 'FRENCH2966'),
('Record a two-minute spoken response in French on the environment. Submit as an audio file.', '2025-11-18', 'FRENCH2966'),
('Write a 500-word essay in French on the topic of travel. Pay attention to agreement and verb conjugation.', '2025-12-09', 'FRENCH2966'),
('Analyse the grammatical structures in the provided French text and annotate them.', '2025-12-11', 'FRENCH2966'),
('Write a 500-word essay in French on the topic of technology. Pay attention to agreement and verb conjugation.', '2025-02-15', 'FRENCH2116'),
('Record a two-minute spoken response in French on the environment. Submit as an audio file.', '2025-03-12', 'FRENCH2116'),
('Write a formal letter in French responding to the scenario described in the case study.', '2025-03-14', 'FRENCH2116'),
('Translate the provided passage from English to French, preserving tone and meaning.', '2025-03-29', 'FRENCH2116'),
('Analyse the grammatical structures in the provided French text and annotate them.', '2025-04-22', 'FRENCH2116'),
('Produce a full requirements specification document for a hospital management system, including use cases and user stories.', '2025-02-12', 'SWEN1583'),
('Perform a code review of the provided pull request. Submit written feedback addressing style, logic, and security.', '2025-03-08', 'SWEN1583'),
('Plan a two-week agile sprint for the hospital management project. Include a backlog, sprint goal, and burndown chart.', '2025-04-12', 'SWEN1583'),
('Write a test plan and execute test cases for the provided mobile banking application. Submit a defect report.', '2025-04-12', 'SWEN1583'),
('Create a UML class diagram and sequence diagram for the retail system described in the case study.', '2025-04-16', 'SWEN1583'),
('Model the real-world scenario below using linear algebra techniques and interpret your results.', '2025-09-09', 'MATH2739'),
('Solve the attached number theory problem set and verify your answers using any computational tool.', '2025-10-12', 'MATH2739'),
('Prove the following discrete mathematics theorems using the methods covered in lectures.', '2025-11-30', 'MATH2739'),
('Complete the problem set on probability. Show all working - answers without justification will not receive credit.', '2025-12-12', 'MATH2739'),
('Write a short essay comparing two approaches to number theory, with worked examples for each.', '2025-09-18', 'MATH1554'),
('Model the real-world scenario below using discrete mathematics techniques and interpret your results.', '2025-11-11', 'MATH1554'),
('Prove the following numerical methods theorems using the methods covered in lectures.', '2025-11-23', 'MATH1554'),
('Solve the attached discrete mathematics problem set and verify your answers using any computational tool.', '2025-12-02', 'MATH1554'),
('Build a REST API with Go that performs full CRUD operations on a concurrency dataset.', '2025-10-28', 'COMP1382'),
('Design and build a microservice application using JavaScript. Submit source code and a README.', '2025-12-06', 'COMP1382'),
('Build a REST API with Java that performs full CRUD operations on a memory management dataset.', '2025-02-08', 'COMP1093'),
('Design and build a CLI application using JavaScript. Submit source code and a README.', '2025-02-18', 'COMP1093'),
('Analyse the time and space complexity of the provided sorting algorithm. Write a report justifying your findings.', '2025-02-19', 'COMP1093'),
('Refactor the given legacy codebase to follow SOLID principles. Document every change made.', '2025-04-15', 'COMP1093'),
('Implement a hash map in C++. Your solution must handle edge cases and include unit tests.', '2025-04-21', 'COMP1093'),
('Prove the following discrete mathematics theorems using the methods covered in lectures.', '2025-10-29', 'MATH1790'),
('Model the real-world scenario below using number theory techniques and interpret your results.', '2025-11-11', 'MATH1790'),
('Solve the attached statistics problem set and verify your answers using any computational tool.', '2025-11-27', 'MATH1790'),
('Write a short essay comparing two approaches to statistics, with worked examples for each.', '2025-09-20', 'MATH3224'),
('Complete the problem set on statistics. Show all working - answers without justification will not receive credit.', '2025-10-16', 'MATH3224'),
('Model the real-world scenario below using number theory techniques and interpret your results.', '2025-11-30', 'MATH3224'),
('Design a controlled experiment to investigate the effect of an environmental variable on DNA replication.', '2025-02-21', 'BIOL3492'),
('Create an annotated diagram of the natural selection process, explaining each stage in your own words.', '2025-04-17', 'BIOL3492'),
('Write a lab report for the thermodynamics experiment. Compare your results to the theoretical values and discuss errors.', '2025-02-05', 'PHYS1308'),
('Analyse the experimental data provided using quantum mechanics principles and present your conclusions.', '2025-02-12', 'PHYS1308'),
('Record a two-minute spoken response in French on daily routines. Submit as an audio file.', '2025-03-04', 'FRENCH1179'),
('Analyse the grammatical structures in the provided French text and annotate them.', '2025-03-17', 'FRENCH1179'),
('Translate the provided passage from English to French, preserving tone and meaning.', '2025-04-23', 'FRENCH1179'),
('Write an essay discussing the role of natural selection in human disease. Use at least six academic references.', '2025-01-31', 'BIOL3377'),
('Create an annotated diagram of the cellular respiration process, explaining each stage in your own words.', '2025-02-01', 'BIOL3377'),
('Critically evaluate two research papers on mitosis and compare their methodologies and conclusions.', '2025-03-16', 'BIOL3377'),
('Prepare a lab report on the natural selection experiment from Week 6. Include your hypothesis, results, and discussion.', '2025-04-13', 'BIOL3377'),
('Design a controlled experiment to investigate the effect of an environmental variable on the immune system.', '2025-04-19', 'BIOL3377'),
('Solve the attached probability problem set and verify your answers using any computational tool.', '2025-03-23', 'MATH3490'),
('Prove the following discrete mathematics theorems using the methods covered in lectures.', '2025-03-27', 'MATH3490'),
('Complete the problem set on statistics. Show all working - answers without justification will not receive credit.', '2025-04-12', 'MATH3490'),
('Prepare a lab report on the the immune system experiment from Week 6. Include your hypothesis, results, and discussion.', '2025-10-08', 'BIOL1530'),
('Design a controlled experiment to investigate the effect of an environmental variable on natural selection.', '2025-10-26', 'BIOL1530'),
('Critically evaluate two research papers on the immune system and compare their methodologies and conclusions.', '2025-11-17', 'BIOL1530'),
('Write an essay discussing the role of mitosis in human disease. Use at least six academic references.', '2025-12-05', 'BIOL1530'),
('Create an annotated diagram of the cellular respiration process, explaining each stage in your own words.', '2025-12-09', 'BIOL1530'),
('Write a formal lab report for the organic synthesis experiment conducted in Week 7. Follow the standard report format.', '2025-03-03', 'CHEM3138'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-03-08', 'CHEM3138'),
('Complete the reaction mechanism worksheet for polymer chemistry. Clearly label all intermediates and arrow-pushing steps.', '2025-04-05', 'CHEM3138'),
('Research and summarise the industrial applications of electrochemistry. Cite at least five peer-reviewed sources.', '2025-04-22', 'CHEM3138'),
('Build a REST API with JavaScript that performs full CRUD operations on a memory management dataset.', '2025-10-07', 'COMP2730'),
('Design and build a CLI application using Java. Submit source code and a README.', '2025-11-02', 'COMP2730'),
('Refactor the given legacy codebase to follow SOLID principles. Document every change made.', '2025-11-04', 'COMP2730'),
('Implement a graph in Go. Your solution must handle edge cases and include unit tests.', '2025-11-22', 'COMP2730'),
('Analyse the time and space complexity of the provided searching algorithm. Write a report justifying your findings.', '2025-11-26', 'COMP2730'),
('Interpret the geological map provided and produce a cross-section with annotations.', '2025-02-03', 'GEOL1581'),
('Write a field report based on the river deltas site visit conducted in Week 4.', '2025-04-16', 'GEOL1581'),
('Model the real-world scenario below using statistics techniques and interpret your results.', '2025-03-27', 'MATH2071'),
('Complete the problem set on calculus. Show all working - answers without justification will not receive credit.', '2025-04-22', 'MATH2071'),
('Analyse the spectroscopic data provided and identify the unknown compound. Justify your identification.', '2025-10-25', 'CHEM2318'),
('Write a formal lab report for the polymer chemistry experiment conducted in Week 8. Follow the standard report format.', '2025-11-02', 'CHEM2318'),
('Research and summarise the industrial applications of acid-base reactions. Cite at least five peer-reviewed sources.', '2025-11-29', 'CHEM2318'),
('Write an essay discussing the role of cellular respiration in human disease. Use at least six academic references.', '2025-03-15', 'BIOL1791'),
('Create an annotated diagram of the the immune system process, explaining each stage in your own words.', '2025-03-27', 'BIOL1791'),
('Critically evaluate two research papers on enzyme kinetics and compare their methodologies and conclusions.', '2025-04-04', 'BIOL1791'),
('Prepare a lab report on the DNA replication experiment from Week 4. Include your hypothesis, results, and discussion.', '2025-04-21', 'BIOL1791');

