-- CALENDAR EVENT INSERTS
INSERT INTO CalendarEvent (event_name, details, event_date, c_code) VALUES
('Introduction to Statistics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-20', 'MATH2300'),
('Chapter Quiz: Numerical Methods', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-10-03', 'MATH2300'),
('Week 12 Tutorial - Numerical Methods', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-27', 'MATH2300'),
('Unit 1 Test - Probability', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-11-22', 'MATH2300'),
('Week 10 Tutorial - Probability', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-12-10', 'MATH2300'),
('Introduction to French Grammar', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-17', 'FRENCH1586'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-11-14', 'PHYS1266'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-11-16', 'PHYS1266'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-01-13', 'JAPA1692'),
('Laboratory: Oral Expression', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-03-06', 'JAPA1692'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-09-24', 'PHYS1990'),
('Tutorial: Thermodynamics Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-26', 'PHYS1990'),
('Unit 1 Test - Electromagnetism', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-11-07', 'PHYS1990'),
('Week 13 Lecture - Spanish Grammar', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-13', 'SPAN1013'),
('Written Composition: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-13', 'SPAN1013'),
('Unit 1 Test - Spanish Grammar', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-11-27', 'SPAN1013'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-12-01', 'SPAN1013'),
('Introduction to Ecology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-13', 'BIOL1674'),
('Tutorial: Ecology Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-21', 'BIOL1674'),
('Week 7 Tutorial - Microbiology', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-15', 'BIOL1674'),
('Laboratory: Cell Biology', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-03-31', 'BIOL1674'),
('Ecology Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-28', 'BIOL1674'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-01-20', 'CHIN3331'),
('Unit 1 Test - Reading Comprehension', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-02-15', 'CHIN3331'),
('Week 1 Lecture - Hispanic Literature', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-26', 'SPAN2889'),
('Lab Session 1 - Inorganic Chemistry', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-02-15', 'CHEM1330'),
('Organic Chemistry: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-02', 'CHEM1330'),
('Week 2 Lecture - Numerical Methods', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-08', 'MATH1116'),
('Quiz 1 - Discrete Mathematics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-10-01', 'MATH1116'),
('Probability Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-14', 'MATH1116'),
('Chapter Quiz: Discrete Mathematics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-12-09', 'MATH1116'),
('Tutorial: Structural Geology Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-30', 'GEOL1664'),
('Week 12 Tutorial - Geophysics', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-05', 'GEOL1664'),
('Week 2 Tutorial - Mineralogy', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-10', 'GEOL1664'),
('Petrology Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-25', 'GEOL1664'),
('Week 7 Tutorial - Microbiology', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-08', 'BIOL1341'),
('Week 3 Tutorial - Microbiology', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-16', 'BIOL1341'),
('Genetics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-13', 'BIOL1341'),
('Ecology In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-12-12', 'BIOL1341'),
('Written Composition: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-11', 'SPAN2282'),
('Week 6 Tutorial - Oral Expression', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-04', 'SPAN2282'),
('Unit 1 Test - Spanish Grammar', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-04-11', 'SPAN2282'),
('Introduction to Spanish Grammar', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-31', 'SPAN2699'),
('Week 10 Lecture - French Grammar', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-01', 'FRENCH1558'),
('Chapter Quiz: Listening Comprehension', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-11-12', 'FRENCH1558'),
('Chapter Quiz: Mechanics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-01-24', 'PHYS3306'),
('Quantum Physics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-02', 'PHYS3306'),
('Week 1 Tutorial - Quantum Physics', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-13', 'PHYS3306'),
('Week 2 Lecture - Quantum Physics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-23', 'PHYS3306'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-04-22', 'PHYS3306'),
('Introduction to Microbiology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-23', 'BIOL3106'),
('Quiz 1 - Ecology', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-03-11', 'BIOL3106'),
('Quiz 2 - Microbiology', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-03-18', 'BIOL3106'),
('Week 9 Lecture - Written Composition', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-09', 'FRENCH1916'),
('Week 5 Tutorial - IT Project Management', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-24', 'INFO1150'),
('Introduction to Data Analytics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-28', 'INFO1150'),
('Linear Algebra: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-15', 'MATH2236'),
('Numerical Methods: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-14', 'MATH2236'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-12-12', 'BIOL2364'),
('Week 12 Lecture - Earth History', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-20', 'GEOL2984'),
('Laboratory: Mineralogy', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-02-15', 'GEOL2984'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-03-24', 'GEOL1927'),
('Introduction to Petrology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-26', 'GEOL1927'),
('Week 12 Lecture - Structural Geology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-11', 'GEOL1927'),
('Structural Geology In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-04-21', 'GEOL1927'),
('Week 5 Lecture - Mineralogy', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-28', 'GEOL1015'),
('Tutorial: Earth History Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-10', 'GEOL1015'),
('Week 1 Lecture - Petrology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-19', 'GEOL1015'),
('Earth History Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-28', 'GEOL1015'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-09-17', 'BIOL2128'),
('Tutorial: Genetics Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-03', 'BIOL2128'),
('Introduction to Microbiology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-09', 'BIOL2128'),
('Week 10 Tutorial - Organic Chemistry', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-11', 'CHEM2751'),
('Spectroscopy Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-17', 'CHEM2751'),
('Thermochemistry: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-13', 'CHEM2751'),
('Tutorial: Inorganic Chemistry Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-07', 'CHEM2787'),
('Thermochemistry: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-22', 'CHEM2787'),
('Chapter Quiz: Analytical Methods', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-12-14', 'CHEM2787'),
('Introduction to Organic Chemistry', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-09', 'CHEM2035'),
('Tutorial: Spectroscopy Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-30', 'CHEM2035'),
('Tutorial: Inorganic Chemistry Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-12-08', 'CHEM2035'),
('Week 9 Tutorial - Inorganic Chemistry', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-12-15', 'CHEM2035'),
('Laboratory: Requirements Engineering', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-01-30', 'SWEN2456'),
('Tutorial: Software Design Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-09', 'SWEN2456'),
('Requirements Engineering: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-11', 'SWEN2456'),
('Genetics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-07', 'BIOL2329'),
('Tutorial: Human Biology Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-03', 'BIOL2329'),
('Laboratory: Electromagnetism', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-02-12', 'PHYS3052'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-02-16', 'PHYS3052'),
('Week 2 Tutorial - Quantum Physics', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-23', 'PHYS2478'),
('Tutorial: Thermodynamics Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-16', 'PHYS2478'),
('Thermodynamics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-19', 'PHYS2478'),
('Week 13 Tutorial - Probability', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-19', 'MATH1762'),
('Unit 1 Test - Calculus', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-04-15', 'MATH1762'),
('Tutorial: Thermodynamics Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-09', 'PHYS1134'),
('Chapter Quiz: Statistics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-03-01', 'MATH2398'),
('Calculus Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-06', 'MATH2398'),
('Unit 1 Test - Linear Algebra', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-03-18', 'MATH2398'),
('Week 10 Lecture - Probability', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-05', 'MATH2398'),
('Agile Methods In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-09-07', 'SWEN1786'),
('Introduction to Requirements Engineering', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-06', 'SWEN1786'),
('Week 13 Tutorial - Software Testing', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-11', 'SWEN1786'),
('Agile Methods Practical', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-11-15', 'SWEN1786'),
('Requirements Engineering: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-01', 'SWEN1786'),
('Organic Chemistry: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-01', 'CHEM2153'),
('Inorganic Chemistry: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-22', 'CHEM2153'),
('Introduction to Inorganic Chemistry', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-19', 'CHEM2153'),
('Organic Chemistry Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-29', 'CHEM2153'),
('Spectroscopy Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-27', 'CHEM2153'),
('Tutorial: Thermodynamics Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-07', 'PHYS2502'),
('Thermodynamics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-31', 'PHYS2502'),
('Quantum Physics Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-11', 'PHYS2502'),
('Week 4 Lecture - Electromagnetism', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-13', 'PHYS2502'),
('Week 10 Lecture - Linear Algebra', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-15', 'MATH1437'),
('Microbiology Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-10', 'BIOL1621'),
('Verb Conjugation In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-09-16', 'SPAN2427'),
('Laboratory: Oral Expression', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-10-13', 'SPAN2427'),
('Week 13 Lecture - Wave Optics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-12', 'PHYS3493'),
('Introduction to Wave Optics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-13', 'PHYS3493'),
('Wave Optics In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-12-08', 'PHYS3493'),
('Software Design: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-04', 'SWEN2103'),
('Quiz 1 - Software Design', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-10-10', 'SWEN2103'),
('Lecturer Office Hours - Week 10', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-10-13', 'SWEN2103'),
('Week 13 Lecture - Software Testing', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-30', 'SWEN2103'),
('Lecturer Office Hours - Week 8', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-12-07', 'SWEN2103'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-10-03', 'CHEM2758'),
('Introduction to Spectroscopy', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-07', 'CHEM2758'),
('Week 4 Tutorial - Thermochemistry', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-17', 'CHEM2758'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-11-29', 'CHEM2758'),
('Week 6 Tutorial - Mineralogy', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-05', 'GEOL1110'),
('Week 4 Lecture - Earth History', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-13', 'GEOL1110'),
('Petrology Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-15', 'GEOL1110'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-02-27', 'GEOL1110'),
('Week 1 Lecture - Structural Geology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-25', 'GEOL1110'),
('Week 10 Lecture - Wave Optics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-26', 'PHYS1823'),
('Introduction to Wave Optics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-12', 'PHYS1823'),
('Tutorial: Genetics Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-14', 'BIOL1825'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-02-25', 'BIOL1825'),
('Tutorial: Cell Biology Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-03', 'BIOL1825'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-04-10', 'BIOL1825'),
('Introduction to Cell Biology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-16', 'BIOL1825'),
('Chapter Quiz: Oral Expression', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-01-31', 'CHIN2420'),
('Wave Optics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-17', 'PHYS1665'),
('Thermodynamics In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-04-07', 'PHYS1665'),
('Week 12 Lecture - Wave Optics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-07', 'PHYS2266'),
('Tutorial: Mechanics Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-17', 'PHYS2266'),
('Thermodynamics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-01', 'PHYS2266'),
('Thermodynamics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-26', 'PHYS2266'),
('Inorganic Chemistry: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-05', 'CHEM3059'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-11-07', 'CHEM2637'),
('Week 1 Tutorial - Spectroscopy', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-10', 'CHEM2637'),
('Computer Architecture: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-25', 'COMP1723'),
('Tutorial: Computer Architecture Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-10', 'COMP1723'),
('Quiz 1 - Databases', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-03-31', 'COMP1723'),
('Tutorial: Wave Optics Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-11', 'PHYS1095'),
('Thermodynamics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-21', 'PHYS1095'),
('Electromagnetism Practical', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-12-02', 'PHYS1095'),
('Introduction to Mechanics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-23', 'PHYS2293'),
('Week 9 Lecture - Wave Optics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-03', 'PHYS2293'),
('Requirements Engineering Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-21', 'SWEN2287'),
('Tutorial: Software Testing Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-21', 'SWEN2287'),
('Quiz 1 - Software Testing', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-03-27', 'SWEN2287'),
('Requirements Engineering: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-31', 'SWEN2287'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-04-27', 'SWEN2287'),
('Quiz 1 - Written Composition', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-09-01', 'SPAN1451'),
('Oral Expression Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-10', 'SPAN1451'),
('Tutorial: Verb Conjugation Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-19', 'SPAN1451'),
('Oral Expression Practical', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-10-31', 'SPAN1451'),
('Quiz 2 - Verb Conjugation', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-11-27', 'SPAN1451'),
('Week 2 Tutorial - Verb Conjugation', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-21', 'SPAN3252'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-03-17', 'SPAN3252'),
('Oral Expression Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-03', 'SPAN3252'),
('Chapter Quiz: Quantum Physics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-10-01', 'PHYS2311'),
('Lecturer Office Hours - Week 8', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-11-10', 'PHYS2311'),
('Chapter Quiz: Electromagnetism', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-12-04', 'PHYS2311'),
('Spectroscopy: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-13', 'CHEM1328'),
('Introduction to Spectroscopy', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-03', 'CHEM1328'),
('Chapter Quiz: Inorganic Chemistry', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-10-23', 'CHEM1328'),
('Introduction to Thermochemistry', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-13', 'CHEM1328'),
('Spectroscopy In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-12-13', 'CHEM1328'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-01-21', 'MATH2336'),
('Week 2 Lecture - Probability', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-23', 'MATH2336'),
('Introduction to Statistics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-25', 'MATH2336'),
('Chapter Quiz: Statistics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-04-18', 'MATH2336'),
('Ecology: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-10', 'BIOL3113'),
('Genetics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-12', 'BIOL3113'),
('Week 7 Tutorial - Ecology', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-09', 'BIOL3113'),
('Quiz 1 - Cell Biology', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-09-12', 'BIOL2124'),
('Lecturer Office Hours - Week 9', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-09-28', 'BIOL2124'),
('Human Biology: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-15', 'BIOL2124'),
('Unit 1 Test - Genetics', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-10-21', 'BIOL2124'),
('Ecology: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-08', 'BIOL2124'),
('Introduction to Wave Optics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-28', 'PHYS3432'),
('Wave Optics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-29', 'PHYS3432'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-01-14', 'BIOL2536'),
('Cell Biology Practical', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-04-07', 'BIOL2536'),
('Introduction to Wave Optics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-08', 'PHYS2109'),
('Wave Optics Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-05', 'PHYS2109'),
('Mechanics In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-03-08', 'PHYS2109'),
('Unit 1 Test - Quantum Physics', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-04-26', 'PHYS2109'),
('Tutorial: Electromagnetism Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-06', 'PHYS2275'),
('Week 2 Lecture - Quantum Physics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-28', 'PHYS2275'),
('Spanish Grammar Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-26', 'SPAN1574'),
('Week 2 Lecture - Written Composition', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-28', 'SPAN1574'),
('Introduction to Analytical Methods', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-12', 'CHEM2654'),
('Week 13 Lecture - Thermochemistry', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-11', 'CHEM2846'),
('Cell Biology In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-01-25', 'BIOL1380'),
('Chapter Quiz: Microbiology', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-02-25', 'BIOL1380'),
('Week 5 Lecture - Wave Optics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-19', 'PHYS1187'),
('Tutorial: Thermodynamics Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-25', 'PHYS1187'),
('Tutorial: Thermodynamics Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-09', 'PHYS1187'),
('Data Structures: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-25', 'COMP2715'),
('Databases: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-30', 'COMP2715'),
('Introduction to Data Analytics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-01', 'INFO3101'),
('Unit 1 Test - IT Project Management', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-09-19', 'INFO3101'),
('Laboratory: Information Security', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-09-25', 'INFO3101'),
('Introduction to Information Security', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-05', 'INFO3101'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-09-13', 'SPAN2900'),
('Week 7 Lecture - Spanish Grammar', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-08', 'SPAN2900'),
('Week 10 Tutorial - Hispanic Literature', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-31', 'SPAN2900'),
('Quiz 1 - Algorithms', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-10-08', 'COMP2343'),
('Week 8 Lecture - Algorithms', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-06', 'COMP2343'),
('Databases: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-09', 'COMP2343'),
('Kanji Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-08', 'JAPA2549'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-01-25', 'JAPA2549'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-02-15', 'JAPA2549'),
('Introduction to Kanji', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-06', 'JAPA2549'),
('Tutorial: Spectroscopy Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-08', 'CHEM1249'),
('Introduction to Spectroscopy', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-12', 'CHEM2113'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-02-19', 'CHEM2113'),
('Quiz 1 - Inorganic Chemistry', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-03-04', 'CHEM2113'),
('Week 11 Lecture - Thermochemistry', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-27', 'CHEM2113'),
('Tutorial: Analytical Methods Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-27', 'CHEM2113'),
('Week 2 Lecture - Linear Algebra', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-26', 'MATH2263'),
('Week 7 Lecture - IT Project Management', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-24', 'INFO1373'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-02-21', 'INFO1373'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-03-12', 'INFO1373'),
('Laboratory: Database Design', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-04-07', 'INFO1373'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-02-16', 'MATH1069'),
('Week 5 Lecture - Probability', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-19', 'MATH1069'),
('Introduction to Numerical Methods', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-22', 'MATH1069'),
('Introduction to Software Engineering', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-03', 'COMP3369'),
('Laboratory: Organic Chemistry', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-09-03', 'CHEM1456'),
('Week 2 Lecture - Inorganic Chemistry', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-08', 'CHEM1456'),
('Organic Chemistry: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-19', 'CHEM1456'),
('Introduction to Analytical Methods', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-18', 'CHEM1456'),
('Genetics In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-03-06', 'BIOL2714'),
('Thermodynamics Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-27', 'PHYS3390'),
('Tutorial: Wave Optics Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-07', 'PHYS3390'),
('Week 1 Lecture - Electromagnetism', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-12', 'PHYS3390'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-11-21', 'PHYS3390'),
('Organic Chemistry: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-04', 'CHEM2316'),
('Week 2 Tutorial - Statistics', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-21', 'MATH3342'),
('Week 13 Tutorial - Calculus', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-18', 'MATH3342'),
('Quiz 1 - Quantum Physics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-11-23', 'PHYS2434'),
('Introduction to Quantum Physics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-07', 'PHYS2434'),
('Organic Chemistry In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-11-27', 'CHEM3131'),
('Week 12 Tutorial - Spectroscopy', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-12-12', 'CHEM3131'),
('Laboratory: Cell Biology', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-02-01', 'BIOL3331'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-03-01', 'BIOL3331'),
('Introduction to Ecology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-22', 'BIOL3331'),
('Introduction to Cell Biology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-23', 'BIOL3331'),
('Microbiology In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-04-25', 'BIOL3331'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-03-04', 'PHYS3298'),
('Quiz 1 - Human Biology', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-01-27', 'BIOL2747'),
('Introduction to Genetics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-21', 'BIOL2747'),
('Written Composition: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-11', 'FRENCH2200'),
('Week 4 Lecture - Francophone Literature', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-14', 'FRENCH2200'),
('Lab Session 1 - Listening Comprehension', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-02-14', 'FRENCH2200'),
('Quiz 1 - Ecology', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-10-14', 'BIOL1712'),
('Week 8 Lecture - Genetics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-30', 'BIOL1712'),
('Introduction to Cell Biology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-14', 'BIOL1712'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-01-23', 'INFO1371'),
('Business Intelligence In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-02-12', 'INFO1371'),
('Week 10 Lecture - IT Project Management', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-14', 'INFO1371'),
('Introduction to IT Project Management', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-19', 'INFO1371'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-03-03', 'INFO1371'),
('Probability Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-25', 'MATH2114'),
('Tutorial: Database Design Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-13', 'INFO1664'),
('Quiz 1 - Database Design', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-11-12', 'INFO1664'),
('Week 11 Lecture - Information Security', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-27', 'INFO1664'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-12-03', 'INFO1664'),
('Lecturer Office Hours - Week 7', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-03-21', 'GEOL1400'),
('Introduction to Structural Geology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-25', 'GEOL1400'),
('Chapter Quiz: Petrology', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-04-05', 'GEOL1400'),
('Chapter Quiz: Discrete Mathematics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-09-27', 'MATH1910'),
('Lecturer Office Hours - Week 9', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-09-05', 'CHEM2949'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-09-06', 'CHEM2949'),
('Inorganic Chemistry Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-30', 'CHEM2949'),
('Week 8 Lecture - Spectroscopy', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-08', 'CHEM2949'),
('Introduction to Spectroscopy', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-09', 'CHEM2949'),
('Introduction to Wave Optics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-14', 'PHYS1272'),
('Electromagnetism Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-29', 'PHYS1272'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-09-22', 'COMP2471'),
('Week 8 Lecture - Databases', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-25', 'COMP2471'),
('Introduction to Networking', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-15', 'COMP2471'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-10-20', 'COMP2471'),
('Introduction to Verb Conjugation', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-09', 'SPAN2626'),
('Quiz 1 - Written Composition', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-04-08', 'SPAN2626'),
('Petrology: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-13', 'GEOL3241'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-10-08', 'GEOL3241'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-11-04', 'GEOL3241'),
('Mineralogy: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-02', 'GEOL3241'),
('Geophysics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-03', 'GEOL3241'),
('Tutorial: Quantum Physics Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-29', 'PHYS2095'),
('Unit 3 Test - Wave Optics', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-02-16', 'PHYS2095'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-03-16', 'PHYS2095'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-04-07', 'PHYS2095'),
('Introduction to Thermodynamics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-14', 'PHYS2095'),
('Character Writing: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-12', 'CHIN1469'),
('Quiz 1 - Hiragana & Katakana', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-01-29', 'JAPA1276'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-02-13', 'JAPA1276'),
('Week 8 Lecture - Japanese Culture', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-18', 'JAPA1276'),
('Week 7 Tutorial - Oral Expression', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-25', 'JAPA1276'),
('Japanese Culture In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-01-08', 'JAPA2433'),
('Introduction to Japanese Grammar', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-08', 'JAPA2433'),
('Japanese Culture: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-24', 'JAPA2433'),
('Introduction to Calculus', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-07', 'MATH3232'),
('Unit 1 Test - Calculus', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-02-06', 'MATH3232'),
('Laboratory: Numerical Methods', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-02-22', 'MATH3232'),
('Week 9 Lecture - Calculus', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-18', 'MATH3232'),
('Chapter Quiz: Numerical Methods', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-03-20', 'MATH3232'),
('Week 8 Tutorial - Organic Chemistry', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-28', 'CHEM1822'),
('Chapter Quiz: Quantum Physics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-01-15', 'PHYS2976'),
('Introduction to Electromagnetism', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-06', 'PHYS2976'),
('Introduction to Electromagnetism', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-07', 'PHYS2976'),
('Chapter Quiz: Human Biology', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-01-28', 'BIOL1614'),
('Quiz 4 - Cell Biology', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-03-06', 'BIOL1614'),
('Microbiology In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-03-27', 'BIOL1614'),
('Chapter Quiz: Cell Biology', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-04-14', 'BIOL1614'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-04-30', 'BIOL1614'),
('Chapter Quiz: French Grammar', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-09-27', 'FRENCH2928'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-10-26', 'MATH2944'),
('Tutorial: Calculus Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-12-14', 'MATH2944'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-12-14', 'MATH2944'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-09-16', 'BIOL3303'),
('Quiz 1 - Cell Biology', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-09-17', 'BIOL3303'),
('Chapter Quiz: Organic Chemistry', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-11-17', 'CHEM2727'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-10-24', 'PHYS2191'),
('Mechanics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-15', 'PHYS2191'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-01-12', 'CHEM1149'),
('Week 4 Lecture - Inorganic Chemistry', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-16', 'CHEM1149'),
('Introduction to Organic Chemistry', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-26', 'CHEM1149'),
('Week 5 Tutorial - Analytical Methods', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-20', 'CHEM1149'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-03-27', 'CHEM1149'),
('Introduction to IT Project Management', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-07', 'INFO1502'),
('Data Analytics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-04', 'INFO1502'),
('Tutorial: Database Design Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-04', 'INFO1502'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-04-25', 'INFO1502'),
('Week 4 Tutorial - Statistics', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-29', 'MATH1669'),
('Statistics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-20', 'MATH1669'),
('Introduction to Calculus', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-06', 'MATH1669'),
('Discrete Mathematics In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-03-22', 'MATH1669'),
('Introduction to Linear Algebra', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-10', 'MATH1669'),
('Statistics Practical', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-09-06', 'MATH2087'),
('Tutorial: Probability Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-10', 'MATH2087'),
('Week 10 Lecture - DevOps', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-21', 'SWEN2928'),
('Week 5 Tutorial - Software Design', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-31', 'SWEN2928'),
('Requirements Engineering In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-02-28', 'SWEN2928'),
('Laboratory: Software Design', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-03-02', 'SWEN2928'),
('Requirements Engineering In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-04-27', 'SWEN2928'),
('Week 9 Tutorial - Chinese Culture', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-23', 'CHIN3353'),
('Week 8 Lecture - Chinese Culture', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-15', 'CHIN3353'),
('Introduction to Verb Conjugation', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-05', 'SPAN3251'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-11-29', 'SPAN3251'),
('Quiz 1 - Hispanic Literature', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-12-06', 'SPAN3251'),
('Tutorial: Geophysics Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-22', 'GEOL3439'),
('Quiz 2 - Structural Geology', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-03-15', 'GEOL3439'),
('Structural Geology In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-03-25', 'GEOL3439'),
('Computer Architecture In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-09-08', 'COMP1450'),
('Week 7 Lecture - Networking', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-27', 'COMP1450'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-10-15', 'COMP1450'),
('Week 8 Lecture - Networking', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-21', 'COMP1450'),
('Quiz 2 - Databases', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-12-12', 'COMP1450'),
('Week 1 Tutorial - Spectroscopy', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-19', 'CHEM3088'),
('Tutorial: Inorganic Chemistry Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-09', 'CHEM3088'),
('Quiz 1 - Statistics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-11-16', 'MATH2278'),
('Week 9 Lecture - Microbiology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-22', 'BIOL2569'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-02-28', 'MATH1726'),
('Linear Algebra In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-03-16', 'MATH1726'),
('Chapter Quiz: Organic Chemistry', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-11-19', 'CHEM1799'),
('Chapter Quiz: Operating Systems', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-02-26', 'COMP3228'),
('Week 11 Lecture - Software Engineering', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-29', 'COMP3228'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-11-15', 'BIOL3356'),
('Introduction to Genetics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-13', 'BIOL3356'),
('Electromagnetism: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-08', 'PHYS1957'),
('Introduction to Wave Optics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-02', 'PHYS1957'),
('Introduction to Electromagnetism', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-08', 'PHYS1957'),
('Week 6 Lecture - Structural Geology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-14', 'GEOL1338'),
('Quiz 1 - Networking', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-11-16', 'COMP3445'),
('Unit 1 Test - Computer Architecture', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-02-25', 'COMP1624'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-03-21', 'COMP1624'),
('Petrology Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-24', 'GEOL2129'),
('Introduction to Mineralogy', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-25', 'GEOL2129'),
('Mineralogy Practical', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-09-27', 'GEOL2129'),
('Tutorial: Geophysics Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-30', 'GEOL2129'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-01-20', 'BIOL1935'),
('Ecology: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-15', 'BIOL1935'),
('Introduction to Human Biology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-21', 'BIOL1935'),
('Lab Session 1 - Genetics', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-04-03', 'BIOL1935'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-04-08', 'BIOL1935'),
('Quiz 1 - IT Project Management', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-01-06', 'INFO1959'),
('Week 6 Tutorial - IT Project Management', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-22', 'INFO1959'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-03-11', 'INFO1959'),
('Week 3 Lecture - Information Security', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-11', 'INFO1959'),
('Earth History: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-11', 'GEOL2833'),
('Introduction to Earth History', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-16', 'GEOL2833'),
('Structural Geology Practical', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-10-16', 'GEOL2833'),
('Introduction to Petrology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-17', 'GEOL2833'),
('Geophysics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-21', 'GEOL2833'),
('Lecturer Office Hours - Week 6', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-01-28', 'PHYS3393'),
('Introduction to Thermodynamics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-18', 'PHYS3393'),
('Introduction to Wave Optics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-09', 'PHYS3393'),
('Introduction to Mechanics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-17', 'PHYS3393'),
('Introduction to Thermodynamics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-24', 'PHYS3393'),
('Numerical Methods: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-16', 'MATH3004'),
('Tutorial: Linear Algebra Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-22', 'MATH3004'),
('Chapter Quiz: Statistics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-10-13', 'MATH3004'),
('Linear Algebra: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-16', 'MATH3004'),
('Week 10 Lecture - Numerical Methods', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-05', 'MATH3004'),
('Week 2 Lecture - Genetics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-15', 'BIOL1818'),
('Introduction to Genetics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-21', 'BIOL1818'),
('Week 10 Lecture - Microbiology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-23', 'BIOL1818'),
('Quiz 2 - Oral Expression', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-09-22', 'JAPA2115'),
('Unit 1 Test - Oral Expression', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-10-01', 'JAPA2115'),
('Kanji In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-10-08', 'JAPA2115'),
('Lecturer Office Hours - Week 3', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-10-14', 'GEOL2884'),
('Mineralogy: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-04', 'GEOL2884'),
('Mineralogy In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-11-28', 'GEOL2884'),
('Week 6 Tutorial - Probability', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-06', 'MATH2153'),
('Statistics Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-25', 'MATH2153'),
('Week 7 Lecture - Probability', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-04', 'MATH2153'),
('Unit 1 Test - Statistics', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-12-08', 'MATH2153'),
('Tutorial: Human Biology Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-01', 'BIOL3141'),
('Microbiology Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-03', 'BIOL3141'),
('Quiz 1 - Ecology', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-11-21', 'BIOL3141'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-12-02', 'BIOL3141'),
('Algorithms Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-02', 'COMP3162'),
('Lab Session 1 - Operating Systems', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-11-09', 'COMP3162'),
('Week 13 Lecture - Software Engineering', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-30', 'COMP3162'),
('Introduction to Linear Algebra', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-10', 'MATH2933'),
('Quiz 1 - Statistics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-11-17', 'MATH2933'),
('Thermodynamics In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-04-06', 'PHYS1762'),
('Week 2 Lecture - Earth History', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-19', 'GEOL1496'),
('Unit 1 Test - Mineralogy', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-09-21', 'GEOL1496'),
('Unit 2 Test - Geophysics', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-10-03', 'GEOL1496'),
('Week 11 Tutorial - Geophysics', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-16', 'GEOL1496'),
('Chapter Quiz: Petrology', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-12-14', 'GEOL1496'),
('Lecturer Office Hours - Week 2', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-09-08', 'JAPA2339'),
('Week 4 Lecture - Hiragana & Katakana', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-10', 'JAPA2339'),
('Oral Expression: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-23', 'JAPA2339'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-09-11', 'CHEM3173'),
('Introduction to Organic Chemistry', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-23', 'CHEM3173'),
('Lecturer Office Hours - Week 3', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-10-25', 'CHEM3173'),
('Week 2 Tutorial - Analytical Methods', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-28', 'CHEM3173'),
('Quiz 1 - Organic Chemistry', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-11-20', 'CHEM3173'),
('Quiz 1 - Wave Optics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-10-01', 'PHYS1770'),
('Unit 1 Test - Mechanics', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-10-05', 'PHYS1770'),
('Week 1 Tutorial - Thermodynamics', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-01', 'PHYS1770'),
('Week 10 Lecture - Quantum Physics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-14', 'PHYS1770'),
('Week 1 Tutorial - Earth History', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-27', 'GEOL2100'),
('Week 8 Tutorial - Earth History', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-29', 'GEOL2100'),
('Cell Biology: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-24', 'BIOL1757'),
('Ecology In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-03-12', 'BIOL1757'),
('Microbiology: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-21', 'BIOL1757'),
('Week 5 Lecture - Human Biology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-25', 'BIOL1757'),
('Week 13 Tutorial - Written Composition', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-20', 'FRENCH1079'),
('Lecturer Office Hours - Week 10', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-12-12', 'FRENCH1079'),
('Quiz 1 - Geophysics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-10-29', 'GEOL2031'),
('Spectroscopy: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-25', 'CHEM2495'),
('Tutorial: Structural Geology Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-07', 'GEOL2890'),
('Tutorial: Geophysics Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-11', 'GEOL2890'),
('Week 7 Lecture - Mineralogy', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-23', 'GEOL2890'),
('Week 13 Lecture - Wave Optics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-25', 'PHYS2096'),
('Ecology Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-04', 'BIOL2143'),
('Cell Biology Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-24', 'BIOL2143'),
('French Grammar: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-03', 'FRENCH1967'),
('Week 8 Tutorial - Oral Expression', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-21', 'FRENCH1967'),
('Week 6 Tutorial - Mineralogy', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-10', 'GEOL1402'),
('Tutorial: Kanji Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-04', 'JAPA3108'),
('Tutorial: Hiragana & Katakana Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-22', 'JAPA3108'),
('Kanji: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-26', 'JAPA3108'),
('Week 5 Tutorial - Japanese Grammar', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-29', 'JAPA3108'),
('Chapter Quiz: Hiragana & Katakana', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-09-16', 'JAPA2151'),
('Oral Expression In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-09-18', 'JAPA2151'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-09-30', 'JAPA2151'),
('Introduction to Kanji', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-12', 'JAPA2151'),
('Mineralogy: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-06', 'GEOL3084'),
('Mineralogy In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-03-31', 'GEOL3084'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-10-08', 'BIOL2803'),
('Cell Biology In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-10-19', 'BIOL2803'),
('Week 6 Lecture - Ecology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-22', 'BIOL2803'),
('Week 13 Lecture - Human Biology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-14', 'BIOL2803'),
('Human Biology: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-26', 'BIOL2803'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-09-07', 'BIOL1804'),
('Genetics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-25', 'BIOL1804'),
('Laboratory: Human Biology', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-12-01', 'BIOL1804'),
('Chapter Quiz: Mechanics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-02-09', 'PHYS2196'),
('Week 5 Tutorial - Thermodynamics', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-07', 'PHYS2196'),
('Human Biology In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-09-21', 'BIOL2711');

INSERT INTO CalendarEvent (event_name, details, event_date, c_code) VALUES
('Genetics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-27', 'BIOL2711'),
('Ecology: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-29', 'BIOL2711'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-02-11', 'GEOL2731'),
('Quiz 1 - Earth History', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-04-19', 'GEOL2731'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-03-23', 'PHYS2028'),
('Introduction to Thermodynamics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-28', 'PHYS2028'),
('Chapter Quiz: Geophysics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-09-24', 'GEOL1368'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-10-06', 'GEOL1368'),
('Introduction to Petrology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-05', 'GEOL1368'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-12-07', 'GEOL1368'),
('Tutorial Support Hour', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-03-01', 'COMP2513'),
('Chapter Quiz: Software Engineering', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-04-22', 'COMP2513'),
('Week 6 Lecture - Human Biology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-13', 'BIOL3040'),
('Drop-In Help Session', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-09-27', 'BIOL3040'),
('Cell Biology: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-03', 'BIOL3040'),
('Cell Biology In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-10-24', 'BIOL3040'),
('Week 7 Tutorial - Microbiology', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-12-11', 'BIOL3040'),
('Week 9 Tutorial - Written Composition', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-28', 'FRENCH2966'),
('Introduction to Oral Expression', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-16', 'FRENCH2966'),
('Quiz 1 - Oral Expression', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-11-29', 'FRENCH2966'),
('Listening Comprehension: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-29', 'FRENCH2966'),
('Tutorial: Written Composition Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-09', 'FRENCH2116'),
('Written Composition: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-21', 'FRENCH2116'),
('Unit 1 Test - Francophone Literature', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-03-14', 'FRENCH2116'),
('Tutorial: Software Testing Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-02-10', 'SWEN1583'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-04-22', 'SWEN1583'),
('Tutorial: Statistics Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-09-25', 'MATH2739'),
('Tutorial: Linear Algebra Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-04', 'MATH2739'),
('Calculus Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-11-09', 'MATH2739'),
('Week 5 Lecture - Numerical Methods', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-16', 'MATH2739'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-11-17', 'MATH2739'),
('Introduction to Discrete Mathematics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-12', 'MATH1554'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-09-09', 'COMP1382'),
('Introduction to Software Engineering', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-26', 'COMP1382'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-10-27', 'COMP1382'),
('Lecturer Office Hours - Week 3', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-01-16', 'COMP1093'),
('Computer Architecture: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-03', 'COMP1093'),
('Tutorial: Computer Architecture Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-08', 'COMP1093'),
('Week 2 Tutorial - Computer Architecture', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-13', 'COMP1093'),
('Unit 1 Test - Data Structures', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-03-22', 'COMP1093'),
('Quiz 1 - Calculus', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-10-04', 'MATH1790'),
('Linear Algebra: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-23', 'MATH1790'),
('Chapter Quiz: Calculus', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-09-13', 'MATH3224'),
('Week 8 Lecture - Discrete Mathematics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-28', 'MATH3224'),
('Tutorial: Numerical Methods Practice', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-06', 'MATH3224'),
('Week 13 Lecture - Statistics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-10', 'MATH3224'),
('Week 3 Lecture - Probability', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-23', 'MATH3224'),
('Cell Biology Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-10', 'BIOL3492'),
('Quiz 1 - Human Biology', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-01-10', 'BIOL3492'),
('Genetics Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-29', 'BIOL3492'),
('Lecturer Office Hours - Week 12', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-04-18', 'BIOL3492'),
('Human Biology: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-23', 'BIOL3492'),
('Mechanics In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-02-13', 'PHYS1308'),
('Week 3 Lecture - Thermodynamics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-12', 'PHYS1308'),
('Mechanics Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-04-23', 'PHYS1308'),
('Week 5 Lecture - Francophone Literature', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-18', 'FRENCH1179'),
('Genetics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-19', 'BIOL3377'),
('Lab Session 1 - Statistics', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-02-13', 'MATH3490'),
('Week 7 Lecture - Statistics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-25', 'MATH3490'),
('Probability: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-26', 'MATH3490'),
('Microbiology In-Class Quiz', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-09-24', 'BIOL1530'),
('Quiz 2 - Genetics', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-10-21', 'BIOL1530'),
('Microbiology: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-10-30', 'BIOL1530'),
('Final Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-12-08', 'BIOL1530'),
('Organic Chemistry Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-03-13', 'CHEM3138'),
('Week 4 Lecture - Thermochemistry', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-08', 'CHEM3138'),
('Chapter Quiz: Spectroscopy', 'Closed-book quiz. Covers material from the last three weeks of lectures.', '2025-04-14', 'CHEM3138'),
('Introduction to Operating Systems', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-11-19', 'COMP2730'),
('Week 8 Lecture - Networking', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-05', 'COMP2730'),
('Introduction to Mineralogy', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-03', 'GEOL1581'),
('Laboratory: Petrology', 'Lab coats and safety goggles required. Pre-lab worksheet must be completed beforehand.', '2025-02-27', 'GEOL1581'),
('Lecturer Office Hours - Week 11', 'No appointment needed. Bring questions from lectures, tutorials, or assignments.', '2025-04-21', 'GEOL1581'),
('Discrete Mathematics Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-01-21', 'MATH2071'),
('Introduction to Statistics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-01-21', 'MATH2071'),
('Week 13 Lecture - Linear Algebra', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-01', 'MATH2071'),
('Discrete Mathematics: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-06', 'MATH2071'),
('Thermochemistry: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-09-10', 'CHEM2318'),
('Inorganic Chemistry Problem-Solving Session', 'Bring your workbook. Solutions to the previous tutorial will be reviewed.', '2025-10-16', 'CHEM2318'),
('Analytical Methods: Theory and Applications', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-12-10', 'CHEM2318'),
('Midterm Examination', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-01-20', 'BIOL1791'),
('Week 7 Lecture - Ecology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-02-11', 'BIOL1791'),
('Week 9 Lecture - Genetics', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-03-09', 'BIOL1791'),
('Unit 2 Test - Microbiology', 'Formal assessment. Bring student ID, pens, and approved calculators only.', '2025-04-11', 'BIOL1791'),
('Week 3 Lecture - Microbiology', 'Attendance is strongly encouraged. Lecture notes will be posted after the session.', '2025-04-17', 'BIOL1791');

